### ISSUE TITLE
Finite element calculation of 3D surface

### ISSUE THREAD

**Issue by HFH104864** [mfem/mfem#2546] opened 2021-09-17 07:05 UTC
Dear MFEM Maintainer 
  I have a finite element model of 3D curved surface, and I wonder if MFEM can solve it.

  I put the mesh model into THE EX2 of MFEM to try to solve it, but it seems that THE EX2 of MEFM only solves the problems of 2D  plane model and 3D solid model.I input my model into the EX2 solution, but the node displacement is only in the X and Y directions, which is obviously not what I want.

For this 3D surface model, if it is in ANSYS, a thickness parameter needs to be specified, I would like to ask if MFEM can do the same.

If possible, please let me know what I need to know, I would be very grateful!

**Comment by tzanio** [comment] 2021-09-17 15:46
Duplicate of #2547

**Closed by tzanio** 2021-09-17 15:46 UTC
