### ISSUE TITLE
Problem with Example 1 for continuous beam-quad.mesh

### ISSUE THREAD

**Issue by PanuLappalainen** [mfem/mfem#1519] opened 2020-06-04 14:03 UTC
The [General MFEM Mesh Format page](https://mfem.org/mesh-format-v1.x/#topology) lists a non-periodic and periodic versions of `data/beam-quad.mesh`. Their difference is illustrated with their results of a simple Laplace problem with homogeneous essential boundary conditions.

Running [Example 1](https://github.com/mfem/mfem/blob/master/examples/ex1.cpp) for the non-periodic beam-quad mesh yields me the same image as illustrated on the page, but for the periodic beam-quad mesh ([Listing 5](https://mfem.org/mesh-format-v1.x/#listing-5)) the image instead looks like this:
![GLVis_s01](https://user-images.githubusercontent.com/66424587/83764027-16ff2280-a682-11ea-8854-36188f9afa54.png)
This has puzzled me for a long time and I don't know what I'm missing. Can you please help me to I get the proper image for the periodic case?

**Comment by mlstowell** [comment] 2020-06-04 20:28
Hi, @PanuLappalainen ,

Sorry for the trouble.  I can confirm the behavior you're seeing with ex1p and the mesh in `Listing 5`.  I believe the trouble is that the mesh shown online has removed the nodes at the end of the beam in `beam-quad.mesh` which were numbered 8 and 17.  This leaves a gap in the node numbering which may be leading to a problem.  If we renumber the nodes so that they are contiguous the problem goes away.
![GLVis_s01](https://user-images.githubusercontent.com/6109571/83806946-1c9b3f00-a667-11ea-8368-abd48029f6c0.png)
The edited mesh would be:
```
MFEM mesh v1.0

#
# MFEM Geometry Types (see mesh/geom.hpp):
#
# POINT       = 0
# SEGMENT     = 1
# TRIANGLE    = 2
# SQUARE      = 3
# TETRAHEDRON = 4
# CUBE        = 5
#

dimension
2

elements
8
1 3 0 1 9 8
1 3 1 2 10 9
1 3 2 3 11 10
1 3 3 4 12 11
2 3 4 5 13 12
2 3 5 6 14 13
2 3 6 7 15 14
2 3 7 0 8 15

boundary
16
3 1 0 1
3 1 1 2
3 1 2 3
3 1 3 4
3 1 4 5
3 1 5 6
3 1 6 7
3 1 7 0
3 1 9 8
3 1 10 9
3 1 11 10
3 1 12 11
3 1 13 12
3 1 14 13
3 1 15 14
3 1 8 15

vertices
16

nodes
FiniteElementSpace
FiniteElementCollection: L2_T1_2D_P1
VDim: 2
Ordering: 1

0 0
1 0
0 1
1 1

1 0
2 0
1 1
2 1

2 0
3 0
2 1
3 1

3 0
4 0
3 1
4 1

4 0
5 0
4 1
5 1

5 0
6 0
5 1
6 1

6 0
7 0
6 1
7 1

7 0
8 0
7 1
8 1

8 0
9 0
8 1
9 1

9 0
10 0
9 1
10 1
```

I can edit the web pages to put this new mesh in place of listing 5.

Best wishes,
Mark

**Comment by mlstowell** [comment] 2020-06-04 22:00
I just created a PR, [#56](https://github.com/mfem/web/pull/56), to address this issue in the documentation.

**Comment by mlstowell** [comment] 2020-06-04 22:02
BTW: In that PR I found a quicker solution.  Just change the number of vertices to 17 or 18 (basically anything larger than 16).  In other words, pretend the removed vertices are still part of the mesh and let MFEM renumber the vertices for you.

**Comment by v-dobrev** [comment] 2020-06-04 23:59
Having unused vertices in a mesh used to be ok. It may be better to still support that instead of changing the example.

**Comment by v-dobrev** [comment] 2020-06-05 00:29
Looking at this more closely, it looks like the mesh in Listing 5 had an issue to begin with (as pointed out in https://github.com/mfem/web/pull/56). That was somehow fine in older versions of MFEM, e.g. in v3.3.

**Comment by PanuLappalainen** [comment] 2020-06-05 12:00
Thank you for the help!

Is it possible to use MFEM to produce the mesh file corresponding to one suggested by @mlstowell ? 
I believe the topology could be achieved with the following code:
```
    int quadCount = 7; // Number of quadrilaterals (excluding "fused")

    // Mesh params:      Dim, NVert,        NElem,       NBdrElem, spaceDim 
    Mesh* mesh = new Mesh(2, 2*quadCount+2, quadCount+1, 2*quadCount+2, 2);

    // Create vertices
    for (int i = 0; i < 2; i++) // Loop over the 2 rows of vertices
    {
        for (int j = 0; j < quadCount+1; j++) // Loop over the elements
        {
            const double vertex[2] = {1.0*j, 1.0*i};
            mesh->AddVertex(vertex);
        }
    }

    // Create quads and boundaries by looping over elements
    for (int q = 0; q < quadCount; q++)
    {
        const int quad[4] = {q, q+1, q+quadCount+2, q+quadCount+1};
        mesh->AddQuad(quad);

        const int bd1[2] = {q, q+1};
        mesh->AddBdrSegment(bd1, 3);
        const int bd2[2] = {q+quadCount+2, q+quadCount+1};
        mesh->AddBdrSegment(bd2, 3);
    }

    // Create the "fused" quad that connects to the initial vertices
    const int quadF[4] = {quadCount, 0, quadCount+1, 2*quadCount+1};
    mesh->AddQuad(quadF);

    // Create the "fused" boundaries
    const int bd1F[2] = {quadCount,0};
    mesh->AddBdrSegment(bd1F,3);
    const int bd2F[2] = {quadCount+1, 2*quadCount+1};
    mesh->AddBdrSegment(bd2F,3);
```
but I have been unable to deduce or find examples of creating the periodic geometry and saving it to a `.mesh` file with `FiniteElementCollection: L2_T1_2D_P1`. I've tried using the [MakePeriodicMesh](https://github.com/mfem/mfem/blob/bravais-dev/miniapps/common/bravais.cpp#L6864-L7148) but I'm highly unsure if it's a good approach.

**Comment by mlstowell** [comment] 2020-06-05 18:10
Hi, @PanuLappalainen ,
The easiest way to produce the geometry is to start with a non-periodic mesh and use `Mesh::SetCurvature` to create the `L2_T1_2D_P1` representation of the vertex coordinates.  This is one of the things `MakePeriodicMesh` does for you.  There are, of course, many ways to accomplish this task.  If you build it manually you need to make assumptions about the order of `L2` degrees of freedom within each element and the order of the x and y components of the coordinates.  Have you seen issue #1256?  This contains links to the code which is not yet part of MFEM's master branch.
If you're still unsure about `MakePeriodicMesh` I'd be happy to hear your concerns.  I would like to move this into MFEM one day so user feedback to improve it would be very helpful.
Best wishes,
Mark

**Comment by PanuLappalainen** [comment] 2020-06-09 18:22
Can you explain why the periodic beam-quad mesh ([Listing 5](https://mfem.org/mesh-format-v1.x/#listing-5)) lists 10x4 nodes, even though there are only 8 square elements?

I have by far failed to programmatically create the Listing 5 mesh. I've managed to do it neither with `MakePeriodicMesh` nor manually, though I would prefer the latter.

**Comment by PanuLappalainen** [comment] 2020-06-11 13:39
Thank you for clearing up the Listing 5 confusion and many thanks for the example code! This has been a huge help.

I hope it's not a bad idea to steal the coordinate data from the topology, e.g. in case it doesn't follow a grid. In the case of above code this can be done with a minor alteration to the coordinates loop:
```
   for (int q = 0; q < quadCount+1; q++)
   {
      (*coords)[8*q+0] = mesh->GetVertex(q+0)[0]; 
      (*coords)[8*q+1] = mesh->GetVertex(q+0)[1]; 

      (*coords)[8*q+2] = mesh->GetVertex(q+1)[0]; 
      (*coords)[8*q+3] = mesh->GetVertex(q+1)[1]; 

      (*coords)[8*q+4] = mesh->GetVertex(q+2+quadCount)[0]; 
      (*coords)[8*q+5] = mesh->GetVertex(q+2+quadCount)[1]; 

      (*coords)[8*q+6] = mesh->GetVertex(q+3+quadCount)[0]; 
      (*coords)[8*q+7] = mesh->GetVertex(q+3+quadCount)[1]; 
   }
```
(Although I will likely avoid using the `mesh->GetVertex` by keeping the vertices' coordinates in a separate array.)

Best wishes,
Panu

**Comment by mlstowell** [comment] 2020-06-11 17:36
No, I don't think that's a bad idea at all.  In fact, I think this is essentially what `Mesh::SetCurvature` does.

**Comment by tzanio** [comment] 2020-06-17 22:34
This was fixed by https://github.com/mfem/web/commit/d8a8f99e3d7ce6ce0da7db66f935f902c8d24aa3.

**Closed by tzanio** 2020-06-17 22:34 UTC
Labels: documentation, examples & miniapps, fem, mesh, usage

**Comment by PanuLappalainen** [comment] 2020-06-18 08:53
Thank you for the fix. The extra set of nodes in the end of the file appears to still remain in [Listing 5](https://mfem.org/mesh-format-v1.x/#listing-5).


> If you're still unsure about `MakePeriodicMesh` I'd be happy to hear your concerns. I would like to move this into MFEM one day so user feedback to improve it would be very helpful.

@mlstowell , I could be interested in looking into `MakePeriodicMesh` as an alternate solution to manually making the periodicity, but I'm having problems with the translation vectors. Could you perhaps provide a simple example of using `MakePeriodicMesh` to create the periodicity in the Listing 5 mesh, so I can study it to expand it into our 3D mesh?
