### ISSUE TITLE
Unit tests failing on some machines

### ISSUE THREAD

**Issue by dylan-copeland** [mfem/mfem#1343] opened 2020-03-09 18:38 UTC
On my local machine, the unit tests fail in functions such as SmemPADiffusionApply3D. I suppose this is because I do not have cuda or other GPU capabilities installed. Until recently, this happened only in TEST_CASE("H1 pa_coeff") in tests/unit/fem/test_pa_coeff.cpp, so I would just comment out that test. Now it also happens in tests/unit/linalg/test_matrix_square.cpp when pa.FormLinearSystem is called and SmemPADiffusionApply3D is entered, so the problem is spreading. It seems this is not an issue in the automated testing, so I assume cuda is installed on the machines that perform the testing. 

Is there a simple solution such as disabling such tests based on build options?

**Comment by jandrej** [comment] 2020-03-09 18:40
You can always use the labels to filter for tests or exclude tests.

**Comment by dylan-copeland** [comment] 2020-03-09 18:52
@jandrej Yes, the following passes, although it is a bit cumbersome and omits CPU-versions of the tests which should pass. This is fine for now, but it would be nice to separate the CPU and GPU tests and automatically exclude GPU tests based on build options. 

`./unit_tests ~"H1 pa_coeff" ~"FormLinearSystem" ~"ParallelFormLinearSystem"`

**Comment by tzanio** [comment] 2020-03-09 19:02
@dylan-copeland, how do you configure and run? Is this a Linux box?

The unit tests should not fail...

**Comment by dylan-copeland** [comment] 2020-03-09 19:33
> @dylan-copeland, how do you configure and run? Is this a Linux box?
> 
> The unit tests should not fail...

@tzanio It is a Linux desktop, and I configure with MFEM_USE_MPI, MFEM_USE_METIS_5, MFEM_USE_MEMALLOC, MFEM_USE_ZLIB set to YES, everything else set to NO (master branch). 

Also, on LC machines `make unittest` fails since `mpirun` is not found, and `tests/unit/unit_tests` runs with 11 failures. In previous versions of mfem, unit tests ran successfully on LC.

**Comment by IdoAkkerman** [comment] 2020-03-09 19:37
Is this in docker?

Verstuurd vanaf mijn iPhone

**Comment by dylan-copeland** [comment] 2020-03-09 19:59
@IdoAkkerman Correct, it is not in docker.

**Comment by rcarson3** [comment] 2020-03-09 20:00
I'm not seeing this behavior on my Linux desktop with a clean build of master built with cmake. I pretty much have the same set of options except for no zlib, and I'm making use of RAJA. If it helps any I'm compiling everything with gcc@7.4.0 and mpich@3.3.2.

**Comment by dylan-copeland** [comment] 2020-03-09 20:20
I am using g++ 4.8.5 and mpich 3.2.1 on my Linux desktop.

**Comment by tzanio** [comment] 2020-03-09 20:58
@dylan-copeland, can I stop  by to figure out what is going on? The tests run fine on Travis and some of our Mac and Linux boxes, so this is not the expected behavior.

Regarding LC, you should configure MFEM differently there, and specifically use `MFEM_MPIEXEC="srun"` and `MFEM_MPIEXEC_NP="-n"`. See the config line here for more details: https://mybitbucket.llnl.gov/projects/MFEM/repos/autotest/commits/4a1d8135c4307480a12275758b7a23fc7707fd44#toss_3_x86_64_ib/2020-03-09-llnl-gh-master/build-test-basic.out

Tzanio

**Comment by dylan-copeland** [comment] 2020-03-09 21:08
@tzanio Yes, I am available.

**Comment by tzanio** [comment] 2020-03-09 21:51
The issue seem to be due to an old version of GCC, which for example fails on the following Example 9p run:
```
mpirun -np 4 ex9p -pa -m ../data/periodic-cube.mesh
```

**Comment by v-dobrev** [comment] 2020-03-09 22:32
I have the same issue with gcc 4.8.5. The solution is to use a newer compiler (4.9.2 works fine for me) or to lower the optimization option for building mfem from `-O3` to `-O2`.

**Comment by tzanio** [comment] 2020-03-14 17:35
I'm closing this now, but please reopen if the issue is not resolved by compiler update

**Closed by tzanio** 2020-03-14 17:35 UTC
Labels: bug, testing
