### ISSUE TITLE
Element reordering in MFEM mesh v1.2

### ISSUE THREAD

**Issue by M8kmyday** [mfem/mfem#3947] opened 2023-10-23 13:46 UTC
I am importing a serial mesh then immediately writing it back out:
    *mesh=new Mesh;
    mesh->Load(inputMeshFile, 1, 1);
    mesh->Save(outputMeshFile)

Doing an sdiff on the input and output mesh files, I get

    MFEM mesh v1.2						      |	MFEM mesh v1.0

    #								#
    # MFEM Geometry Types (see mesh/geom.hpp):			# MFEM Geometry Types (see mesh/geom.hpp):
    #								#
    # POINT       = 0						# POINT       = 0
    # SEGMENT     = 1						# SEGMENT     = 1
    # TRIANGLE    = 2						# TRIANGLE    = 2
    # SQUARE      = 3						# SQUARE      = 3
    # TETRAHEDRON = 4						# TETRAHEDRON = 4
    # CUBE        = 5						# CUBE        = 5
    # PRISM       = 6						# PRISM       = 6
    # PYRAMID     = 7						# PYRAMID     = 7
    #								#

    dimension							dimension
    2								2

    elements							elements
    22								22
    1 2 0 1 2							1 2 0 1 2
    1 2 0 3 4							1 2 0 3 4
    1 2 0 5 1							1 2 0 5 1
    1 2 4 6 0							1 2 4 6 0
    1 2 7 0 2							1 2 7 0 2
    1 2 8 4 9							1 2 8 4 9
    1 2 4 10 11							1 2 4 10 11
    1 2 0 7 3						      |	1 2 3 0 7
    1 2 4 8 6							1 2 4 8 6
    1 2 4 11 9							1 2 4 11 9
    1 2 12 13 2							1 2 12 13 2
    1 2 5 0 6						      |	1 2 0 6 5
    1 2 11 14 9							1 2 11 14 9
    1 2 10 4 3							1 2 10 4 3
    1 2 15 14 11							1 2 15 14 11
    1 2 16 8 9							1 2 16 8 9
    1 2 14 16 9							1 2 14 16 9
    1 2 13 7 2							1 2 13 7 2
    1 2 5 17 1							1 2 5 17 1
    1 2 10 15 11							1 2 10 15 11
    1 2 17 12 1							1 2 17 12 1
    1 2 1 12 2							1 2 1 12 2

    boundary							boundary
    12								12
    900 1 7 3							900 1 7 3
    900 1 8 6							900 1 8 6
    900 1 12 13							900 1 12 13
    900 1 6 5							900 1 6 5
    900 1 3 10							900 1 3 10
    900 1 15 14							900 1 15 14
    900 1 16 8							900 1 16 8
    900 1 14 16							900 1 14 16
    900 1 13 7							900 1 13 7
    900 1 5 17							900 1 5 17
    900 1 10 15							900 1 10 15
    900 1 17 12							900 1 17 12

    vertices							vertices
    18								18
    2								2
    -0.0604858274417405 -0.00238125					-0.0604858274417405 -0.00238125
    -0.061930450058858 -0.00670148102131573				-0.061930450058858 -0.00670148102131573
    -0.0586997734383796 -0.0064013185168163				-0.0586997734383796 -0.0064013185168163
    -0.0552400000000048 3.93712660941204e-19			-0.0552400000000048 3.93712660941204e-19
    -0.0593644459855282 0.00238125					-0.0593644459855282 0.00238125
    -0.0647600000000068 -0.0047625					-0.0647600000000068 -0.0047625
    -0.0647600000000068 3.86315961289482e-18			-0.0647600000000068 3.86315961289482e-18
    -0.0552400000000048 -0.0047625					-0.0552400000000048 -0.0047625
    -0.0647600000000068 0.0047625					-0.0647600000000068 0.0047625
    -0.0612676392719943 0.0063942736998689				-0.0612676392719943 0.0063942736998689
    -0.0552400000000048 0.0047625					-0.0552400000000048 0.0047625
    -0.0579906835877266 0.00676449844656732				-0.0579906835877266 0.00676449844656732
    -0.0600000000000048 -0.00952500000000001		      |	-0.0600000000000048 -0.009525000000000009
    -0.05524 -0.009525						-0.05524 -0.009525
    -0.0600000000000068 0.00952500000000001			      |	-0.0600000000000068 0.009525000000000009
    -0.05524 0.009525						-0.05524 0.009525
    -0.06476 0.009525						-0.06476 0.009525
    -0.06476 -0.009525						-0.06476 -0.009525
    mfem_serial_mesh_end					      <
							      <
    communication_groups					      <
    number_of_groups 1					      <
							      <
    # number of entities in each group, followed by group ids in  <
    1 0							      <
							      <
    total_shared_vertices 0					      <
    total_shared_edges 0					      <
							      <
    mfem_mesh_end						      <

Notice the re-ordering of two of the elements, and this is causing a problem: the reordering does not affect the 2D electromagetic solution, but when I import the computed dofs into a 3D space using ParSubMesh capability, the two re-ordered elements are corrupted (from my point of view).

The process I am using is to start with a 3D mesh, pull off a 2D mesh using ParSubMesh, write the 2D mesh using either an MFEM version 1.2 or 1.0 mesh, solve in 2D and save the dofs to a file, import the dofs back into the 3D program and distribute on a 3D grid function, and plot.  Running in serial, here is what I get when I write a version 1.2 mesh for the 2D program to use:

![Screenshot from 2023-10-23 08-07-41](https://github.com/mfem/mfem/assets/90462987/b34f63cf-227d-4e18-a59a-69b9bd53484d)

and here is the same shot using a version 1.0 mesh for the 2D program (this is the correct result):

![Screenshot from 2023-10-23 08-07-54](https://github.com/mfem/mfem/assets/90462987/830e9898-0625-469a-9ab0-ec445949f07a)

Here is the 2D solution, which is the same for either mesh:

![Screenshot from 2023-10-23 08-15-36](https://github.com/mfem/mfem/assets/90462987/b633d90c-18cf-4f07-b0d8-29134c997b06)

I believe that the swap in the node order of two elements in the mesh is leading to the dofs for two elements being re-ordered so that the import from the 2D solution to the 3D solution is being corrupted (from my point of view).

Note that I see the same behavior when running in serial and parallel.

Also of interest is that the re-ordering does not happen all the time.  I have many examples where no re-ordering occurs and the 2D/3D interface works perfectly in serial and parallel.  In the example above, the other two ports of this waveguide T junction do not have element re-ordering so that the imported 2D solutions are fine leading to a correct 3D solutions.  Just one port has the issue.

I'm looking for either a bug fix, if this is a bug, a feature enhancement to maintain dof ordering if not a bug, or a workaround so that I can import the dofs from my 2D program into the 3D program and maintain the expected field.

[Although the version 1.0 meshes work fine in serial and get the correct answers across a wide variety of examples, they do not work for parallel execution because of the different splits of the mesh across the ranks in 2D and 3D.  I need the version 1.2 mesh to enable parallel operation.]

**Comment by sebastiangrimberg** [comment] 2023-10-23 18:26
Hi @M8kmyday, this looks like a similar issue to something I've run into in the past. Could you perhaps give the code from https://github.com/mfem/mfem/pull/3847 a try?

**Comment by M8kmyday** [comment] 2023-10-23 20:21
This discussion is consistent with something I am seeing.  After posting this issue, I just started changing options on the mesh constructor and load methods to see what happens.  I found that setting refine=0 fixed the dof ordering issue for me.  I've been running my regression suites to see if this is a general fix (still running).  The vast majority of cases pass (10s of thousands), but some see some slight changes (say 0.1%).  I do use adaptive mesh refinement for some cases, so I don't know what refine=0 vs. refine=1 means and what it is doing.  It is possible that the newer results are better than the older result such that failing the test with a small change is not meaningful.

I'll check the code you suggest and let you know how it goes.

**Comment by sebastiangrimberg** [comment] 2023-10-23 21:53
Yes, when you specify `refine = 1` to the `Mesh` constructor, it performs a permutation of the edges in an element which can break in parallel when you have many shared edges of (near) equal length. #3847 should resolve that problem.

If you are doing refinement, the reason for the slight changes when you run with `refine = 0` vs. `refine = 1` is because the resulting mesh after refinement will be different in each case (assuming conforming triangular/tetrahedral refinement). The marking performed when `refine = 1` reorients the elements so their longest edge is split during refinement, vs. when you use `refine = 0` the edge which is split is just based on the initial mesh ordering during parsing from file.

**Comment by M8kmyday** [comment] 2023-10-24 17:00
I'm seeing #3847 partially correct the problem.  For the example above, one element is corrected while another is not:
![Screenshot from 2023-10-24 11-57-07](https://github.com/mfem/mfem/assets/90462987/20e2e553-780d-493b-b6e7-3449641e8f86)

**Comment by M8kmyday** [comment] 2023-10-24 17:45
I'm checking out a workaround where I use refine=0 when running a 3D problem, where I don't do mesh refinement on the 2D port mesh, and refine=1 when running 2D problems standalone, where I do do mesh refinement.  So far that is checking out, but I'm running the full regression suites to fully check it out.

Even if the workaround is 100% solid, I'm still interested in a fundamental solution and helping out if I can.  I can easily disable the workaround and try new MFEM code, if it helps.

**Comment by sebastiangrimberg** [comment] 2023-10-24 17:47
Hi @M8kmyday, upon reading your description more closely I think this is actually unrelated to #3847, since you are experiencing this issue in serial as well as in parallel.

The issue is likely an inherent limitation of reading your `Mesh` and `GridFunction` from file. Whenever you load a mesh from file and use `refine = 1`, you are subject to get reorientations of your elements which will invalidate the dofs associated with any `GridFunction` on the `Mesh`. This is likely what's happening to you: When you read your 2D `GridFunction` and distribute the the 3D mesh, the order of the dofs on each element may have changed and thus the `GridFunction` also needs to be permuted.

I think the solution here is to try to take more advantage of the `SubMesh`/`ParSubMesh` classes which perform the orientation changes for you when transferring `GridFunctions` to/from the parent mesh. If you can avoid writing anything to file, this will fix the issue. Alternatively, as you note, calling the `Mesh` constructor with `refine = 0` will also work since you are guaranteeing no element reorientations can occur.

**Comment by M8kmyday** [comment] 2023-10-24 19:23
Your comments give me confidence that my workaround is on solid ground.  Regressions continue, but they are looking good.  Thanks for your time and insights.

**Closed** 2023-10-24 19:24 UTC
Labels: usage, mesh
