### ISSUE TITLE
Question about example ex3

### ISSUE THREAD

**Issue by TangLaoya** [mfem/mfem#621] opened 2018-10-08 03:33 UTC
Dear all,

I noticed that example 3 is focusing on Nedelec H(curl) FEM for the definite Maxwell problem. It is very close to my project. I need to solve the following eddy current problem
curl ( u^(-1) curl E) + (i*omega*sigma-omega^2*epslion) E = -i*omega*J

where J is the current source from transmit coils. In some location, there are receive coils and the inducted voltage is measured in these coils. Therefore I need to calculate the electric field and integrate the electric field along coil loop. In my project the electric field is complex value. Could anyone help me to modify the example project to let it solve the electromagnetic excited by coils in media, such as ground? 

Thanks,
Tang Laoya

**Comment by mlstowell** [comment] 2018-10-08 16:42
Hello, @TangLaoya ,

This is something I've been slowly working on.  Currently it is on hold waiting for some related additions to MFEM.  Specifically we need classes to more easily handle complex-valued fields and operators as well as more suitable solvers.

You're welcome to look at some code which is a work in progress.  You can find it in the branch `hertz-dev`.  The code itself is `miniapps/electromagnetics/hertz.cpp`.  This is far from being polished code but I think it has the basic functionality that you're looking for.  The main problem with it currently is that the default solver is not very effective.  I believe the code can support SuperLU or STRUMPACK if they are available and I would suggest trying one of these.

Best wishes,
Mark

**Comment by TangLaoya** [comment] 2018-10-09 06:49
Dear mlstowell and tzanio,
I got to know that I need to enable 'MFEM_USE_MPI' if the feature
using namespace mfem::electromagnetics;
is used. After enabled 'MFEM_USE_MPI', the Cmake shows that I have to install the 'hypre' solver, so I download the latest hypre and built it, and the provided the hypre include and library folder in Cmake, however, this time it displayed that 'Unable to determine HYPRE version'. So I have two questions:
1) how to configure the HYPRE to let the project be configured successfully?
2) since the feature
namespace mfem::electromagnetics
doesn't relate to the MPI or HYPRE solver (I guess), could you please seperate the feature
namespace mfem::electromagnetics
with MPI or HYPRE solver, i.e., let the feature dependent to MPI and HYPRE solver?

Thanks,
Tang Laoya

**Comment by TangLaoya** [comment] 2018-10-09 08:03
Dear mlstowell,
Thank you very much for your kindly reply. I am trying to build the MFEM on Windows 7 64bit, VS2013 and Intel MPI 4.1.3.047 64bit version. I tested both HYPRE 2.11.2 and HYPRE 2.15.0 and they all failed (in fact, after I successfully built HYPRE and tried to configure the project by CMake 3.10.2 it failed). 

It would be wonderful if you can help me to modify the hertz to a serial version, I wish the FEM matrices be generated purely by MFEM instead of any other tools. 

Thanks,
Tang Laoya

**Comment by mlstowell** [comment] 2018-10-11 17:34
Hi, @TangLaoya ,
Last night we merged a large amount of new code into MFEM's master branch.  Whenever we do this I merge the new changes into all of my branches, including `hertz-dev` in this case.  Consequently, the current `hertz-dev` is rather different than the one you cloned a few days ago.  Rather than creating a serial version of `hertz` in the outdated branch I placed an updated version in the current branch.  

If you look at the most recent `hertz-dev` branch you should find a new miniapp called `hertz-ser` which is a serial version.  It only uses GMRES which performs very poorly.

Best wishes,
Mark

**Comment by TangLaoya** [comment] 2018-10-11 23:57
Dear Mark,

Thank you very much for your kindly reply. I will clone the latest code and study it carefully.

Thanks,
Tang Laoya

**Comment by TangLaoya** [comment] 2018-10-12 10:03
Dear Mark,
Thank you very much for your kindly reply. I created a project and put files 'hertz_ser.cpp' and 'hertz_ser_solver.cpp‘ into this project and built it. I also added mfem.lib into the link library. However, the following similar errors displayed:

Error	15	error LNK2019: unresolved external symbol "public: __cdecl mfem::ComplexGridFunction::ComplexGridFunction(class mfem::FiniteElementSpace *)" (??0ComplexGridFunction@mfem@@QEAA@PEAVFiniteElementSpace@1@@Z) referenced in function "public: __cdecl mfem::electromagnetics::HertzSolver::HertzSolver(class mfem::Mesh &,int,double,enum mfem::electromagnetics::HertzSolver::SolverType,enum mfem::ComplexOperator::Convention,class mfem::Coefficient &,class mfem::Coefficient &,class mfem::Coefficient *,class mfem::Coefficient *,class mfem::Array<int> &,class mfem::Array<int> &,void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &),void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &),void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &),void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &))" (??0HertzSolver@electromagnetics@mfem@@QEAA@AEAVMesh@2@HNW4SolverType@012@W4Convention@ComplexOperator@2@AEAVCoefficient@2@3PEAV72@4AEAV?$Array@H@2@5P6AXAEBVVector@2@AEAV92@@Z888@Z)	E:\mfem\mfem-hertz-dev\coiltest\hertz_ser_solver.obj	coiltest
Error	17	error LNK2019: unresolved external symbol "public: __cdecl mfem::ComplexLinearForm::ComplexLinearForm(class mfem::FiniteElementSpace *,enum mfem::ComplexOperator::Convention)" (??0ComplexLinearForm@mfem@@QEAA@PEAVFiniteElementSpace@1@W4Convention@ComplexOperator@1@@Z) referenced in function "public: __cdecl mfem::electromagnetics::HertzSolver::HertzSolver(class mfem::Mesh &,int,double,enum mfem::electromagnetics::HertzSolver::SolverType,enum mfem::ComplexOperator::Convention,class mfem::Coefficient &,class mfem::Coefficient &,class mfem::Coefficient *,class mfem::Coefficient *,class mfem::Array<int> &,class mfem::Array<int> &,void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &),void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &),void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &),void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &))" (??0HertzSolver@electromagnetics@mfem@@QEAA@AEAVMesh@2@HNW4SolverType@012@W4Convention@ComplexOperator@2@AEAVCoefficient@2@3PEAV72@4AEAV?$Array@H@2@5P6AXAEBVVector@2@AEAV92@@Z888@Z)	E:\mfem\mfem-hertz-dev\coiltest\hertz_ser_solver.obj	coiltest
Error	27	error LNK2019: unresolved external symbol "public: __cdecl mfem::miniapps::ND_FESpace::ND_FESpace(class mfem::Mesh *,int,int,int,int)" (??0ND_FESpace@miniapps@mfem@@QEAA@PEAVMesh@2@HHHH@Z) referenced in function "public: __cdecl mfem::electromagnetics::HertzSolver::HertzSolver(class mfem::Mesh &,int,double,enum mfem::electromagnetics::HertzSolver::SolverType,enum mfem::ComplexOperator::Convention,class mfem::Coefficient &,class mfem::Coefficient &,class mfem::Coefficient *,class mfem::Coefficient *,class mfem::Array<int> &,class mfem::Array<int> &,void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &),void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &),void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &),void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &))" (??0HertzSolver@electromagnetics@mfem@@QEAA@AEAVMesh@2@HNW4SolverType@012@W4Convention@ComplexOperator@2@AEAVCoefficient@2@3PEAV72@4AEAV?$Array@H@2@5P6AXAEBVVector@2@AEAV92@@Z888@Z)	E:\mfem\mfem-hertz-dev\coiltest\hertz_ser_solver.obj	coiltest
Error	21	error LNK2019: unresolved external symbol "public: __cdecl mfem::SesquilinearForm::SesquilinearForm(class mfem::FiniteElementSpace *,enum mfem::ComplexOperator::Convention)" (??0SesquilinearForm@mfem@@QEAA@PEAVFiniteElementSpace@1@W4Convention@ComplexOperator@1@@Z) referenced in function "public: __cdecl mfem::electromagnetics::HertzSolver::HertzSolver(class mfem::Mesh &,int,double,enum mfem::electromagnetics::HertzSolver::SolverType,enum mfem::ComplexOperator::Convention,class mfem::Coefficient &,class mfem::Coefficient &,class mfem::Coefficient *,class mfem::Coefficient *,class mfem::Array<int> &,class mfem::Array<int> &,void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &),void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &),void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &),void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &))" (??0HertzSolver@electromagnetics@mfem@@QEAA@AEAVMesh@2@HNW4SolverType@012@W4Convention@ComplexOperator@2@AEAVCoefficient@2@3PEAV72@4AEAV?$Array@H@2@5P6AXAEBVVector@2@AEAV92@@Z888@Z)	E:\mfem\mfem-hertz-dev\coiltest\hertz_ser_solver.obj	coiltest
Error	16	error LNK2019: unresolved external symbol "public: void __cdecl mfem::ComplexGridFunction::Update(void)" (?Update@ComplexGridFunction@mfem@@QEAAXXZ) referenced in function "public: void __cdecl mfem::electromagnetics::HertzSolver::Update(void)" (?Update@HertzSolver@electromagnetics@mfem@@QEAAXXZ)	E:\mfem\mfem-hertz-dev\coiltest\hertz_ser_solver.obj	coiltest
Error	18	error LNK2019: unresolved external symbol "public: void __cdecl mfem::ComplexLinearForm::AddDomainIntegrator(class mfem::LinearFormIntegrator *,class mfem::LinearFormIntegrator *)" (?AddDomainIntegrator@ComplexLinearForm@mfem@@QEAAXPEAVLinearFormIntegrator@2@0@Z) referenced in function "public: __cdecl mfem::electromagnetics::HertzSolver::HertzSolver(class mfem::Mesh &,int,double,enum mfem::electromagnetics::HertzSolver::SolverType,enum mfem::ComplexOperator::Convention,class mfem::Coefficient &,class mfem::Coefficient &,class mfem::Coefficient *,class mfem::Coefficient *,class mfem::Array<int> &,class mfem::Array<int> &,void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &),void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &),void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &),void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &))" (??0HertzSolver@electromagnetics@mfem@@QEAA@AEAVMesh@2@HNW4SolverType@012@W4Convention@ComplexOperator@2@AEAVCoefficient@2@3PEAV72@4AEAV?$Array@H@2@5P6AXAEBVVector@2@AEAV92@@Z888@Z)	E:\mfem\mfem-hertz-dev\coiltest\hertz_ser_solver.obj	coiltest
Error	20	error LNK2019: unresolved external symbol "public: void __cdecl mfem::ComplexLinearForm::Assemble(void)" (?Assemble@ComplexLinearForm@mfem@@QEAAXXZ) referenced in function "public: void __cdecl mfem::electromagnetics::HertzSolver::Assemble(void)" (?Assemble@HertzSolver@electromagnetics@mfem@@QEAAXXZ)	E:\mfem\mfem-hertz-dev\coiltest\hertz_ser_solver.obj	coiltest
Error	19	error LNK2019: unresolved external symbol "public: void __cdecl mfem::ComplexLinearForm::Update(void)" (?Update@ComplexLinearForm@mfem@@QEAAXXZ) referenced in function "public: void __cdecl mfem::electromagnetics::HertzSolver::Update(void)" (?Update@HertzSolver@electromagnetics@mfem@@QEAAXXZ)	E:\mfem\mfem-hertz-dev\coiltest\hertz_ser_solver.obj	coiltest
Error	23	error LNK2019: unresolved external symbol "public: void __cdecl mfem::SesquilinearForm::AddBoundaryIntegrator(class mfem::BilinearFormIntegrator *,class mfem::BilinearFormIntegrator *,class mfem::Array<int> &)" (?AddBoundaryIntegrator@SesquilinearForm@mfem@@QEAAXPEAVBilinearFormIntegrator@2@0AEAV?$Array@H@2@@Z) referenced in function "public: __cdecl mfem::electromagnetics::HertzSolver::HertzSolver(class mfem::Mesh &,int,double,enum mfem::electromagnetics::HertzSolver::SolverType,enum mfem::ComplexOperator::Convention,class mfem::Coefficient &,class mfem::Coefficient &,class mfem::Coefficient *,class mfem::Coefficient *,class mfem::Array<int> &,class mfem::Array<int> &,void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &),void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &),void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &),void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &))" (??0HertzSolver@electromagnetics@mfem@@QEAA@AEAVMesh@2@HNW4SolverType@012@W4Convention@ComplexOperator@2@AEAVCoefficient@2@3PEAV72@4AEAV?$Array@H@2@5P6AXAEBVVector@2@AEAV92@@Z888@Z)	E:\mfem\mfem-hertz-dev\coiltest\hertz_ser_solver.obj	coiltest
Error	22	error LNK2019: unresolved external symbol "public: void __cdecl mfem::SesquilinearForm::AddDomainIntegrator(class mfem::BilinearFormIntegrator *,class mfem::BilinearFormIntegrator *)" (?AddDomainIntegrator@SesquilinearForm@mfem@@QEAAXPEAVBilinearFormIntegrator@2@0@Z) referenced in function "public: __cdecl mfem::electromagnetics::HertzSolver::HertzSolver(class mfem::Mesh &,int,double,enum mfem::electromagnetics::HertzSolver::SolverType,enum mfem::ComplexOperator::Convention,class mfem::Coefficient &,class mfem::Coefficient &,class mfem::Coefficient *,class mfem::Coefficient *,class mfem::Array<int> &,class mfem::Array<int> &,void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &),void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &),void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &),void (__cdecl*)(class mfem::Vector const &,class mfem::Vector &))" (??0HertzSolver@electromagnetics@mfem@@QEAA@AEAVMesh@2@HNW4SolverType@012@W4Convention@ComplexOperator@2@AEAVCoefficient@2@3PEAV72@4AEAV?$Array@H@2@5P6AXAEBVVector@2@AEAV92@@Z888@Z)	E:\mfem\mfem-hertz-dev\coiltest\hertz_ser_solver.obj	coiltest
Error	24	error LNK2019: unresolved external symbol "public: void __cdecl mfem::SesquilinearForm::Assemble(int)" (?Assemble@SesquilinearForm@mfem@@QEAAXH@Z) referenced in function "public: void __cdecl mfem::electromagnetics::HertzSolver::Assemble(void)" (?Assemble@HertzSolver@electromagnetics@mfem@@QEAAXXZ)	E:\mfem\mfem-hertz-dev\coiltest\hertz_ser_solver.obj	coiltest
Error	25	error LNK2019: unresolved external symbol "public: void __cdecl mfem::SesquilinearForm::Finalize(int)" (?Finalize@SesquilinearForm@mfem@@QEAAXH@Z) referenced in function "public: void __cdecl mfem::electromagnetics::HertzSolver::Assemble(void)" (?Assemble@HertzSolver@electromagnetics@mfem@@QEAAXXZ)	E:\mfem\mfem-hertz-dev\coiltest\hertz_ser_solver.obj	coiltest
Error	26	error LNK2019: unresolved external symbol "public: void __cdecl mfem::SesquilinearForm::FormLinearSystem(class mfem::Array<int> const &,class mfem::Vector &,class mfem::Vector &,class mfem::OperatorHandle &,class mfem::Vector &,class mfem::Vector &,int)" (?FormLinearSystem@SesquilinearForm@mfem@@QEAAXAEBV?$Array@H@2@AEAVVector@2@1AEAVOperatorHandle@2@11H@Z) referenced in function "public: void __cdecl mfem::electromagnetics::HertzSolver::Solve(void)" (?Solve@HertzSolver@electromagnetics@mfem@@QEAAXXZ)	E:\mfem\mfem-hertz-dev\coiltest\hertz_ser_solver.obj	coiltest
Error	28	error LNK2019: unresolved external symbol "void __cdecl mfem::miniapps::VisualizeField(class mfem::socketstream &,char const *,int,class mfem::GridFunction &,char const *,int,int,int,int,bool)" (?VisualizeField@miniapps@mfem@@YAXAEAVsocketstream@2@PEBDHAEAVGridFunction@2@1HHHH_N@Z) referenced in function "public: void __cdecl mfem::electromagnetics::HertzSolver::DisplayToGLVis(void)" (?DisplayToGLVis@HertzSolver@electromagnetics@mfem@@QEAAXXZ)	E:\mfem\mfem-hertz-dev\coiltest\hertz_ser_solver.obj	coiltest


Could you please help me to take a look at it?

**Comment by mlstowell** [comment] 2018-10-12 16:54
Hi, @TangLaoya, 
It looks like the unresolved symbols are from the new files that were added to the `hertz-dev` branch.  Is it possible that your project is not including these when building the MFEM library?  It's also possible you're linking with another version of `libmfem.dll`.  Perhaps one built from a different branch of MFEM.
Mark

**Comment by TangLaoya** [comment] 2018-10-12 19:57
Dear Mark,
I really built both the mem.lib and hertz from the hertz-dev branch, the only difference is that I used the same ‘bilininteg.cpp’ because I reported compile error with VS2013.
Thanks,
Tang Laoya

**Comment by mlstowell** [comment] 2018-10-13 00:59
Hi, @TangLaoya, 
I think the problem is that I forgot to add the new files to CMake's configuration files.  I've made the corrections in the repository.
Best wishes,
Mark

**Comment by mlstowell** [comment] 2018-10-18 03:40
Hi, @TangLaoya ,

According to MFEM's build instructions, in the file `INSTALL`, the CMake build expects HYPRE and MFEM to be installed next to each other in the filesystem.  Specifically, HYPRE should be in `../hypre-2.10.0b`.  From the error message that you posted:
```
CMake Error at config/cmake/modules/FindHYPRE.cmake:33 (message):
Unable to determine HYPRE version.
Call Stack (most recent call first):
CMakeLists.txt:131 (find_package)
```
It seems that CMake simply cannot find HYPRE.  There are a few things to try.  I'm not sure if this is possible in Windows but perhaps you could create a symbolic link from `../hypre-2.10.0b` to the actual location of your HYPRE install.  Failing that you could simply move your HYPRE install to this location even though the version number would be incorrect.  Lastly you could instruct CMake to override its expected HYPRE location with the actual location.  The last option is probably best but I'm not sure how to pass such instructions to CMake (if you don't know I may be able to find the answer.)

Best wishes,
Mark

**Comment by TangLaoya** [comment] 2018-10-18 06:14
Dear Mark,
Thank you very much for your kindly reply. I just put HYPRE to the same folder as MFEM:
E:\mfem\hypre2.11.2
E:\mfem\mfem-hertz-dev

In addition, I also set 'HYPRE_INCLUDE_DIRS' to 'E:/mfem/hypre-2.11.2/src/parcsr_mv' and set 'HYPRE_LIBRARIES' to 'E:/mfem/hypre-2.11.2/src/64bit_2013/Release/HYPRE.lib'

but still the same error.

Thanks,
Tang Laoya

**Comment by v-dobrev** [comment] 2018-10-18 06:33
The directory `hypre-2.11.2/src/parcsr_mv` is one of the source directories - it does not contain all necessary hypre headers. You need to set `HYPRE_INCLUDE_DIRS` to the directory where all the headers are installed, after the library is built. This directory is usually called `include` but I'm not sure where exactly it will be located when building with Visual Studio - try searching for it somewhere inside `E:/mfem/hypre-2.11.2/src/64bit_2013`.

**Comment by TangLaoya** [comment] 2018-10-18 07:02
Dear Mark,
Thank you very much for your kindly reply. Now the configure passed, the setting is as follows:
set 'HYPRE_DIR' to 'E:\mfem\hypre-2.11.2\src\64bit_2013'
set 'HYPRE_INCLUDE_DIR' to 'E:\mfem\hypre-2.11.2\src\64bit_2013'
set 'HYPRE_INCLUDE_DIRS' to 'E:\mfem\hypre-2.11.2\src\64bit_2013;E:\mfem\hypre-2.11.2\src\IJ_mv;E:\mfem\hypre-2.11.2\src\krylov;E:\mfem\hypre-2.11.2\src\matrix_matrix;E:\mfem\hypre-2.11.2\src\multivector;E:\mfem\hypre-2.11.2\src\parcsr_block_mv;E:\mfem\hypre-2.11.2\src\parcsr_ls;E:\mfem\hypre-2.11.2\src\parcsr_mv;E:\mfem\hypre-2.11.2\src\seq_mv;E:\mfem\hypre-2.11.2\src\sstruct_ls;E:\mfem\hypre-2.11.2\src\sstruct_mv;E:\mfem\hypre-2.11.2\src\struct_ls;E:\mfem\hypre-2.11.2\src\struct_mv;E:\mfem\hypre-2.11.2\src\utilities'
set 'HYPRE_LIBRIES' to 'E:\mfem\hypre-2.11.2\src\lib/HYPRE.lib'
set 'HYPRE_LIBRARY' to 'E:\mfem\hypre-2.11.2\src\lib/HYPRE.lib'

but errors displayed when build the project by VS2013:
c:\program files (x86)\intel\mpi\4.1.3.047\em64t\include\mpicxx.h(97): fatal error C1189: #error :  "SEEK_SET is #defined but must not be for the C++ binding of MPI. Include mpi.h before stdio.h"

Now the problem is solved by adding
-DMPICH_IGNORE_CXX_SEEK
after refereed from here
https://software.intel.com/en-us/forums/intel-c-compiler/topic/560682


Thanks,
Tang Laoya

**Comment by tzanio** [comment] 2018-10-23 15:37
@TangLaoya are you able to build now? Do you have any further questions on this issue?

**Comment by TangLaoya** [comment] 2018-10-24 08:06
Dear tzanio,
Yes, I can build the project now, but I have to do many modifications, as I described before. I don't know whether it is possible to do these modification to Cmake files.

Thanks,
Tang Laoya

**Closed** 2018-10-26 16:48 UTC
Labels: examples & miniapps, question, usage
