### ISSUE TITLE
Hypre AMS convergence issues after ReorientTetMesh depreciation

### ISSUE THREAD

**Issue by sebastiangrimberg** [mfem/mfem#2492] opened 2021-08-26 20:44 UTC
I'm testing out changes from #1046 on 3D problems with tetrahedral meshes. For the most part everything works but for a few of my test problems with my code I am seeing AMS solver convergence stall. This only seems to happen with ND space order > 1 and number of processors > 1. Calling `ReorientTetMesh` with the new build fixes the issue for the problems where it shows. Alternatively, using a direct solver also seems to eliminate the issue and the solutions match whether or not I call `ReorientTetMesh`.

 I've tried reproducing this problem using some of the MFEM examples but it seems the tetrahedral meshes there work just fine. One thing I did notice is that the Frobenius norm of the assembled system matrix does change with the new changes from #1046 (keeping the number of processors constant). The difference seems to be ~5% for the problem I'm looking at. I'm not sure if that is expected or if the changes should produce the same exact assembly of the matrix.

@mlstowell, I'm not sure if this is something you might be able to help with? Thanks!

**Comment by v-dobrev** [comment] 2021-08-28 03:27
Hi @sebastiangrimberg,

I think the issue with `ProjectBdrCoefficientTangent` comes from here: https://github.com/mfem/mfem/blob/b1e84b81275f2f1bb23a2bbd1c62a72f265fdd8b/fem/gridfunc.cpp#L2260-L2262

Can you try changing these lines to be:
```c++
      DofTransformation *dof_tr = fes->GetBdrElementDofs(i, dofs);
      lvec.SetSize(fe->GetDof());
      fe->Project(vcoeff, *T, lvec);
      if (dof_tr) { dof_tr->TransformPrimal(lvec); }
```

**Comment by sebastiangrimberg** [comment] 2021-08-28 04:32
Great find @v-dobrev, that fixes the `ProjectBdrCoefficientTangent` issue!

Perhaps it's something similar related to the discrete gradient matrix assembly for the AMS issue? I'll look in that direction.

**Comment by sebastiangrimberg** [comment] 2021-08-28 05:56
Some further testing on the convergence issue...It seems like it may be related to the mesh partitioning, perhaps some sort of corner cases between shared dofs? Here are the results of an AMS solve on a different problem than I was originally using for which I thought the new code "worked", for various numbers of subdomains:

With `ReorientTetMesh`: 1 proc, 27 its; 6 proc, 30 its; 12 proc, 28 its; 24 proc, 30 its
Without `ReorientTetMesh`: 1 proc, 27 its; 6 proc, 30 its; 12 proc, no convergence in 100 its; 24 proc, no convergence in 100 its

**Comment by mlstowell** [comment] 2021-09-02 18:13
I wonder, is it possible that the finite element space being passed to HypreAMS is a trace space? If so the construction of the discrete gradient takes a different code path which does not currently use the `DofTransformation`. We can probably make the necessary changes to `DiscreteLinearOperator::Assemble` easily enough. However, I'm not sure how we can test this. Do we have any examples or unit tests which would follow this code path?

**Comment by mlstowell** [comment] 2021-09-02 21:44
Hi, @sebastiangrimberg,

I've tested HypreAMS with a trace space using static condensation in `ex3p` and it seems to work fine. Could you send us a copy of your mesh and perhaps a bit more information about the problem you're running so we can try to reproduce the issue?

Best wishes,
Mark

**Comment by sebastiangrimberg** [comment] 2021-09-03 18:43
Hi @mlstowell and @tzanio, sorry for the delayed response on this, I've been sifting through my own code to try to debug what I could be doing wrong and comparing along the way to some modified versions of `ex3p` and `ex22p` to sanity check everything. I think I tracked the issue down to something I was doing in my code to handle Dirichlet boundary conditions that seems to no longer work, so maybe you can just confirm this for me and I can close out this issue as bug in my own code.

Previously, I would eliminate the rows/columns for Dirichlet BC dofs for a `ParBilinearForm` as

```
    a.Assemble();
    a.EliminateEssentialBC(dbc_marker, mfem::Matrix::DIAG_KEEP);
    a.Finalize();
    a.ParallelAssemble();
```

And later on in my code I would modify the diagonal values of the parallel assembled matrix to penalize the BC more or less. (This is a bit of a tangent, but I found that for example just setting the diagonals to 1 would lead to sometimes worse performance with AMG preconditioners like AMS when the other entries of the matrix were all significantly smaller or larger.) My hypothesis is that now this doesn't work anymore as expected, perhaps because of the `DofTransformation` meaning that the `P` matrix may not just be boolean now for high order `ND` spaces?

I think in that case I'll just go back to doing the elimination on the parallel assembled matrix rather than before the `ParallelAssemble` call, at the expense of a few extra zeros in the final matrix. Thank you so much, really glad to have tracked this to this point at least!

**Comment by tzanio** [comment] 2021-09-05 23:24
Great detective work, thanks for tracking this down @tuckerbabcock!

**Comment by tzanio** [comment] 2021-09-05 23:27
I think you are exactly correct -- due to the enhanced functionality of `DofTransformation`, the P matrix is no longer boolean for high-order Nedelec spaces and just like with AMR, this implies that you cannot eliminate the boundary conditions until the very end.

@mlstowell and @jakubcerveny, do you agree with this?

We should make a note about it in the code and/or the online documentation.

**Comment by sebastiangrimberg** [comment] 2021-09-06 00:53
Awesome, that makes sense to me. Thanks @tzanio! Also I believe that in this case (though I haven't tested this yet) ex13p will have a similar bug when the order is > 1 that requires fixing: https://github.com/mfem/mfem/blob/adab7bb4602b991f50716e25f4ecd0db9ff629cb/examples/ex13p.cpp#L158

**Comment by tzanio** [comment] 2021-09-12 00:18
> Has anyone thought about how this might affect using an unassembled matrix format and solver (like PETSc's MATIS and BDDC through PETSc in ex3p)? I presume these changes would cause the same types of issues there and I'm not sure how we might get around them.

I am not sure how this will affect BDDC, but hopefully @stefanozampini does. We already have the non-Boolean `P` matrix situation with AMR, so maybe it could be handled the same way.

**Comment by stefanozampini** [comment] 2021-09-12 05:29
As long as the discrete gradient is properly represented, BDDC should be fine. MATIS assembly in MFEM never assumed a boolean `P` matrix. @sebastiangrimberg Did you notice any regression in your test cases with BDDC?

**Comment by sebastiangrimberg** [comment] 2021-09-12 17:00
I haven’t actually had the chance to test this on any of the MFEM examples as the build I use isn’t linked to PETSc, but I just postulated that the problem might exist. Because the issue above seemed to be that elimination of BC at the subdomain level messed up the final assembled matrix, I’m not immediately sure how you would get around doing do when working with unassembled MATIS.

**Comment by tzanio** [comment] 2021-10-17 01:34
There hasn't been activity on this issue for over a month, so I will close it now. Feel free to re-open of you have additional questions/information.

**Closed by tzanio** 2021-10-17 01:34 UTC
Labels: bug, linalg
