### ISSUE TITLE
GetCoarseToFineMap() crashes in parallel after using GetDerefinementTransforms()

### ISSUE THREAD

**Issue by rw-anderson** [mfem/mfem#2484] opened 2021-08-20 21:38 UTC
I am not sure if I am using this interface properly. Here's a minimal example which creates a mesh, refines it twice, and then derefines it once. Refining twice seems essential to the issue.

```c++
#include "mfem.hpp"

using namespace std;
using namespace mfem;

int main(int argc, char *argv[])
{
   MPI_Session mpi(argc, argv);
   
   const char *mesh_file = "../data/star.mesh";

   OptionsParser args(argc, argv);
   args.AddOption(&mesh_file, "-m", "--mesh", "Mesh file to use.");
   args.ParseCheck();

   Mesh serial_mesh(mesh_file);
   serial_mesh.EnsureNCMesh();
   
   ParMesh pmesh(MPI_COMM_WORLD, serial_mesh);

   Array<int> refs;
   refs.Append(0);

   pmesh.GeneralRefinement(refs);
   pmesh.GeneralRefinement(refs);

   mfem::Vector zero(pmesh.GetNE());
   zero = 0.;
   pmesh.DerefineByError(zero, 1.0);

   const CoarseFineTransformations &cft =
      pmesh.ncmesh->GetDerefinementTransforms();
   Table coarse_to_fine;
   cft.GetCoarseToFineMap(pmesh, coarse_to_fine);
   
   return 0;

}
```

I am trying to obtain a map of the element numbers from the mesh before it was derefined onto the mesh after it was derefined. This seems to work in serial but crashes on 2 procs.

**Comment by rw-anderson** [comment] 2021-08-21 04:33
I looked into this a little. It looks like it has something to do with this line:

```// this coarse element will get pruned, encode who owns it now
         index = -1 - elements[coarse[i]].rank;
```
where the index gets overloaded with a rank encoding, and then assigned as the parent field:

```
transforms.embeddings[i].parent = index;
```

But then later, this value gets used directly to index into an array in the GetCoarseToFineMap() routine, causing an array access error.

**Comment by rw-anderson** [comment] 2021-08-23 21:35
In looking at PR #2074, it looks like this use case was maybe never fully implemented. Also I guess the git blame erroneously shows @jakubcerveny as the author due to some cutting and pasting or refactoring. @kmittal2 or @v-dobrev do you possibly know more about this?

**Comment by kmittal2** [comment] 2021-08-24 01:09
It seems like the issue is that for [GetRefinementTransforms](https://github.com/mfem/mfem/blob/master/mesh/ncmesh.cpp#L4323), we properly set ```transforms.embeddings.SetSize(NElements);```. But we do not do is in [GetDerefinementTransforms](https://github.com/mfem/mfem/blob/master/mesh/ncmesh.cpp#L4365), which means that the size of ```transforms``` is `leaf_elements.Size()` and as a result it includes information for elements from the `ghost layer` and thus the ```index``` is negative.

**Comment by rw-anderson** [comment] 2021-08-24 04:58
Sounds right. Here's the case on 2 procs with 1 refinement on each processor:
![coarsen](https://user-images.githubusercontent.com/11507994/130546377-60d93a87-3653-498e-bd47-e5c758127a60.png)
The coarse_to_fine table is constructed successfully without the array access error, but looks like this:

proc 0:
```coarse to fine table
[row 0]
    0    1    2    3
[row 1]
    4
[row 2]
    5    8    7    6
[row 3]
    9
```

proc 1:
```
coarse to fine table
[row 0]
    0    1    2    3
[row 1]
    4
[row 2]
    5    8    7    6
[row 3]
    9
```
which is showing all the elements on both processors because it is including the ghost layer.

So I am not sure what the right solution is here. Does embeddings need the ghost layer elements in other contexts? If not, we could remove it. If it does, we could try to filter out the ghost elements when building the coarse fine map. But I am not sure how to do that either yet, since we don't have access to the ncmesh metadata since GetCoarseFineMap is a method on CoarseFineTransformations, not on ncmesh.

**Comment by kmittal2** [comment] 2021-08-24 17:15
Upon further investigation, it seems that if prior to derefinement `leaf_elements` contain `refined-ghost-elements`, and these ghost elements get derefined, their `element_type = 0` which means that they no longer exist (even though they are still vaild leaf elements on the processor that they were originally located on).
Since there is so much going on during refinement and derefinement, I have not been able to pin point how we could properly fix this. One way to address this might be to eliminate the rows from `CoarseFineTransformations.Embeddings` that have invalid elements in `GetCoarseToFineMap`. Maybe @v-dobrev or @jakubcerveny have better ideas.

**Comment by rw-anderson** [comment] 2021-08-24 17:21
I guess a first question is: would we ever want ghost elements to be supplied in this coarse_to_fine Table. I think the answer is no, it doesn't fit my use case, but maybe there was some other motivating use case for this code that I'm not aware of.

**Comment by kmittal2** [comment] 2021-08-24 17:29
Agreed. 
GetCoarseToFineMap was originally written with post-refinement scenario in mind, and was not really used post-derefinement until recently. We fixed one issue with #2074, and you have discovered another use one where it fails for derefinement.

**Comment by jakubcerveny** [comment] 2021-09-03 15:04
OK so after studying this problem (and my own code), I should probably provide a bit of background. 

The problem with derefinement is that it's a lot more tricky than refinement, especially in parallel: there are pathological cases where the ghost layer doesn't provide enough information to reconstruct the new (coarse) ghost layer correctly. These are cases that are called "complex derefinements" in the code and they happen already in 2D when the fine elements of some future coarse element are owned by three or more different ranks. The first child's rank (I think), that will end up owning the coarse element may not see enough ghost elements to build its new ghost layer. To avoid these cases, there always is a slight rebalance first in each parallel derefinement, where the complex cases are removed by migrating all fine childs to the owner of the future coarse element. This step creates a valid ghost layer, and all derefinements become "simple".

This shift in ownership sometimes has the side effect that some of the other ranks no longer see the coarse element, not even in their ghost layer. Even if the coarse element ends up just behind the second or third rank's ghost layer, nothing can be said of it, because it may no longer even be a real element: the regions beyond the ghost layer are pruned (derefined) as much as possible.

This is why `Embedding::parent` may be negative for some of the original fine elements, indicating that the fine element cannot be linked to any element in the new (coarse) mesh. (I'm not sure anymore if this can happen to any fine element or just ghost elements, but probably both).

So far it was sufficient to just skip these fine elements (try grepping the code for `parent < 0`). There *is* one case in `ParFiniteElementSpace::ParallelDerefinementMatrix` where it is necessary to at least determine on which rank is the new coarse element located. That's why `ParNCMesh::Derefine` sneaks in the rank number as `-1-rank`, in the `parent` member. The `parent` is still invalid though.

I think `CoarseFineTransformations::GetCoarseToFineMap` was originally not designed at all for derefinement. But hopefully it can be fixed by skipping fine elements with `parent < 0` too. (On a related note, I think the method should also be split into several methods because right now it seems to be doing quite a lot of stuff).

Finally, as for Bob's use case:
> I am trying to obtain a map of the element numbers from the mesh before it was derefined onto the mesh after it was derefined.

Do you have to use `GetCoarseToFineMap`? This seems doable with the original `CoarseFineTransformations` struct, where you just look directly at the `embeddings`. The `parent`, if nonnegative, is the coarse element number in the new mesh. The method `GetCoarseToFineMap` is a later, special-purpose addition to the struct.

**Comment by rw-anderson** [comment] 2021-09-03 20:17
Thanks for that background Jakub.

After a derefinement, the embeddings in the CoarseFineTransformations struct correspond to the "fine" elements, right, i.e., the elements before the derefinement? I do want the mapping in the other direction, and I think that's what GetCoarseFineMap() does: creates a table that inverts that mapping.

I think what we could do would be to skip the ghost elements on the fine mesh  while inverting the mapping. But it wasn't clear to me how to test if embeddings[i] corresponds to a ghost element from the context where this inversion happens.

I thought about adding a 'ghost' field to the embeddings structure and carrying that around, but that's a memory overhead that might not be worth it just for this use case.

**Comment by jakubcerveny** [comment] 2021-09-03 21:18
Oh, OK, I thought you needed the other direction. 

To only process non-ghosts, just take the first N `embeddings` where N is the number of regular elements in the fine mesh.

But as I said I'm not sure non-ghost are guaranteed to have a valid `parent`, I think this isn't the case because `ParallelDerefinementMatrix` is also checking that.

**Comment by rw-anderson** [comment] 2021-09-03 21:58
Unfortunately I don't think we have that information either without changing something. Although there's an argument named "fine_mesh" in GetCoarseToFineMap(), it's actually the coarser mesh when called after a derefinement. Probably we should change that argument name to "adapted_mesh" or something. Embeddings seems to be the structure that carries around information about the prior state of the mesh, but I don't think it contains that information.

**Comment by tzanio** [comment] 2021-09-19 01:54
Discussion continued in #2507.

**Closed by tzanio** 2021-09-19 01:54 UTC
Labels: question, amr, high-priority
