### ISSUE TITLE
Example 18 in 1D

### ISSUE THREAD

**Issue by L29430** [mfem/mfem#1606] opened 2020-07-06 14:36 UTC
Hi everyone,

I'm using Example 18: "DG Euler Equations" to help me solve my system of equations. I would like to start in one dimension but I'm having trouble. I have the impression that the problem comes from the .hpp file, first on the line 136 :
      -    A.Mult(x, z);

Can you help me understand why it doesn't work in 1D?

Regards,

Le

**Comment by jdahm** [comment] 2020-07-06 17:51
@L29430 Thanks for reporting this! I'll take a look at the example soon. In the meantime, could you tell us exactly what mesh you're using and what error you get?

**Comment by L29430** [comment] 2020-07-07 07:22
Hello @jdahm ! 

It's a simple mesh in 1D (segment) depending only on x, the error  indicated is : **Segmentation error (core dumped)**. 
If I comment the line 136 : **A.Mult(x, z);** in .hpp, the error does not appear, the problem could come from there?

**Comment by jdahm** [comment] 2020-07-09 06:36
@L29430, The problem is in calculating the face Jacobian on line 463 `Tr.Jacobian()`. In 1D, I suppose MFEM does not support this. You'll need a switch, which in a naive sense could simply be
```
     if (nor.Size() > 1) {
         CalcOrtho(Tr.Jacobian(), nor);
      } else {
         nor = 1;
      }
```

Other parts of the example will have to change as well, since code outside the integrators assumes the input mesh is periodic and 2D.

**Comment by rw-anderson** [comment] 2020-07-09 23:03
@v-dobrev @tzanio Is there an aspiration to support 1D as generally as possible?

**Comment by v-dobrev** [comment] 2020-07-10 02:49
For d-dimensional problem, `Tr.Jacobian()` is a `d x (d-1)` matrix, so it does not really make much sense in 1D.

This is one reason why, for DG face integrators, the (scaled) normal is computed using: https://github.com/mfem/mfem/blob/d81b3fa05acb049f5fdc89943666c19ec1c7f0fb/fem/bilininteg.cpp#L2743-L2750

@rw-anderson, what do you think is missing from the library regarding support for 1D meshes?

**Comment by rw-anderson** [comment] 2020-07-10 03:56
@v-dobrev I don't know that anything is missing, really. Most of the materials for MFEM say it is a "2D and 3D" library.   With very few exceptions a user can write dimension independent code that works in 2D and 3D without having to write special case clauses.  I was just wondering if it's a design principle that this should be true of 1D as well.

**Comment by tzanio** [comment] 2020-07-10 04:09
It's not a huge priority, but I think we should try to support 1D to the extent possible as one of our design principles.

**Comment by jdahm** [comment] 2020-07-10 19:01
@v-dobrev Thanks for the pointer!

> https://github.com/mfem/mfem/blob/d81b3fa05acb049f5fdc89943666c19ec1c7f0fb/fem/bilininteg.cpp#L2743-L2750

Shall we add this type of check to the example? My hope was that the integrators there would be general for any dimension, but the specific example uses meshes and ICs that are 2D-specific.

**Comment by v-dobrev** [comment] 2020-07-10 19:22
> Shall we add this type of check to the example? My hope was that the integrators there would be general for any dimension, but the specific example uses meshes and ICs that are 2D-specific.

Sounds good to me. Apart from the computation of the normal, is there anything else to do to make the integrators general?

**Comment by jdahm** [comment] 2020-07-13 16:08
It was at least my intention that the integrators work for any dimension. When I knew it wouldn't I put an assert, e.g. in the 2D ICs: https://github.com/mfem/mfem/blob/master/examples/ex18.hpp#L507

**Comment by tzanio** [comment] 2020-08-02 15:17
This issue hasn't been active for 3 weeks so I am closing it now.

Feel free to reopen (or open another issue) if there are outstanding questions or todos.

**Closed by tzanio** 2020-08-02 15:17 UTC
Labels: examples & miniapps, fem, question
