### ISSUE TITLE
Restart function in parallel version code in MFEM

### ISSUE THREAD

**Issue by diliu1994** [mfem/mfem#1628] opened 2020-07-16 22:32 UTC
Hi All,

I want to know if there is a function in MFEM which it can restart simulation. For example, when I run a simulation, I want to stop the simulation at a certain time, and then restart the simulation from that time point and continue to run the simulation. Could anyone help me?

Best regards,
Di

**Comment by tzanio** [comment] 2020-07-17 19:53
There is no dedicated "restart" function, but you can save the `Mesh` and `GridFunction`s when stopping a simulation, and then read them when "restarting".

The `DataCollection` class and its various sub-classes can be particularly useful for that.

Tzanio

**Comment by diliu1994** [comment] 2020-07-23 12:57
Hi All,

There is another problem. I can import the deformed mesh into the code, however, I don't know how to import the `GridFunction`s into the code. Could anyone help me with that.


Best Regards,
Di

**Comment by tzanio** [comment] 2020-07-26 01:02
Just use the `GridFunction(Mesh *m, std::istream &input)` constructor.

**Comment by diliu1994** [comment] 2020-07-27 16:56
Hi @tzanio,

I have tried the method and can successfully import the GridFunction into the code. However, the result I get from the restart method and the result I get from the code without restart is not the same. Could you please help me with how to restart for ex10p?

Best,
Di

**Comment by tzanio** [comment] 2020-07-28 20:38
In parallel you need to save and load the parallel mesh appropriately. See [this example](https://github.com/mfem/mfem/pull/1561/files#diff-acdeb0d83bfa7eabdf562ce5149e36fb).

**Comment by diliu1994** [comment] 2020-07-30 00:57
Hi @tzanio ,

I can export and import the parallel mesh. My question is the output result like the velocity and the elastic energy is not the same when I reload the deformed mesh and the gridfunctions in ex10p. Actually, in my opinion, in ex10p, the main coefficient that can affect the output result is the `BlockVector vx(true_offset)`, but for the `BlockVector` type, there is no function which can export and import it.

Best,
Di

**Comment by tzanio** [comment] 2020-07-30 01:01
For testing purposes, can you reproduce that in Example 1p and post the code?

**Comment by rw-anderson** [comment] 2020-07-30 17:08
> Actually, in my opinion, in ex10p, the main coefficient that can affect the output result is the `BlockVector vx(true_offset)`, but for the `BlockVector` type, there is no function which can export and import it.

Isn't the BlockVector derived from the gridfunction data? I think the typical way to handle this would be to save/restore the gridfunctions, then recreate the BlockVector object, much as the existing initialization works.  A typical restart strategy is rather than trying to save the state of each object, only save the fundamental data, and then rebuild/reinit the derived objects.

**Comment by tzanio** [comment] 2020-08-16 00:30
There hasn't been activity for more than 2 weeks on this issues, so I will close it now. Please feel free to reopen if you were not able to resolve it.

**Closed by tzanio** 2020-08-16 00:30 UTC
Labels: examples & miniapps, fem, mesh, usage

**Comment by vkorchagova** [comment] 2020-11-20 15:14
Good evening everyone,

I have one additional questions about the application restart in parallel mode: how to restart with the different number of procs? For example, when data were saved for the 4-procs simulation, could I restart with 2, or 8, or 12 procs?

**Comment by tzanio** [comment] 2020-11-20 16:42
Currently it is not possible to restart on a different number of processors, sorry.

**Comment by vkorchagova** [comment] 2020-11-25 14:52
@tzanio, thanks! Do you have some plans to make this option available in future?

**Comment by vkorchagova** [comment] 2020-11-25 15:00
One more question about BlockVector. How to update data in BlockVector correctly?

I have the following piece of code for the data reading from the VisItDataCollection:
```
Array<int> offsets(num_equation + 1);
for (int k = 0; k <= num_equation; k++) { offsets[k] = k * vfes.GetNDofs(); }
BlockVector u_block(offsets);
ParGridFunction sol(&vfes, u_block.GetData());
ParGridFunction *saved_sol = NULL;

if (restart)
{
   saved_sol = restart_dc.GetParField("restart_conservative_vars");
   if (!saved_sol)
   {
      if (myRank == 0)
      {
          cout << "The given data collection has no 'restart_conservative_vars' field."
                 << endl;
         exit(2);
      }
   }
   else
   {
      u_block.Update(*saved_sol,offsets);
   }
}
```
After that, I check data inside the u_block. When I use `u_block.Print(cout)` or `sol.Print(cout) ` I see only zeros. When I use `u_block.GetBlock(k).Print(cout)`, I see the correct values inside each block.

What could be a problem?

**Comment by v-dobrev** [comment] 2020-11-25 23:59
The reason `u_block.Print(cout)` does not work is that there is a bug in the implementation of `BlockVector::Update(Vector & data, const Array<int> & bOffsets)` -- the data for the big vector is not actually updated. We will need to fix that, thanks for finding the bug!

Here is what the fix should look like:
```diff
diff --git a/linalg/blockvector.cpp b/linalg/blockvector.cpp
index 01b9fa3c3..1bd4961dc 100644
--- a/linalg/blockvector.cpp
+++ b/linalg/blockvector.cpp
@@ -101,6 +101,7 @@ void BlockVector::Update(Vector & data, const Array<int> & bOffsets)
    {
       blocks[i].MakeRef(data, blockOffsets[i], BlockSize(i));
    }
+   MakeRef(data, 0, blockOffsets[numBlocks]);
 }
 
 void BlockVector::Update(const Array<int> &bOffsets)
```

The reason `sol.Print(cout)` does not work is that it still points to the original data of `u_block`. After you update `u_block`, you should also call `sol.MakeRef(&vfes, u_block, 0)`. For this to work, you need the fix for the above bug too.
