### ISSUE TITLE
Question about accumulate_dofs 

### ISSUE THREAD

**Issue by tuckerbabcock** [mfem/mfem#1496] opened 2020-05-20 22:26 UTC
Hi all,

I'm working on differentiating parts of the MFEM code with respect to the mesh coordinates, which has led me to differentiating `GridFunction::ProjectBdrCoefficientTangent`, which calls `GridFunction::AccumulateAndCountBdrTangentValues`, which in turn calls `accumulate_dofs`: 
https://github.com/mfem/mfem/blob/4fc13517f5e8d91ec9c6b0c0d12d4daafb18e316/fem/gridfunc.cpp#L1858-L1875

I have a few questions about what this function does. 

1) I'm wondering about the code between lines 1866 to 1873. By the looks of it, the if/else block could be replaced with just `gf(k) += val`, assuming the `GridFunction` was initialized to a vector full of to zeros, is that right? 
2) For the check on line 1865, what causes `k` to be negative? Based on a little searching it seems like it will be negative if the orientation of the element is incorrect. If that is true, how often is that the case?

Thanks as always,

Tucker

**Comment by jakubcerveny** [comment] 2020-05-21 08:55
1. I suspect the intent was to prevent access to the complete vector (O(N)) when only the boundary often needs updating (O(N^{2/3})?). But then `values_counter` has to be zeroed completely anyway, so I'm not sure.

2. In H(curl) and H(div), negative DOF is a (somewhat hacky) way to encode the need to flip the sign of the solution or shape function value on some interfaces. This happens often in those spaces.

**Comment by tuckerbabcock** [comment] 2020-05-21 17:23
Hi @jakubcerveny,
I think you're right for the first point. It looks like values counter is needed to compute the averages of the projected values in `GridFunction::ProjectBdrCoefficientTangent`, so I suspect that's why it needs to be the full size of the grid function. Regarding the second point, thank you, I'll have to think about how that affects differentiation.

**Comment by tzanio** [comment] 2020-05-25 16:49
I believe @v-dobrev wrote this code, so maybe he can provide additional details.

**Comment by v-dobrev** [comment] 2020-05-28 19:48
Regarding 1: the reason is not so much about the complexity as with the intended behavior -- we don't want to modify any dofs that are not boundary. This is useful in various scenarios, like AMR, where you have an initial guess for the solution but the boundary values need to be updated to be exact according to boundary conditions.

**Comment by tuckerbabcock** [comment] 2020-05-29 19:59
Thanks @jakubcerveny, @tzanio, and @v-dobrev. I've got a related question about `ParGridFunction::ProjectBdrCoefficientTangent`, specifically the comment on line 465: https://github.com/mfem/mfem/blob/4fc13517f5e8d91ec9c6b0c0d12d4daafb18e316/fem/pgridfunc.cpp#L448-L472
Can one of you explain what this really means, as well as what the reduction operations are doing? I expect the reductions are summing the contributions for the dofs that lie on a part boundary, but I have not spent a ton of time digging into the `GroupCommunicator` or `GroupTopology` objects, so I'd love to confirm that.

Thanks,

Tucker

**Comment by v-dobrev** [comment] 2020-05-29 23:36
In a `ParGridFunction` (aka L-vector) the dofs on processor boundaries (aka the shared dofs) have copies on each neighboring processor. The `GroupCommunicator` performs operations with these different copies of the dofs. For example, `Reduce` will perform a reduction like summation of those (generally different) values from different processors. The result of the reduction will be available only on one of the processors -- the master for that group of processors. This is what the comment on line 465 points out -- only the master processor will have the actual sum, the rest will have just their local value. If necessary, we can have the masters send their values to all other processors that share the dof -- this is what the method `GroupCommunicator::Bcast` does.

**Comment by tzanio** [comment] 2020-06-12 19:40
Hi @tuckerbabcock, I'm closing this for now, but please feel free to reopen if you have additional questions.

**Closed by tzanio** 2020-06-12 19:40 UTC
Labels: fem, question
