### ISSUE TITLE
Bug in HypreParMatrixFromBlocks

### ISSUE THREAD

**Issue by chikitkin** [mfem/mfem#3915] opened 2023-10-06 05:41 UTC
Hi, all!

I prepared an example to reproduce a bug in `HypreParMatrixFromBlocks`, to be more precise, it occurs inside Hypre lib. 

For me, it fails with `mpirun -n NP  reproduce_hypre_from_blocks_bug.exe` for NP > 1 both in MFEM 4.3 and MFEM 4.5.2 with the following message:

![image](https://github.com/mfem/mfem/assets/7203771/198fc79c-3401-403f-b70e-5a1bd93c4070)
 
I discovered that error occurs in `hypre_DataExchangeList` function in HYPRE lib, because 
`         hypre_MPI_Irecv(response_ptrs[i], max_response_total_bytes,
                         hypre_MPI_BYTE, contact_proc_list[i],
                         response_tag, comm, &response_requests[i]);`

is called with rank `contact_proc_list[i]` equal to N of MPI ranks, while maximum rank is N-1. But I have no idea why it happens :)

[reproduce_bug.zip](https://github.com/mfem/mfem/files/12746656/reproduce_bug.zip)

**Comment by tzanio** [comment] 2023-10-24 16:56
Duplicate of #3893

**Closed by tzanio** 2023-10-24 16:56 UTC
