### ISSUE TITLE
GMSH Support

### ISSUE THREAD

**Issue by goinea** [mfem/mfem#2216] opened 2021-05-03 19:46 UTC
Uploaded a gmsh file(.msh) and got the following error:
MFEM abort: Gmsh file : vertices indices are not unique
 ... in function: void mfem::Mesh::ReadGmshMesh(std::istream&, int&, int&)
 ... in file: mesh/mesh_readers.cpp:1551

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.

Is there already an mfem periodic tet mesh for a cube?

**Comment by v-dobrev** [comment] 2021-05-04 02:08
Maybe you can load the periodic hex mesh for the unit cube, `data/periodic-cube.mesh` and then convert it tet mesh with `Mesh::MakeSimplicial`. However, I'm not 100% sure periodic meshes are supported by `Mesh::MakeSimplicial` -- @pazner will know for sure.

**Comment by pazner** [comment] 2021-05-04 02:27
I suspect it won't work, since periodic meshes rely on the L2 nodes, and nodes are not really supported by `Mesh::MakeSimplicial`.

Perhaps a better solution could be to create a Cartesian tet mesh:
```c++
Mesh mesh = Mesh::MakeCartesian3D(10, 10, 10, Element::TETRAHEDRON);
```
and then make it periodic using the function `MakePeriodicMesh` found [here](https://github.com/mfem/mfem/blob/821689c16009055a61e8e4af6519cb0ff3290b8f/miniapps/common/bravais.cpp#L9048):
```c++
std::vector<Vector> translation_vectors = {Vector({1,0,0}),Vector({0,1,0}),Vector({0,0,1})};
Mesh *periodic_mesh = MakePeriodicMesh(&mesh, translation_vectors, 0);
```

**Comment by pazner** [comment] 2021-05-05 15:28
By the way @goinea, what version of the gmsh mesh format are you trying to read (this will be listed on the second line of the `.msh` file, in between `$MeshFormat` and `$EndMeshFormat`)?

Sometimes the error you are seeing can be caused by trying to load a gmsh v4 mesh. MFEM supports reading gmsh v2.2 meshes, which can be controlled in your `.geo` file with `Mesh.MshFileVersion = 2.2;`.

**Comment by goinea** [comment] 2021-05-05 15:31
It is version 2.2, I checked that.

**Comment by goinea** [comment] 2021-05-05 15:32
Thanks

**Comment by pazner** [comment] 2021-05-05 16:04
Ok, so the error is caused by something else then. Perhaps it is an issue with how we handle periodic gmsh meshes. It will be hard to say without the msh and geo files.

**Comment by goinea** [comment] 2021-05-05 22:58
@pazner  I'll attach the code for GEO and gmesh: I edited the gmesh example 18 to exclude the sphere
 `// -----------------------------------------------------------------------------
//
//  Gmsh GEO tutorial 18
//
//  Periodic meshes
//
// -----------------------------------------------------------------------------

// Periodic meshing constraints can be imposed on surfaces and curves.

// Let's use the OpenCASCADE geometry kernel to build two geometries.

SetFactory("OpenCASCADE");

// The first geometry is very simple: a unit cube with a non-uniform mesh size
// constraint (set on purpose to be able to verify visually that the periodicity
// constraint works!):

Box(1) = {0, 0, 0, 1, 1, 1};
MeshSize {:} = 0.33333;
//MeshSize {1} = 0.02;

// To impose that the mesh on surface 2 (the right side of the cube) should
// match the mesh from surface 1 (the left side), the following periodicity
// constraint is set:
Periodic Surface {2} = {1} Translate {1, 0, 0};

// During mesh generation, the mesh on surface 2 will be created by copying the
// mesh from surface 1.  Periodicity constraints can be specified with a
// `Translation', a `Rotation' or a general `Affine' transform.

// Multiple periodicities can be imposed in the same way:
Periodic Surface {6} = {5} Translate {0, 0, 1};
Periodic Surface {4} = {3} Translate {0, 1, 0};

// For more complicated cases, finding the corresponding surfaces by hand can be
// tedious, especially when geometries are created through solid
// modelling. Let's construct a slightly more complicated geometry.

// We start with a cube and some spheres:
//Box(10) = {2, 0, 0, 1, 1, 1};
//x = 2-0.3; y = 0; z = 0;
//Sphere(11) = {x, y, z, 0.35};
//Sphere(12) = {x+1, y, z, 0.35};
//Sphere(13) = {x, y+1, z, 0.35};
//Sphere(14) = {x, y, z+1, 0.35};
//Sphere(15) = {x+1, y+1, z, 0.35};
//Sphere(16) = {x, y+1, z+1, 0.35};
//Sphere(17) = {x+1, y, z+1, 0.35};
//Sphere(18) = {x+1, y+1, z+1, 0.35};

// We first fragment all the volumes, which will leave parts of spheres
// protruding outside the cube:
//v() = BooleanFragments { Volume{10}; Delete; }{ Volume{11:18}; Delete; };

// Ask OpenCASCADE to compute more accurate bounding boxes of entities using the
 //STL mesh:
//Geometry.OCCBoundsUseStl = 1;

// We then retrieve all the volumes in the bounding box of the original cube,
// and delete all the parts outside it:
//eps = 1e-3;
//vin() = Volume In BoundingBox {2-eps,-eps,-eps, 2+1+eps,1+eps,1+eps};
//v() -= vin();
//Recursive Delete{ Volume{v()}; }

// We now set a non-uniform mesh size constraint (again to check results
// visually):
//MeshSize { PointsOf{ Volume{vin()}; }} = 0.1;
//p() = Point In BoundingBox{2-eps, -eps, -eps, 2+eps, eps, eps};
//MeshSize {p()} = 0.001;

// We now identify corresponding surfaces on the left and right sides of the
// geometry automatically.

// First we get all surfaces on the left:
//Sxmin() = Surface In BoundingBox{2-eps, -eps, -eps, 2+eps, 1+eps, 1+eps};

//For i In {0:#Sxmin()-1}
  // Then we get the bounding box of each left surface
  //bb() = BoundingBox Surface { Sxmin(i) };
  // We translate the bounding box to the right and look for surfaces inside it:
  //Sxmax() = Surface In BoundingBox { bb(0)-eps+1, bb(1)-eps, bb(2)-eps,
                                  // bb(3)+eps+1, bb(4)+eps, bb(5)+eps };
  // For all the matches, we compare the corresponding bounding boxes...
  //For j In {0:#Sxmax()-1}
  //bb2() = BoundingBox Surface { Sxmax(j) };
    //bb2(0) -= 1;
    //bb2(3) -= 1;
    // ...and if they match, we apply the periodicity constraint
    //If(Fabs(bb2(0)-bb(0)) < eps && Fabs(bb2(1)-bb(1)) < eps &&
      // Fabs(bb2(2)-bb(2)) < eps && Fabs(bb2(3)-bb(3)) < eps &&
      //Fabs(bb2(4)-bb(4)) < eps && Fabs(bb2(5)-bb(5)) < eps)
      //Periodic Surface {Sxmax(j)} = {Sxmin(i)} Translate {1,0,0};
    //EndIf
  //EndFor
//EndFor
`
Attached below is the gmsh mesh
`$MeshFormat
2.2 0 8
$EndMeshFormat
$Nodes
81
1 0 0 1
2 0 0 0
3 0 1 1
4 0 1 0
5 1 0 1
6 1 0 0
7 1 1 1
8 1 1 0
9 0 0 0.3333333333333333
10 0 0 0.6666666666666666
11 0 0.3333333333333333 1
12 0 0.6666666666666666 1
13 0 1 0.3333333333333333
14 0 1 0.6666666666666666
15 0 0.3333333333333333 0
16 0 0.6666666666666666 0
17 1 0 0.3333333333333333
18 1 0 0.6666666666666666
19 1 0.3333333333333333 1
20 1 0.6666666666666666 1
21 1 1 0.3333333333333333
22 1 1 0.6666666666666666
23 1 0.3333333333333333 0
24 1 0.6666666666666666 0
25 0.3333333333333333 0 0
26 0.6666666666666666 0 0
27 0.3333333333333333 0 1
28 0.6666666666666666 0 1
29 0.3333333333333333 1 0
30 0.6666666666666666 1 0
31 0.3333333333333333 1 1
32 0.6666666666666666 1 1
33 0 0.5 0.295191706296517
34 0 0.5 0.7050506247151784
35 0 0.2474399182838952 0.5000403885019492
36 0 0.7525600817161049 0.5000403885019492
37 0 0.7576802451483147 0.7576802451483147
38 0 0.2423197548516856 0.2423197548516855
39 0 0.2423197548516855 0.7576802451483146
40 0 0.7576802451483144 0.2423197548516854
41 1 0.5 0.295191706296517
42 1 0.5 0.7050506247151784
43 1 0.2474399182838952 0.5000403885019492
44 1 0.7525600817161049 0.5000403885019492
45 1 0.7576802451483147 0.7576802451483147
46 1 0.2423197548516856 0.2423197548516855
47 1 0.2423197548516855 0.7576802451483146
48 1 0.7576802451483144 0.2423197548516854
49 0.295191706296517 0 0.5
50 0.7050506247151784 0 0.5
51 0.5000403885019492 0 0.2474399182838952
52 0.5000403885019492 0 0.7525600817161049
53 0.7576802451483147 0 0.7576802451483147
54 0.2423197548516855 0 0.2423197548516856
55 0.2423197548516854 0 0.7576802451483144
56 0.7576802451483146 0 0.2423197548516855
57 0.295191706296517 1 0.5
58 0.7050506247151784 1 0.5
59 0.5000403885019492 1 0.2474399182838952
60 0.5000403885019492 1 0.7525600817161049
61 0.7576802451483147 1 0.7576802451483147
62 0.2423197548516855 1 0.2423197548516856
63 0.2423197548516854 1 0.7576802451483144
64 0.7576802451483146 1 0.2423197548516855
65 0.5 0.295191706296517 0
66 0.5 0.7050506247151784 0
67 0.2474399182838952 0.5000403885019492 0
68 0.7525600817161049 0.5000403885019492 0
69 0.7576802451483147 0.7576802451483147 0
70 0.2423197548516856 0.2423197548516855 0
71 0.2423197548516855 0.7576802451483146 0
72 0.7576802451483144 0.2423197548516854 0
73 0.5 0.295191706296517 1
74 0.5 0.7050506247151784 1
75 0.2474399182838952 0.5000403885019492 1
76 0.7525600817161049 0.5000403885019492 1
77 0.7576802451483147 0.7576802451483147 1
78 0.2423197548516856 0.2423197548516855 1
79 0.2423197548516855 0.7576802451483146 1
80 0.7576802451483144 0.2423197548516854 1
81 0.4999999999999999 0.5000000000000001 0.5
$EndNodes
$Elements
384
1 15 2 0 1 1
2 15 2 0 2 2
3 15 2 0 3 3
4 15 2 0 4 4
5 15 2 0 5 5
6 15 2 0 6 6
7 15 2 0 7 7
8 15 2 0 8 8
9 1 2 0 1 2 9
10 1 2 0 1 9 10
11 1 2 0 1 10 1
12 1 2 0 2 1 11
13 1 2 0 2 11 12
14 1 2 0 2 12 3
15 1 2 0 3 4 13
16 1 2 0 3 13 14
17 1 2 0 3 14 3
18 1 2 0 4 2 15
19 1 2 0 4 15 16
20 1 2 0 4 16 4
21 1 2 0 5 6 17
22 1 2 0 5 17 18
23 1 2 0 5 18 5
24 1 2 0 6 5 19
25 1 2 0 6 19 20
26 1 2 0 6 20 7
27 1 2 0 7 8 21
28 1 2 0 7 21 22
29 1 2 0 7 22 7
30 1 2 0 8 6 23
31 1 2 0 8 23 24
32 1 2 0 8 24 8
33 1 2 0 9 2 25
34 1 2 0 9 25 26
35 1 2 0 9 26 6
36 1 2 0 10 1 27
37 1 2 0 10 27 28
38 1 2 0 10 28 5
39 1 2 0 11 4 29
40 1 2 0 11 29 30
41 1 2 0 11 30 8
42 1 2 0 12 3 31
43 1 2 0 12 31 32
44 1 2 0 12 32 7
45 2 2 0 1 10 1 39
46 2 2 0 1 1 11 39
47 2 2 0 1 2 9 38
48 2 2 0 1 15 2 38
49 2 2 0 1 12 3 37
50 2 2 0 1 3 14 37
51 2 2 0 1 13 4 40
52 2 2 0 1 4 16 40
53 2 2 0 1 9 10 35
54 2 2 0 1 9 35 38
55 2 2 0 1 35 10 39
56 2 2 0 1 11 12 34
57 2 2 0 1 11 34 39
58 2 2 0 1 34 12 37
59 2 2 0 1 14 13 36
60 2 2 0 1 36 13 40
61 2 2 0 1 14 36 37
62 2 2 0 1 16 15 33
63 2 2 0 1 33 15 38
64 2 2 0 1 16 33 40
65 2 2 0 1 34 33 35
66 2 2 0 1 33 34 36
67 2 2 0 1 35 33 38
68 2 2 0 1 33 36 40
69 2 2 0 1 34 35 39
70 2 2 0 1 36 34 37
71 2 2 0 2 18 5 47
72 2 2 0 2 5 19 47
73 2 2 0 2 6 17 46
74 2 2 0 2 23 6 46
75 2 2 0 2 20 7 45
76 2 2 0 2 7 22 45
77 2 2 0 2 21 8 48
78 2 2 0 2 8 24 48
79 2 2 0 2 17 18 43
80 2 2 0 2 17 43 46
81 2 2 0 2 43 18 47
82 2 2 0 2 19 20 42
83 2 2 0 2 19 42 47
84 2 2 0 2 42 20 45
85 2 2 0 2 22 21 44
86 2 2 0 2 44 21 48
87 2 2 0 2 22 44 45
88 2 2 0 2 24 23 41
89 2 2 0 2 41 23 46
90 2 2 0 2 24 41 48
91 2 2 0 2 42 41 43
92 2 2 0 2 41 42 44
93 2 2 0 2 43 41 46
94 2 2 0 2 41 44 48
95 2 2 0 2 42 43 47
96 2 2 0 2 44 42 45
97 2 2 0 3 1 10 55
98 2 2 0 3 27 1 55
99 2 2 0 3 9 2 54
100 2 2 0 3 2 25 54
101 2 2 0 3 18 5 53
102 2 2 0 3 5 28 53
103 2 2 0 3 6 17 56
104 2 2 0 3 26 6 56
105 2 2 0 3 10 9 49
106 2 2 0 3 49 9 54
107 2 2 0 3 10 49 55
108 2 2 0 3 17 18 50
109 2 2 0 3 17 50 56
110 2 2 0 3 50 18 53
111 2 2 0 3 25 26 51
112 2 2 0 3 25 51 54
113 2 2 0 3 51 26 56
114 2 2 0 3 28 27 52
115 2 2 0 3 52 27 55
116 2 2 0 3 28 52 53
117 2 2 0 3 50 49 51
118 2 2 0 3 49 50 52
119 2 2 0 3 51 49 54
120 2 2 0 3 49 52 55
121 2 2 0 3 50 51 56
122 2 2 0 3 52 50 53
123 2 2 0 4 3 14 63
124 2 2 0 4 31 3 63
125 2 2 0 4 13 4 62
126 2 2 0 4 4 29 62
127 2 2 0 4 22 7 61
128 2 2 0 4 7 32 61
129 2 2 0 4 8 21 64
130 2 2 0 4 30 8 64
131 2 2 0 4 14 13 57
132 2 2 0 4 57 13 62
133 2 2 0 4 14 57 63
134 2 2 0 4 21 22 58
135 2 2 0 4 21 58 64
136 2 2 0 4 58 22 61
137 2 2 0 4 29 30 59
138 2 2 0 4 29 59 62
139 2 2 0 4 59 30 64
140 2 2 0 4 32 31 60
141 2 2 0 4 60 31 63
142 2 2 0 4 32 60 61
143 2 2 0 4 58 57 59
144 2 2 0 4 57 58 60
145 2 2 0 4 59 57 62
146 2 2 0 4 57 60 63
147 2 2 0 4 58 59 64
148 2 2 0 4 60 58 61
149 2 2 0 5 2 15 70
150 2 2 0 5 25 2 70
151 2 2 0 5 16 4 71
152 2 2 0 5 4 29 71
153 2 2 0 5 23 6 72
154 2 2 0 5 6 26 72
155 2 2 0 5 8 24 69
156 2 2 0 5 30 8 69
157 2 2 0 5 15 16 67
158 2 2 0 5 15 67 70
159 2 2 0 5 67 16 71
160 2 2 0 5 24 23 68
161 2 2 0 5 68 23 72
162 2 2 0 5 24 68 69
163 2 2 0 5 26 25 65
164 2 2 0 5 65 25 70
165 2 2 0 5 26 65 72
166 2 2 0 5 29 30 66
167 2 2 0 5 29 66 71
168 2 2 0 5 66 30 69
169 2 2 0 5 66 65 67
170 2 2 0 5 65 66 68
171 2 2 0 5 67 65 70
172 2 2 0 5 65 68 72
173 2 2 0 5 66 67 71
174 2 2 0 5 68 66 69
175 2 2 0 6 1 11 78
176 2 2 0 6 27 1 78
177 2 2 0 6 12 3 79
178 2 2 0 6 3 31 79
179 2 2 0 6 19 5 80
180 2 2 0 6 5 28 80
181 2 2 0 6 7 20 77
182 2 2 0 6 32 7 77
183 2 2 0 6 11 12 75
184 2 2 0 6 11 75 78
185 2 2 0 6 75 12 79
186 2 2 0 6 20 19 76
187 2 2 0 6 76 19 80
188 2 2 0 6 20 76 77
189 2 2 0 6 28 27 73
190 2 2 0 6 73 27 78
191 2 2 0 6 28 73 80
192 2 2 0 6 31 32 74
193 2 2 0 6 31 74 79
194 2 2 0 6 74 32 77
195 2 2 0 6 74 73 75
196 2 2 0 6 73 74 76
197 2 2 0 6 75 73 78
198 2 2 0 6 73 76 80
199 2 2 0 6 74 75 79
200 2 2 0 6 76 74 77
201 4 2 0 1 61 45 77 81
202 4 2 0 1 63 79 37 81
203 4 2 0 1 46 72 56 81
204 4 2 0 1 53 80 47 81
205 4 2 0 1 69 48 64 81
206 4 2 0 1 70 38 54 81
207 4 2 0 1 78 55 39 81
208 4 2 0 1 62 40 71 81
209 4 2 0 1 68 41 69 81
210 4 2 0 1 39 49 35 81
211 4 2 0 1 37 36 57 81
212 4 2 0 1 76 77 42 81
213 4 2 0 1 45 58 44 81
214 4 2 0 1 61 74 60 81
215 4 2 0 1 79 75 34 81
216 4 2 0 1 68 72 41 81
217 4 2 0 1 35 49 38 81
218 4 2 0 1 76 42 80 81
219 4 2 0 1 44 58 48 81
220 4 2 0 1 43 46 50 81
221 4 2 0 1 34 75 78 81
222 4 2 0 1 49 39 55 81
223 4 2 0 1 46 41 72 81
224 4 2 0 1 69 41 48 81
225 4 2 0 1 38 49 54 81
226 4 2 0 1 57 63 37 81
227 4 2 0 1 77 74 61 81
228 4 2 0 1 61 58 45 81
229 4 2 0 1 45 42 77 81
230 4 2 0 1 58 64 48 81
231 4 2 0 1 79 34 37 81
232 4 2 0 1 56 50 46 81
233 4 2 0 1 80 42 47 81
234 4 2 0 1 34 78 39 81
235 4 2 0 1 68 65 72 81
236 4 2 0 1 76 80 73 81
237 4 2 0 1 44 48 41 81
238 4 2 0 1 55 52 49 81
239 4 2 0 1 57 60 63 81
240 4 2 0 1 49 51 54 81
241 4 2 0 1 67 70 65 81
242 4 2 0 1 41 46 43 81
243 4 2 0 1 35 38 33 81
244 4 2 0 1 40 36 33 81
245 4 2 0 1 75 73 78 81
246 4 2 0 1 62 59 57 81
247 4 2 0 1 50 52 53 81
248 4 2 0 1 42 45 44 81
249 4 2 0 1 51 50 56 81
250 4 2 0 1 47 42 43 81
251 4 2 0 1 58 59 64 81
252 4 2 0 1 61 60 58 81
253 4 2 0 1 68 69 66 81
254 4 2 0 1 37 34 36 81
255 4 2 0 1 76 74 77 81
256 4 2 0 1 39 35 34 81
257 4 2 0 1 66 71 67 81
258 4 2 0 1 79 74 75 81
259 4 2 0 1 44 41 42 81
260 4 2 0 1 49 52 50 81
261 4 2 0 1 42 41 43 81
262 4 2 0 1 50 51 49 81
263 4 2 0 1 66 65 68 81
264 4 2 0 1 67 65 66 81
265 4 2 0 1 60 57 58 81
266 4 2 0 1 74 76 73 81
267 4 2 0 1 73 75 74 81
268 4 2 0 1 34 35 33 81
269 4 2 0 1 33 36 34 81
270 4 2 0 1 58 57 59 81
271 4 2 0 1 31 79 63 60
272 4 2 0 1 62 71 29 59
273 4 2 0 1 43 18 47 53
274 4 2 0 1 64 69 59 30
275 4 2 0 1 38 70 15 67
276 4 2 0 1 70 54 25 51
277 4 2 0 1 27 55 78 52
278 4 2 0 1 40 62 13 36
279 4 2 0 1 52 28 53 80
280 4 2 0 1 16 67 71 40
281 4 2 0 1 26 51 56 72
282 4 2 0 1 79 31 74 60
283 4 2 0 1 66 29 71 59
284 4 2 0 1 73 27 78 52
285 4 2 0 1 57 13 62 36
286 4 2 0 1 65 70 25 51
287 4 2 0 1 15 33 38 67
288 4 2 0 1 59 69 66 30
289 4 2 0 1 18 43 50 53
290 4 2 0 1 67 16 33 40
291 4 2 0 1 28 52 73 80
292 4 2 0 1 51 26 65 72
293 4 2 0 1 40 71 4 62
294 4 2 0 1 38 2 70 54
295 4 2 0 1 37 63 3 79
296 4 2 0 1 55 1 78 39
297 4 2 0 1 5 47 53 80
298 4 2 0 1 45 77 7 61
299 4 2 0 1 48 64 8 69
300 4 2 0 1 6 56 46 72
301 4 2 0 1 35 10 9 49
302 4 2 0 1 36 57 13 14
303 4 2 0 1 52 73 27 28
304 4 2 0 1 26 65 25 51
305 4 2 0 1 33 15 16 67
306 4 2 0 1 23 24 68 41
307 4 2 0 1 11 12 75 34
308 4 2 0 1 66 29 59 30
309 4 2 0 1 22 44 58 21
310 4 2 0 1 76 20 19 42
311 4 2 0 1 32 74 31 60
312 4 2 0 1 50 43 18 17
313 4 2 0 1 47 18 5 53
314 4 2 0 1 69 64 8 30
315 4 2 0 1 3 37 79 12
316 4 2 0 1 78 1 11 39
317 4 2 0 1 71 29 4 62
318 4 2 0 1 79 63 3 31
319 4 2 0 1 80 5 47 19
320 4 2 0 1 77 7 20 45
321 4 2 0 1 64 8 21 48
322 4 2 0 1 61 7 45 22
323 4 2 0 1 56 17 6 46
324 4 2 0 1 32 7 77 61
325 4 2 0 1 71 4 16 40
326 4 2 0 1 9 2 38 54
327 4 2 0 1 53 28 5 80
328 4 2 0 1 8 48 69 24
329 4 2 0 1 62 4 40 13
330 4 2 0 1 38 70 2 15
331 4 2 0 1 2 70 54 25
332 4 2 0 1 63 3 14 37
333 4 2 0 1 10 1 55 39
334 4 2 0 1 55 78 1 27
335 4 2 0 1 46 23 6 72
336 4 2 0 1 6 26 56 72
337 4 2 0 1 80 52 81 53
338 4 2 0 1 80 81 52 73
339 4 2 0 1 69 41 24 48
340 4 2 0 1 24 41 69 68
341 4 2 0 1 37 57 14 63
342 4 2 0 1 37 14 57 36
343 4 2 0 1 67 40 81 71
344 4 2 0 1 81 40 67 33
345 4 2 0 1 39 49 10 35
346 4 2 0 1 10 49 39 55
347 4 2 0 1 51 72 81 56
348 4 2 0 1 81 72 51 65
349 4 2 0 1 74 61 32 77
350 4 2 0 1 32 61 74 60
351 4 2 0 1 58 45 22 61
352 4 2 0 1 58 22 45 44
353 4 2 0 1 42 77 20 45
354 4 2 0 1 42 20 77 76
355 4 2 0 1 53 43 81 47
356 4 2 0 1 53 81 43 50
357 4 2 0 1 59 69 81 66
358 4 2 0 1 59 81 69 64
359 4 2 0 1 79 34 12 37
360 4 2 0 1 12 34 79 75
361 4 2 0 1 70 51 81 54
362 4 2 0 1 81 51 70 65
363 4 2 0 1 36 62 81 40
364 4 2 0 1 36 81 62 57
365 4 2 0 1 78 52 81 73
366 4 2 0 1 81 52 78 55
367 4 2 0 1 38 67 81 70
368 4 2 0 1 81 67 38 33
369 4 2 0 1 38 49 9 54
370 4 2 0 1 9 49 38 35
371 4 2 0 1 72 41 23 68
372 4 2 0 1 72 23 41 46
373 4 2 0 1 58 48 21 44
374 4 2 0 1 21 48 58 64
375 4 2 0 1 60 79 81 74
376 4 2 0 1 60 81 79 63
377 4 2 0 1 50 46 17 56
378 4 2 0 1 17 46 50 43
379 4 2 0 1 59 71 81 62
380 4 2 0 1 59 81 71 66
381 4 2 0 1 80 42 19 47
382 4 2 0 1 19 42 80 76
383 4 2 0 1 34 78 11 39
384 4 2 0 1 34 11 78 75
$EndElements
$Periodic
19
0 1 2
Affine 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1
1
1 2
0 3 1
Affine 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 1
1
3 1
0 4 2
Affine 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 1
1
4 2
0 5 6
Affine 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1
1
5 6
0 6 2
Affine 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1
1
6 2
0 7 5
Affine 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 1
1
7 5
0 8 6
Affine 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 1
1
8 6
1 2 4
Affine 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1
4
12 16
11 15
3 4
1 2
1 3 1
Affine 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 1
4
14 10
13 9
4 2
3 1
1 5 1
Affine 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1
4
17 9
18 10
5 1
6 2
1 6 8
Affine 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1
4
19 23
20 24
7 8
5 6
1 7 5
Affine 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 1
4
21 17
22 18
7 5
8 6
1 8 4
Affine 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1
4
24 16
23 15
8 4
6 2
1 10 9
Affine 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1
4
28 26
27 25
5 6
1 2
1 11 9
Affine 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 1
4
30 26
29 25
8 6
4 2
1 12 10
Affine 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 1
4
31 27
32 28
7 5
3 1
2 2 1
Affine 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1
20
19 11
21 13
47 39
24 16
44 36
17 9
22 14
20 12
42 34
48 40
41 33
43 35
46 38
18 10
23 15
45 37
7 3
8 4
5 1
6 2
2 4 3
Affine 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 1
20
14 10
13 9
31 27
21 17
30 26
61 53
59 51
29 25
22 18
32 28
57 49
58 50
60 52
63 55
62 54
64 56
7 5
8 6
4 2
3 1
2 6 5
Affine 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1
20
31 29
19 23
28 26
12 16
11 15
20 24
27 25
32 30
79 71
73 65
76 68
78 70
80 72
77 69
74 66
75 67
7 8
5 6
3 4
1 2
$EndPeriodic`

**Comment by pazner** [comment] 2021-05-06 16:48
I have confirmed that this is a bug, I will look into what it would take to fix this.

In the mean time, if you need a periodic Cartesian tet mesh, you can try the method in [this comment](https://github.com/mfem/mfem/issues/2216#issuecomment-831649011).

**Comment by goinea** [comment] 2021-05-07 02:35
Okay, thanks. Will do. Please let me know if this bug gets fixed.

**Comment by goinea** [comment] 2021-05-07 13:15
Just curious @pazner  is this a bug in gmesh or mfem? Also, is Bravis.cpp/.hpp a part of the main branch of mfem?

**Comment by pazner** [comment] 2021-05-07 16:31
> Just curious @pazner is this a bug in gmesh or mfem? Also, is Bravis.cpp/.hpp a part of the main branch of mfem?

It's a bug in MFEM. It used to be working as recently as in #1938, I believe.

Bravais is not part of the main branch of MFEM. I made a PR with the same functionality here: #2230.

**Comment by goinea** [comment] 2021-05-11 13:12
Thanks @tzanio @pazner . Concerning current implementation, can I just copy and paste the whole periodic function into my code to use it or just upload the cpp and hpp files to my directory and include them without having licensing errors?Or, would I need to just wait for the pull request to be satisfied? I want to use it but also make sure my citations are appropriate.

**Comment by pazner** [comment] 2021-05-11 14:30
I think the easiest option would be to check out the PR branch (`git pull && git checkout make-periodic-mesh` from within the MFEM repository directory). I'm not an expert on licensing, but I think it should be fine to copy and paste the code also.

**Comment by tzanio** [comment] 2021-05-11 15:08
>  I'm not an expert on licensing, but I think it should be fine to copy and paste the code also.

If you copy+paste the code inside an mfem branch, that's totally fine (though you may want to synchronize when #2230 is merged to avoid duplication).

**Comment by tzanio** [comment] 2021-05-16 20:08
Discussion continued in #2240

**Closed by tzanio** 2021-05-16 20:08 UTC
Labels: bug, mesh
