### ISSUE TITLE
tests are not run

### ISSUE THREAD

**Issue by yurivict** [mfem/mfem#2442] opened 2021-08-01 17:15 UTC
Setting ```-DMFEM_ENABLE_TESTING=ON``` causes this message:
```
otal Test time (real) =   0.04 sec

The following tests FAILED:
	  1 - unit_tests (Not Run)
	  2 - sedov_tests_cpu (Not Run)
	  3 - sedov_tests_debug (Not Run)
	  4 - tmop_pa_tests_cpu (Not Run)
	  5 - tmop_pa_tests_debug (Not Run)
	  6 - debug_device_tests (Not Run)
	  7 - ex0_ser (Not Run)
	  8 - ex1_ser (Not Run)
	  9 - ex2_ser (Not Run)
	 10 - ex3_ser (Not Run)
	 11 - ex4_ser (Not Run)
	 12 - ex5_ser (Not Run)
	 13 - ex6_ser (Not Run)
[...]
```

Test executables weren't built.

**Comment by tzanio** [comment] 2021-08-02 00:33
Hi @yurivict,

Can you provide the full list of commands you are executing?

Is this something that worked before and now is not working with `mfem-4.3`?

Tzanio

**Comment by yurivict** [comment] 2021-08-02 00:39
```
cmake -DMFEM_USE_MPI:BOOL=false -DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_EXE_LINKER_FLAGS:STRING=" -fstack-protector-strong "  -DCMAKE_MODULE_LINKER_FLAGS:STRING=" -fstack-protector-strong "  -DCMAKE_SHARED_LINKER_FLAGS:STRING=" -fstack-protector-strong "  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -GNinja
```
```
make
```
```
make test
```

I never tried to run tests before.

**Comment by adrienbernede** [comment] 2021-08-02 09:29
Hello @yurivict. 
Looking at this, it seems you may not be building in a dedicated `build` directory.

For the record, MFEM has two build systems: Makefile (I will refer to as "original") and CMake. CMake is an out-of-source build system generator, that will generate a build-system in `Makefile` or another language like `Ninja`. Here, you chose Ninja, which is a good choice with CMake (and hopefully works with MFEM). But you are not building _out-of-source_. 

The clue was that you are missing ".." at the end of the first command. You are apparently configuring MFEM with *CMake* in-source (directly in the mfem root directory), and then running `make` and `make test`. The last 2 command will call the the original `Makefile` build system instead of the generated `Ninja`.

Here are your options:
- Use the original Makefile
```
cd <mfem-root-dir>
make config [...options...]
make all -j 8   # Build everything
make test       # Run the tests
```

- Use CMake + Makefile (option 1: explicit makefile)
```
cd <mfem-root-dir>
mkdir build
cd build
cmake [...options...] ..   # Note the ".."
make -j 8                  # Build MFEM
make tests -j 8            # Build unit-tests
make examples -j 8         # Build examples
make miniapps -j 8         # Build miniapps
make test                  # Run the tests
```

- Use CMake + Makefile (option 2: generic build, cmake wrappers)
```
cd <mfem-root-dir>
mkdir build
cd build
cmake [...options...] ..                  # Note the ".."
cmake --build . -j 8                      # Build MFEM
cmake --build . --target tests -j 8       # Build unit-tests
cmake --build . --target examples -j 8    # Build examples
cmake --build . --target miniapps -j 8    # Build miniapps
ctest --output-on-failure -T test         # Run the tests
```

- Use with CMake + Ninja (this is not what we are used to do, but it works)
```
cd <mfem-root-dir>
mkdir build
cd build
cmake [...options...] -GNinja ..          # Note the ".."
cmake --build . -j 8                      # Build MFEM
cmake --build . --target tests -j 8       # Build unit-tests
cmake --build . --target examples -j 8    # Build examples
cmake --build . --target miniapps -j 8    # Build miniapps
ctest --output-on-failure -T test         # Run the tests

**Comment by yurivict** [comment] 2021-08-02 15:29
No, it uses out-of-soutce build. Sorry, I missed ```..``` in my previous message.

**Comment by adrienbernede** [comment] 2021-08-02 15:57
Still, you are generating a Ninja build system, and then running make commands.
Please try following one of the suggestion above, and let us know if the issue remains.
Thank you.

**Comment by v-dobrev** [comment] 2021-08-02 21:18
Note: running the test with CMake is described here: https://github.com/mfem/mfem/blob/c528f79c9fc2f92612660ccf0f98cd1fe95879dc/INSTALL#L825-L837

**Comment by adrienbernede** [comment] 2021-08-04 15:25
Hello @yurivict, did this help?

**Comment by adrienbernede** [comment] 2021-08-09 18:36
@yurivict @tzanio @v-dobrev since I was able to reproduce the problem by building with -GNinja and then using Makefile commands, I believe this is solved and more clear now. (I also wrote a how-to article about this).

I believe we can close this.

**Comment by tzanio** [comment] 2021-08-09 19:23
Link to Adrien's article: https://github.com/mfem/web/blob/5621afc9e4c3a449393aa282211bf85262ecb180/src/howto/build-systems.md

**Comment by tzanio** [comment] 2021-08-09 19:24
I will close this now, but please feel free to reopen if you still have questions.

**Closed by tzanio** 2021-08-09 19:24 UTC
Labels: bug, examples & miniapps, testing
