### ISSUE TITLE
Error when 'make all' on ubuntu 22.04.1 LTS

### ISSUE THREAD

**Issue by etiennespieser** [mfem/mfem#3200] opened 2022-09-09 02:43 UTC
Hello,

when trying to build mfem with 'make all' cmd on ubuntu 22.04.1 LTS an error message prompted.

It appears to be linked with the 'catch.hpp' header. The post hereafter helped me to solve it:
https://github.com/madMAx43v3r/chia-plotter/issues/1002#issuecomment-1219024593 
I changed 
static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
into
static constexpr std::size_t sigStackSize = 32768;

I am new to C++ and just starting with mfem, I hope this comment will be useful to code developers.

**Comment by tzanio** [comment] 2022-09-11 01:00
Hi @etiennespieser,

Thanks for reporting this. What compiler and whis version was it with?

Tzanio

**Comment by etiennespieser** [comment] 2022-09-13 01:58
Hi @tzanio ,

Sorry, I don't know exactly which compiler was used. It must have been g++ 11. Here are the list of compiler installed on my computer:
$ dpkg --list | grep compiler
ii  g++                                        4:11.2.0-1ubuntu1                       amd64        GNU C++ compiler
ii  g++-11                                     11.2.0-19ubuntu1                        amd64        GNU C++ compiler
ii  gcc                                        4:11.2.0-1ubuntu1                       amd64        GNU C compiler
ii  gcc-11                                     11.2.0-19ubuntu1                        amd64        GNU C compiler
ii  gcc-11-multilib                            11.2.0-19ubuntu1                        amd64        GNU C compiler (multilib support)
ii  gcc-multilib                               4:11.2.0-1ubuntu1                       amd64        GNU C compiler (multilib files)
ii  libllvm13:amd64                            1:13.0.1-2ubuntu2.1                     amd64        Modular compiler and toolchain technologies, runtime library
ii  libllvm14:amd64                            1:14.0.0-1ubuntu1                       amd64        Modular compiler and toolchain technologies, runtime library
ii  libllvm9                                   2:9.0.1-0ppa4~ubuntu22.04               amd64        Modular compiler and toolchain technologies, runtime library
ii  libparams-validationcompiler-perl          0.30-1                                  all          module to build an optimized subroutine parameter validator
ii  libxkbcommon-dev:amd64                     1.4.0-1                                 amd64        library interface to the XKB compiler - development files
ii  libxkbcommon0:amd64                        1.4.0-1                                 amd64        library interface to the XKB compiler - shared library
ii  rpcsvc-proto                               1.4.2-0ubuntu6                          amd64        RPC protocol compiler and definitions

The precise cmd lline I used to build MFEM are
$ make build
$ make all -j4

Here is a sample of the log output displaying the error msg:

'''
g++ -O3 -std=c++11 -I../.. seq_test.o -o seq_test -L../.. -lmfem -lrt
make -C tests/unit
make[1]: Entering directory '/home/espieser/Documents/MFEM_debug_test/mfem-4.4/tests/unit'
g++ -g -c /home/espieser/Documents/MFEM_debug_test/mfem-4.4/tests/unit/unit_test_main.cpp  -O3 -std=c++11 -I../..  -I. -I../.. -o unit_test_main.o
g++ -O3 -std=c++11 -I../.. seqheat.o mtop_integrators.o paramnonlinearform.o pparamnonlinearform.o -o seqheat -L../.. -lmfem -lrt
rm mtop_integrators.o pparamnonlinearform.o paramnonlinearform.o seqheat.o
make[1]: Leaving directory '/home/espieser/Documents/MFEM_debug_test/mfem-4.4/miniapps/mtop'
g++ -g -c /home/espieser/Documents/MFEM_debug_test/mfem-4.4/tests/unit/fem/test_1d_bilininteg.cpp  -O3 -std=c++11 -I../..  -I. -I../.. -o fem/test_1d_bilininteg.o
g++ -O3 -std=c++11 -I../.. seq_example.o -o seq_example -L../.. -lmfem -lrt
rm seq_test.o seq_example.o
make[1]: Leaving directory '/home/espieser/Documents/MFEM_debug_test/mfem-4.4/miniapps/autodiff'
g++ -g -c /home/espieser/Documents/MFEM_debug_test/mfem-4.4/tests/unit/fem/test_2d_bilininteg.cpp  -O3 -std=c++11 -I../..  -I. -I../.. -o fem/test_2d_bilininteg.o
In file included from /usr/include/signal.h:328,
                 from /home/espieser/Documents/MFEM_debug_test/mfem-4.4/tests/unit/catch.hpp:8030,
                 from /home/espieser/Documents/MFEM_debug_test/mfem-4.4/tests/unit/unit_tests.hpp:15,
                 from /home/espieser/Documents/MFEM_debug_test/mfem-4.4/tests/unit/run_unit_tests.hpp:15,
                 from /home/espieser/Documents/MFEM_debug_test/mfem-4.4/tests/unit/unit_test_main.cpp:14:
/home/espieser/Documents/MFEM_debug_test/mfem-4.4/tests/unit/catch.hpp:10818:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
10818 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/sigstksz.h:24,
                 from /usr/include/signal.h:328,
                 from /home/espieser/Documents/MFEM_debug_test/mfem-4.4/tests/unit/catch.hpp:8030,
                 from /home/espieser/Documents/MFEM_debug_test/mfem-4.4/tests/unit/unit_tests.hpp:15,
                 from /home/espieser/Documents/MFEM_debug_test/mfem-4.4/tests/unit/run_unit_tests.hpp:15,
                 from /home/espieser/Documents/MFEM_debug_test/mfem-4.4/tests/unit/unit_test_main.cpp:14:
/usr/include/unistd.h:640:17: note: ‘long int sysconf(int)’ declared here
  640 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
In file included from /home/espieser/Documents/MFEM_debug_test/mfem-4.4/tests/unit/unit_tests.hpp:15,
                 from /home/espieser/Documents/MFEM_debug_test/mfem-4.4/tests/unit/run_unit_tests.hpp:15,
                 from /home/espieser/Documents/MFEM_debug_test/mfem-4.4/tests/unit/unit_test_main.cpp:14:
/home/espieser/Documents/MFEM_debug_test/mfem-4.4/tests/unit/catch.hpp:10877:45: error: size of array ‘altStackMem’ is not an integral constant-expression
10877 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
      |                                             ^~~~~~~~~~~~
g++  -O3 -std=c++11 -I..  ex9.cpp -o ex9 -L.. -lmfem -lrt
make[1]: *** [makefile:134: unit_test_main.o] Error 1
make[1]: *** Waiting for unfinished jobs....
g++  -O3 -std=c++11 -I..  ex10.cpp -o ex10 -L.. -lmfem -lrt
g++  -O3 -std=c++11 -I..  ex14.cpp -o ex14 -L.. -lmfem -lrt
make -C miniapps/electromagnetics
make[1]: Entering directory '/home/espieser/Documents/MFEM_debug_test/mfem-4.4/miniapps/electromagnetics'
make[1]: Nothing to be done for 'all'.
'''

Etienne

**Comment by tzanio** [comment] 2022-09-18 16:08
What is the output of `g++ --version`?

Does anyone else suse `g++ 11` or newer?

**Comment by etiennespieser** [comment] 2022-09-19 03:10
Hi @tzanio,

`g++ --version` gives me the output `g++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0`.

Serial examples are building and running properly with this version of g++, however I run into troubles with the parallel examples using `mpirun (Open MPI) 4.1.2`. The provided examples are building but return a segmentation fault error when they are run in parallel (my `config.mk` is maybe not set up correctly...).

The turnaround I have found was to use MFEM provided along with Spack, it is more convenient to use for a beginner like me since all dependencies are easily verified. 

Etienne

**Comment by tzanio** [comment] 2022-09-19 21:25
Spack is definitely the easiest if that works for you 👍 

It could be that your OpenMPI and g++ compilers or runtimes are not synchronized.

**Comment by tzanio** [comment] 2022-09-28 16:30
I can't reproduce this and the OP has found a workaround, so I am closing this now.

Please feel free to reopen, if this is still an issue with recent `g++` versions.

**Closed by tzanio** 2022-09-28 16:30 UTC
Labels: building
