### ISSUE TITLE
Template usage in kernel_dispatch.hpp is difficult to interpret (for SWIG)? 

### ISSUE THREAD

**Issue by sshiraiwa** [mfem/mfem#4530] opened 2024-10-03 20:21 UTC
I am opening this message here to get help from  C++ experts. 
With recent MFEM master, I am having a problem of  running SWIG to generate PyMFEM.
It somehow crashes.  Looking into the root cause, it appears that  SWIG have a difficulty tin understanding how template is used in kernel_dispatch.hpp. 
When I give this header file to SWIG separately, it spits out the following error message
/home/sshiraiw/venvs/env20220809/lib/python3.9/site-packages/mfem/external/ser/include/mfem/fem/kernel_dispatch.hpp:128: Error: Template partial specialization has more arguments than primary template 4 1.
Can someone tell what is going on? Is this an issue which has to be fixed in SWIG?

**Comment by pazner** [comment] 2024-10-03 22:14
That part of the code uses some kind of complicated templates and macros. Is it possible to simply skip that file when running SWIG? It's not really user-facing, so we don't actually need to generate any Python bindings for this.

**Comment by sshiraiwa** [comment] 2024-10-04 17:13
I already tried to skip it by %ignore directive in SWIG, but it does not work, probably because this line does not make sense at all for SWIG. While we don't need to expose it in Python binding, SWIG need to know the MFEM_REGISTER_KERNELS macro, which is defined above in the same file, in order to interpret bilininteg.hpp and quadinterpolator.hpp. 

I will try bit more to find a work-around.

**Comment by pazner** [comment] 2024-10-11 19:57
What compiler (and version) are you using?

It's related to [this](https://stackoverflow.com/a/29618545). We can add a fix/workaround if needed.

**Comment by sshiraiwa** [comment] 2024-10-14 11:41
@pazner, Thank you for prompt response. The compiler is from Apple default. (/usr/bin/c++), and --version spits out 
the following
```
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
Typical compiler command line generated by CMAKE is as follows
```
/usr/bin/c++ -DMFEM_CONFIG_FILE=\"/.../mfem/cmbuild_ser/config/_config.hpp\" -Dmfem_EXPORTS -I/.../mfem/cmbuild_ser -I/.../mfem -std=c++11 -O3 -DNDEBUG -std=c++11 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -fPIC -MD -MT CMakeFiles/mfem.dir/fem/fe/fe_nd.cpp.o -MF CMakeFiles/mfem.dir/fem/fe/fe_nd.cpp.o.d -o CMakeFiles/mfem.dir/fem/fe/fe_nd.cpp.o -c /.../mfem/fem/fe/fe_nd.cpp
```
Thank you in advance. The MacOS version is bit old (Monterey) due to some reason. I hope this is not the problem.

**Comment by pazner** [comment] 2024-10-14 16:41
Actually I think the problem has to do with the version of the standard library rather than the compiler version:

- [clang 14.0 with libstdc++ 5.5.0](https://godbolt.org/z/r3Wdz7s33) ❌ fails
- [clang 14.0 with libstdc++ 6.1.0](https://godbolt.org/z/nonY854GT) ✅ works
- [clang 14.0 with default flags](https://godbolt.org/z/TKMdYMzzn) ✅ works

Are you for some reason using an old version of the standard library? This was fixed in libstdc++ (gcc's standard library) in version 6.1.0 and libc++ (clang's standard library) in version 4 (both in 2013).

**Comment by sshiraiwa** [comment] 2024-10-20 17:27
@panzer, thank you for your advise. After a lot of trial and error, I found that I need to set -std=c++14, instead of c++11. Following is an example of compiler call, which works for me. Note that -std=c++14 is added before -std=c++11 is specified.  The first one is enforced using -DCMAKE_CXX_FLAGS flag when calling CMAKE. There is still  -std=c++11 remained, perhaps coming from MFEM's CMAKE default setting?
I am not sure what is the implication. Is MFEM using something from the c++14 standard not officially supported in C++11, and my compiler caught it ??? Anyhow, there is a workaround for this.
```
/usr/bin/c++ 
-DMFEM_CONFIG_FILE=\"./PyMFEM/external/mfem/cmbuild_ser/config/_config.hpp\"
-Dmfem_EXPORTS -I./PyMFEM/external/mfem/cmbuild_ser 
-./PyMFEM/external/mfem 
-std=c++14 O3 -DNDEBUG -std=c++11 -arch arm64 
-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk
-fPIC -MD -MT CMakeFiles/mfem.dir/fem/qinterp/grad_phys_by_nodes.cpp.o 
-MF CMakeFiles/mfem.dir/fem/qinterp/grad_phys_by_nodes.cpp.o.d 
-o CMakeFiles/mfem.dir/fem/qinterp/grad_phys_by_nodes.cpp.o 
-c ./PyMFEM/external/mfem/fem/qinterp/grad_phys_by_nodes.cpp
```

**Comment by pazner** [comment] 2024-10-20 18:20
Hi @sshiraiwa,

The problem you were running into is caused by the compiler flag:

```
-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk
```

This is sets the "system root directory", which will cause the compiler to use the C++ standard library found at `/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/c++/v1`. This is an old version of the standard library. If you use instead `-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk` (or later), I believe it should work.

Note that this is not exactly a C++14 vs. C++11 issue — it's not about the language per se, but rather about the implementation of the standard library. This should work with a C++11 compiler, as long as the standard library supports hashing enums.

**Comment by sshiraiwa** [comment] 2024-10-20 20:31
Hi @pazner 
Okay. Thanks. The line of sysroot is set, because the Python I am using (system Python) is built with this version of SDK, and difficult to change (I will have a different compatibility problem), unless I switch to another Python built differently, like Brew.

I think we can close this since there is work around and the root cause of issue is identified.
Do you anticipate any issue of setting -std=C++14 as above? Does it make the code break?

**Comment by pazner** [comment] 2024-10-21 16:08
There shouldn't be any issue setting -std=c++14 (or any standard newer than C++11), but just FYI that fix doesn't work for me.

Are you running on an older version of Mac OS?

BTW, this is the workaround I mentioned earlier. Does it also fix the issue for you? I'm hesitant to recommend merging this because the same code will need to be added for any enum used in the kernel dispatch and it's really just a workaround for pretty old versions of the standard library, once we move to C++17 (hopefully soon!) it should be irrelevant.

```diff
diff --git a/fem/fespace.hpp b/fem/fespace.hpp
index 7edb9e640..b8a006964 100644
--- a/fem/fespace.hpp
+++ b/fem/fespace.hpp
@@ -47,6 +47,10 @@ public:
    static void DofsToVDofs(int ndofs, int vdim, Array<int> &dofs);
 };
 
+// Note: std::hash is specialized for QVectorLayout below (outside the mfem
+// namespace). This is a workaround for a defect in older versions of the
+// standard library. Hashing is needed for kernel dispatch.
+
 /// @brief Type describing possible layouts for Q-vectors.
 /// @sa QuadratureInterpolator and FaceQuadratureInterpolator.
 enum class QVectorLayout
@@ -1385,6 +1389,15 @@ inline bool UsesTensorBasis(const FiniteElementSpace& fes)
 /// elements, otherwise, return NATIVE.
 ElementDofOrdering GetEVectorOrdering(const FiniteElementSpace& fes);
 
-}
+} // namespace mfem
+
+template <> struct std::hash<mfem::QVectorLayout>
+{
+   size_t operator()(const mfem::QVectorLayout &x) const
+   {
+      return std::hash<int>()(static_cast<int>(x));
+      // Could also just do: return static_cast<size_t>(x);
+   }
+};
 
 #endif
```

**Comment by sshiraiwa** [comment] 2024-10-22 00:38
Thank you. As I wrote earlier, the MacOS version is bit old (Monterey=2022) due to some reason. I was hoping this is not the problem, but it seems this is a part of problem. 
I propose to close this. For now, my workaround is okay for myself, and good enough to finish a PR in PyMFEM (https://github.com/mfem/PyMFEM/pull/254). I will see if I can update MacOS.

**Comment by pazner** [comment] 2024-10-22 02:44
Thanks @sshiraiwa. Closing for now. Please re-open if it continues to be an issue.

**Closed by pazner** 2024-10-22 02:44 UTC
Labels: question, python
