### ISSUE TITLE
What are the boundary conditions in example 9?

### ISSUE THREAD

**Issue by LeilaSalomon** [mfem/mfem#1840] opened 2020-10-26 10:33 UTC
Hello,

I'm trying to solve a simple advection equation in DG space. So I decided to use Example 9, which looks like my problem. I'm just not using an inflow condition, so I solve **M du/dt = K u**  and not **M du/dt = K u + b**.

I ask myself a question which is very important for my resolution : what are the boundary conditions used in this example for the compute of u?

Regards,

Leïla

**Comment by pazner** [comment] 2020-10-26 16:51
Hi @LeilaSalomon,
At inflow boundaries (velocity vector points inside the domain), an inflow solution is specified (in ex9 this is specified using the `inflow` coefficient). At outflow boundaries, no boundary conditions are required.

**Comment by LeilaSalomon** [comment] 2020-10-26 18:04
Hello, I don't use inflow coefficient, so I don't know what is set by default? What are the boundary conditions on the upper and lower walls?

**Comment by pazner** [comment] 2020-10-26 18:18
If you omit the inflow term, it will be the same as prescribing a zero boundary condition.

**Comment by LeilaSalomon** [comment] 2020-10-26 20:19
What do you mean ? It is equivalent to putting Dirichlet? u = 0 ?

**Comment by pazner** [comment] 2020-10-26 20:24
It is equivalent to Dirichlet u=0 on the inflow boundaries.

**Comment by LeilaSalomon** [comment] 2020-10-26 20:36
It's very strange because when I visualize the solution in GLVis, the solution is not equal to 0 (inlet and outlet). And what about the boundary conditions on the upper and lower walls of the domain?

**Comment by rw-anderson** [comment] 2020-10-26 20:45
It's very helpful if you show the glvis images you are looking at so we can be sure we're talking about the same thing.

**Comment by LeilaSalomon** [comment] 2020-10-26 20:50
> It's very helpful if you show the glvis images you are looking at so we can be sure we're talking about the same thing.

How can I do that ?

**Comment by pazner** [comment] 2020-10-26 20:53
> It's very strange because when I visualize the solution in GLVis, the solution is not equal to 0 (inlet and outlet). And what about the boundary conditions on the upper and lower walls of the domain?

The boundary conditions (inflow or outflow) depend on the velocity field. Without knowing what the velocity field is for your problem, it is impossible to say what the boundary conditions are on the upper and lower walls of the domain (I also don't know what domain you are solving your problem on).

If the boundary is an outflow boundary (velocity field point outwards), then no boundary conditions are needed and none are enforced.

**Comment by LeilaSalomon** [comment] 2020-10-26 21:00
> > It's very strange because when I visualize the solution in GLVis, the solution is not equal to 0 (inlet and outlet). And what about the boundary conditions on the upper and lower walls of the domain?
> 
> The boundary conditions (inflow or outflow) depend on the velocity field. Without knowing what the velocity field is for your problem, it is impossible to say what the boundary conditions are on the upper and lower walls of the domain (I also don't know what domain you are solving your problem on).
> 
> If the boundary is an outflow boundary (velocity field point outwards), then no boundary conditions are needed and none are enforced.

Effectively I give boundary conditions to my velocity field. But when solving d**u** / dt = vGrad (**u**), are there necessarily boundary conditions on **u** no?

**Comment by pazner** [comment] 2020-10-26 21:20
> Effectively I give boundary conditions to my velocity field. But when solving d**u** / dt = vGrad (**u**), are there necessarily boundary conditions on **u** no?

Boundary conditions for u are only required on inflow boundaries. No boundary conditions for u are required at outflow boundaries. The number of boundary conditions required for hyperbolic equations (like linear advection) is determined by the number of negative eigenvalues of the flux Jacobian, see e.g. http://www.ita.uni-heidelberg.de/~dullemond/lectures/num_fluid_2011/Chapter_2.pdf

**Comment by LeilaSalomon** [comment] 2020-10-27 16:18
Ok, thanks. I'm not sure I understand everything. Can I explain the problem that I'm solving to you?

My domain Omega is rectangular, I want to solve the following advection equation:

d**u**/dt + div(V**u**) = 0 (conservative form)

The solution **u** is known at time t = 0 in the whole domain. The velocity field V is analytical, and known at each time step. I impose boundary conditions on the velocity fields, on the 4 walls of the domain.

My resolution system is as follows:

 BilinearForm m(fes);
 m.AddDomainIntegrator(new MassIntegrator);

 BilinearForm k(fes);
 k.AddDomainIntegrator(new TransposeIntegrator(new ConvectionIntegrator(velocity))); 
 k.AddInteriorFaceIntegrator(                                                   
      (new DGTraceIntegrator(velocity, -1.0, -0.5)));
 k.AddBdrFaceIntegrator(                       
      (new DGTraceIntegrator(velocity, -1.0, -0.5)));

 m.Assemble();
 m.Finalize();
 int skip_zeros = 0;
 k.Assemble(skip_zeros);
 k.Finalize(skip_zeros);

In this system, I cannot see where the boundary conditions are declared.

**Comment by pazner** [comment] 2020-10-27 16:45
> My domain Omega is rectangular, I want to solve the following advection equation:
> 
> d**u**/dt + div(V**u**) = 0 (conservative form)
> 
> The solution **u** is known at time t = 0 in the whole domain. The velocity field V is analytical, and known at each time step. I impose boundary conditions on the velocity fields, on the 4 walls of the domain.

Is your velocity field divergence free? If it is divergence free, then the conservative and non-conservative forms will be equivalent. If not, there will be an additional "reaction" term involving div(V).

If your velocity field is known analytically, you do not need to impose boundary conditions on it.

However, you do need to impose boundary conditions on the solution field u. You cannot enforce boundary conditions on all 4 walls of the domain — you can only enforce boundary conditions on **inflow** boundaries. Which of the walls are inflow and which are outflow depends on your velocity field.

In the code that you attached, you do not have a `BoundaryFlowIntegrator`. Because this term is omitted, this is equivalent to enforcing a zero boundary condition at inflow boundaries.

Perhaps it would be helpful to include the analytical formula for the velocity field and initial condition.

**Comment by rw-anderson** [comment] 2020-10-27 17:51
> > It's very helpful if you show the glvis images you are looking at so we can be sure we're talking about the same thing.
> 
> How can I do that ?

As it says in the bottom of the box here, you can attach files by dragging and dropping them.

**Comment by LeilaSalomon** [comment] 2020-11-01 11:59
> > My domain Omega is rectangular, I want to solve the following advection equation:
> > d**u**/dt + div(V**u**) = 0 (conservative form)
> > The solution **u** is known at time t = 0 in the whole domain. The velocity field V is analytical, and known at each time step. I impose boundary conditions on the velocity fields, on the 4 walls of the domain.
> 
> Is your velocity field divergence free? If it is divergence free, then the conservative and non-conservative forms will be equivalent. If not, there will be an additional "reaction" term involving div(V).
> 
> If your velocity field is known analytically, you do not need to impose boundary conditions on it.
> 
> However, you do need to impose boundary conditions on the solution field u. You cannot enforce boundary conditions on all 4 walls of the domain — you can only enforce boundary conditions on **inflow** boundaries. Which of the walls are inflow and which are outflow depends on your velocity field.
> 
> In the code that you attached, you do not have a `BoundaryFlowIntegrator`. Because this term is omitted, this is equivalent to enforcing a zero boundary condition at inflow boundaries.
> 
> Perhaps it would be helpful to include the analytical formula for the velocity field and initial condition.


Hi ! Thank you for your help,

So, in the following equation : du/dt + div(V.u) = 0, if I don't have a BoundaryFlowIntegrator (because I omit this term),
does this mean that I have zero flux at the inlet boundary ? With flux = V.u.

**Comment by pazner** [comment] 2020-11-02 23:04
> So, in the following equation : du/dt + div(V.u) = 0, if I don't have a BoundaryFlowIntegrator (because I omit this term),
> does this mean that I have zero flux at the inlet boundary ? With flux = V.u.

That should mean that the solution u is zero at the inflow boundary.

**Comment by LeilaSalomon** [comment] 2020-11-04 08:21
> > So, in the following equation : du/dt + div(V.u) = 0, if I don't have a BoundaryFlowIntegrator (because I omit this term),
> > does this mean that I have zero flux at the inlet boundary ? With flux = V.u.
> 
> That should mean that the solution u is zero at the inflow boundary.

Ok, but let us imagine (always in the case where I omit BoundaryFlowIntegrator ) that the analytical velocity is zero on all the edges of the field.

In this case, u must not be zero at the inflow boundary since the velocity is already equal to 0 and therefore the flux is zero, no ?

**Comment by pazner** [comment] 2020-11-04 16:47
> Ok, but let us imagine (always in the case where I omit BoundaryFlowIntegrator ) that the analytical velocity is zero on all the edges of the field.
> 
> In this case, u must not be zero at the inflow boundary since the velocity is already equal to 0 and therefore the flux is zero, no ?

If the velocity is zero at the boundary, then it is not an inflow boundary.

**Comment by LeilaSalomon** [comment] 2020-11-04 17:13
Yes, it's true. I have one last question: If now, on the same wall of my domain, I have a part with an inflow and another part with an outflow, it's a problem no?

**Comment by pazner** [comment] 2020-11-04 18:12
> Yes, it's true. I have one last question: If now, on the same wall of my domain, I have a part with an inflow and another part with an outflow, it's a problem no?

That is not a problem, this situation should be handled automatically by the DG discretization.

For example, the following velocity field would be fine.

<img width="441" alt="image" src="https://user-images.githubusercontent.com/11493037/98152053-f7b12f00-1e85-11eb-814c-fbcb7ff4bd5b.png">

Ideally, the point where the sign of the normal velocity changes should lie on an element interface, but it's not required.

**Comment by LeilaSalomon** [comment] 2020-11-04 18:28
> > Yes, it's true. I have one last question: If now, on the same wall of my domain, I have a part with an inflow and another part with an outflow, it's a problem no?
> 
> That is not a problem, this situation should be handled automatically by the DG discretization.
> 
> For example, the following velocity field would be fine (the left half of the bottom boundary is inflow, the right half is outflow).
> 
> <img alt="image" width="441" src="https://user-images.githubusercontent.com/11493037/98152053-f7b12f00-1e85-11eb-814c-fbcb7ff4bd5b.png">
> 
> Ideally, the point where the sign of the normal velocity changes should lie on an element interface, but it's not required.

Ok, if I take your example, after I define my inflow_function, the code will understand that it is to apply inflow_function only on the left part (for negative values) of the bottom edge of the domain?

**Comment by pazner** [comment] 2020-11-04 18:40
> Ok, if I take your example, after I define my inflow_function, the code will understand that it is to apply inflow_function only on the left part (for negative values) of the bottom edge of the domain?

Yes, it should happen automatically.

**Comment by LeilaSalomon** [comment] 2020-11-06 12:21
Ok, thank you very much for your help.

The case in which I'm working requires to impose **u** in the inflow boundary : I'm having a problem.

1 - Initially, I use an analytical velocity field to make the solution **u** evolve. I impose **u** in the inflow boundary. Inflow is then correctly calculated, the numerical solution **u** corresponds to the analytical solution: everything works well.

2 - Now, I don't want to use analytical velocities anymore. For that, I would like my code to calculate the gradient of an analytical solution, which I note **A**. My velocity field is now Grad (**A**). From a theoretical point of view : Grad (**A**) = analytical velocities (used in 1 - ). So normally, I have the same velocities as in the 1 - case.

Here, to get V_x and V_y, I use a GridFunction with the values ​​of **A**, and then use GradientGridFunctionCoefficient **velocity** (& **A**). I then use those velocities, with the same inflow boundary as in 1 -, to make  **u** evolve.

Unfortunately using this method, the solution **u** is not calculated correctly, and I don't understand why...

In my rectangular domain, the solution is not well calculated in the last column of the mesh...

I am using the same velocity field, same inflow boundary as the 1 - case, why the results don't match?

**Comment by pazner** [comment] 2020-11-06 19:40
It is hard to say exactly why your case isn't working without knowing more specific details, such as the expression for the velocity potential *A*, exactly what about the solution is not correct (is the error just larger, or is something qualitatively wrong), etc.

One thing that I would note is that you are creating a grid function with the values of *A* (likely by interpolating, e.g. using `ProjectCoefficient`). Depending on which interpolation points you are using (depends on the basis of the finite element space), then the resulting grid function may or may not be continuous. In either case, the *gradient* of this grid function will be **discontinuous** (even if grad(*A*) is continuous). This could lead to behavior that is different from what you expect.

**Comment by LeilaSalomon** [comment] 2020-11-09 15:51
> It is hard to say exactly why your case isn't working without knowing more specific details, such as the expression for the velocity potential _A_, exactly what about the solution is not correct (is the error just larger, or is something qualitatively wrong), etc.
> 
> One thing that I would note is that you are creating a grid function with the values of _A_ (likely by interpolating, e.g. using `ProjectCoefficient`). Depending on which interpolation points you are using (depends on the basis of the finite element space), then the resulting grid function may or may not be continuous. In either case, the _gradient_ of this grid function will be **discontinuous** (even if grad(_A_) is continuous). This could lead to behavior that is different from what you expect.


Expression of my velocity potential **A(x,y,t)** is: **Cg/w  *  (cosh [k(y+h)]/cosh(k*h))  * cos(k*x) * sin(w*t)**. With C,g,w,k,h constants.
**A** is recalculated at each time step. I get the velocity field with GradientGridFunctionCoefficient **velocity** (& **A**).

At first I used a VectorCoefficient with analytical velocity, the code didn't encounter any problem, here is the result (desired result) obtained at the final time:

![analytical_solution](https://user-images.githubusercontent.com/40572513/98559770-5243f400-22a7-11eb-9d3c-1ae3a512218b.png)

Now, when I use Grad(**A**), my final result is not correct, this is what it looks like:

![gradA_solution](https://user-images.githubusercontent.com/40572513/98559791-5708a800-22a7-11eb-9092-8ba0640c9148.png)

The mesh used is the following one:

![mesh](https://user-images.githubusercontent.com/40572513/98563556-9a651580-22ab-11eb-80e4-bef8bfbea240.png)

We notice that the solution is not well calculated in the last column of the domain. The result here is at order 2, because at order 1, the gradient of A is not calculated precisely.

I have checked well: at order 2, the Grad(A) values are the same as those obtained with the VectorCoefficient of analytical velocity. In both cases, I use the same Coefficient inflow, is that the problem ?

**Comment by pazner** [comment] 2020-11-09 18:25
Can you please give a complete problem specification? i.e. dimensions of the domain, values of the constants C, g, w, k, h, final time, initial conditions, etc.?

**Comment by LeilaSalomon** [comment] 2020-11-09 19:46
2D domain : [0;1] x [-1.5;0.03]

The constants :
g = 9.81;
C= 0.01; 
k = pi; 
h = 1.5;
w = sqrt(g*k*tanh(k*h));

Initial condition for u : 

double u0_function(const Vector &x)
{
    double C = 0.01;
    double k = M_PI; 

    double eta =  - C * cos(k*x(0));

   // Distance between eta and nodes:

    if ( x(1) < eta )
    {
    return - abs(x(1)-eta);
    }
    else if ( x(1) > eta )
    {
    return abs(x(1)-eta);
    }
    else if ( x(1) == eta )
    {
    return 0;
    }
}

Inflow u conditions :

double inflow_function(const Vector &x, double t)
{
  double g = 9.81;
  double C = 0.01; 
  double k = M_PI;
  double h = 1.5; 

  double omega = sqrt(g*k*tanh(k*h)); 

  double eta =  - C * cos(k*x(0))*cos(omega*t); 

  double u_analytical_BI = abs(x(1) - eta);

  return u_analytical_BI;
}

Final time : t_f = 2*T = 2*(2*pi/w);

**Comment by pazner** [comment] 2020-11-09 23:30
Your problem seems like it is probably caused by the error that you incur when you represent the potential as a grid function (note that since your potential function is composed of trigonometric/hyperbolic functions, it cannot be represented exactly as a grid function). You could mitigate this error by increasing the order of the FE space or by increasing the resolution of the mesh. Another option would be to avoid representing your velocity potential as a gird function altogether...

**Comment by LeilaSalomon** [comment] 2020-11-10 08:26
> Your problem seems like it is probably caused by the error that you incur when you represent the potential as a grid function (note that since your potential function is composed of trigonometric/hyperbolic functions, it cannot be represented exactly as a grid function). You could mitigate this error by increasing the order of the FE space or by increasing the resolution of the mesh. Another option would be to avoid representing your velocity potential as a gird function altogether...

The results that I have attached to you in pictures are in order 2. Effectively, in order 1 the results are not correct.
However, one notices well on picture 2 that the solution is not well calculated **only in the last column of the mesh**. If I refine the mesh, I still notice the same thing: the solution is not correct in the last column.
It's very strange because when I compare the values of numerical grad (**A**) to order 2 with the analytical V_x V_y values: the values are the **same**, everywhere in the field. So, the error doesn't seem to come from the GridFunction **A**...

**Comment by LeilaSalomon** [comment] 2020-11-12 16:50
Hi :) 

Like I told you in my previous message, when I compare the values of numerical grad (**A**) (order 2) with the **analytical V_x V_y** values: the values are the same, everywhere on the nodes of the mesh.

But now, I want to see what velocities **BoudaryFlowIntegrator**(inflow,**velocity**,-1.0,-0.5) is using. For that, I go to lininteg.cpp to analyze the values of the variable that is declared **uv**. For each segment belonging to the boundaries of the domain, the code uses 2 values **vu** (this velocities are not calculated on the nodes of the mesh). I wonder how the code calculates these values **vu** from the VectorCoefficient **velocity** that I give?

Indeed, I notice that **vu** is different if I use grad (**A**) than **V_x V_y analytics** for **velocity**.

**Comment by pazner** [comment] 2020-11-12 17:42
Hi @LeilaSalomon,

Note that you should be comparing the values of the velocity at **quadrature points** and not **nodal points**. The integration of the terms in the bilinear form occurs at **quadrature points** determined by the `IntegrationRule` in the integrator.

The numerical grad(*A*) and the analytical grad(*A*) **cannot** be the same, because *A* is composed of trigonometric and hyperbolic functions which cannot be represented as a piecewise polynomial. The numerical *A* and analytical *A* must be different, and their gradients must also be different. Note that the values may be "close", and the numerical *A* may well-approximate the analytical *A*, but they will not be identical.

One thing to keep in mind is that your velocity field is tangential to the right wall of your domain. That means that even a small error in the velocity field may turn this boundary into an inflow boundary, which could change the results depending on your inflow boundary conditions.

It is also possible that you may have other issues/bugs in your code that we haven't considered in this discussion.

I modified ex9 to solve your problem with both analytical and numerical *A*, and the results for both of them are quite similar, and I don't see the same distortion that you observe in the second figure that you posted.

**Comment by LeilaSalomon** [comment] 2020-11-12 18:25
> Hi @LeilaSalomon,
> 
> Note that you should be comparing the values of the velocity at **quadrature points** and not **nodal points**. The integration of the terms in the bilinear form occurs at **quadrature points** determined by the `IntegrationRule` in the integrator.
> 
> The numerical grad(_A_) and the analytical grad(_A_) **cannot** be the same, because _A_ is composed of trigonometric and hyperbolic functions which cannot be represented as a piecewise polynomial. The numerical _A_ and analytical _A_ must be different, and their gradients must also be different. Note that the values may be "close", and the numerical _A_ may well-approximate the analytical _A_, but they will not be identical.
> 
> One thing to keep in mind is that your velocity field is tangential to the right wall of your domain. That means that even a small error in the velocity field may turn this boundary into an inflow boundary, which could change the results depending on your inflow boundary conditions.
> 
> It is also possible that you may have other issues/bugs in your code that we haven't considered in this discussion.
> 
> I modified ex9 to solve your problem with both analytical and numerical _A_, and the results for both of them are quite similar, and I don't see the same distortion that you observe in the second figure that you posted.

When **velocity** in BoudaryFlowIntegrator(inflow,**velocity**,-1.0,-0.5)  is a VectorCoefficient obtained from a function which gives the analytical velocities, I observe that **uv**(0) = 0 on the right wall in lininteg.cpp.
Now, when **velocity** is calculated with GradientGridFunctionCoefficient **velocity**(& **A**) (**A** = analytical potential) then **uv**(0) is no longer zero, its value is low but maybe that's why I observed this distortion on the right wall (like on figure 2)

**Comment by pazner** [comment] 2020-11-12 19:42
> When **velocity** in BoudaryFlowIntegrator(inflow,**velocity**,-1.0,-0.5) is a VectorCoefficient obtained from a function which gives the analytical velocities, I observe that **uv**(0) = 0 on the right wall in lininteg.cpp.
> Now, when **velocity** is calculated with GradientGridFunctionCoefficient **velocity**(& **A**) (**A** = analytical potential) then **uv**(0) is no longer zero, its value is low but maybe that's why I observed this distortion on the right wall (like on figure 2), no ?

Yes, I think that is a possibility. uv(0) = 0 because the velocity is tangential to the right wall. If uv(0) is non-zero, then the boundary will be either inflow or outflow depending on the sign. If the boundary is inflow, the boundary conditions could cause this distortion.

**Comment by LeilaSalomon** [comment] 2020-11-12 20:00
Okay, but what I don't understand is when I plot V_x = d**A**/dx (see the following figure), we notice that V_x = 0 on the right wall. So how can **uv**(0) be different from 0 in lininteg.cpp ?

![u_num](https://user-images.githubusercontent.com/40572513/98989869-fe950d00-2529-11eb-91d8-b656c5c23f19.png)

**Comment by pazner** [comment] 2020-11-13 02:34
It is possible that the values of dA/dx are small, but not exactly zero. I will mention again that I implemented your problem as modifications to ex9, and I did not observe the same distortion that you are reporting.

**Comment by LeilaSalomon** [comment] 2020-11-15 20:19
Hi :)

Until now, I have been using 4-1 version of MFEM. So, I downloaded the last version: 4-2, and now, I don't observe the same distortion as observed on my picture above. Do you understand why?

**Comment by tzanio** [comment] 2020-11-15 20:45
Hi @LeilaSalomon, mfem-4.1 is more than 1.5 years old now and there have been improvements and fixes. 

We always recommend to use the latest mfem release when possible.

**Comment by LeilaSalomon** [comment] 2020-11-16 16:37
Hi, yes ok :)

Thanks a lot for your help. My analytical case has been working since I imposed the right boundary conditions for inflow in BoudaryFlowIntegrator(**inflow**,**velocity**, -1.0, -0.5).

Now, I'm working with a non-analytical case. I remind you that I solve du / dt + div (u.V) = 0. My flux is (**u.V**)

I have no problem to give a numerical VectorCoefficient **velocity** to BoudaryFlowIntegrator(), I calculate my velocity potential **A** in the domain, and after I calculate its gradient with GradientGridFunctionCoefficient **velocity** (& **A**). 

But now, I would like to use a "numerical" **inflow** Coefficient. My solution u is known at the initial moment (in a GridFunction), I call it u_n. I would like **inflow** to return u_n for u_ (n+1) to be calculated. Is it possible ?

**Comment by pazner** [comment] 2020-11-17 02:30
> But now, I would like to use a "numerical" **inflow** Coefficient. My solution u is known at the initial moment (in a GridFunction), I call it u_n. I would like **inflow** to return u_n for u_ (n+1) to be calculated. Is it possible ?

I think this should be possible by setting the `inflow` coefficient to be a `GridFunctionCoefficient` with the grid function representing u_n.

**Comment by LeilaSalomon** [comment] 2020-11-22 15:58
Thank you very much. You guys have all been a very big help to me :)

**Comment by tzanio** [comment] 2020-11-22 23:31
Glad that we can help 👍 

I will close this now, but feel free to reopen if you have further quesitons.

**Closed by tzanio** 2020-11-22 23:31 UTC
Labels: examples & miniapps, fem, usage
