### ISSUE TITLE
Strange behaviour on boundaries in parallel version for the Sod problem

### ISSUE THREAD

**Issue by vkorchagova** [mfem/mfem#1730] opened 2020-08-31 16:14 UTC
Good evening,

I try to compute the cylindrical Sod problem using the non-periodic mesh which has been created in gmsh. For this goal, I modify the ex18p example: I create an appropriate problem and use general ExplicitRKSolver.. The idea for boundaries is simple: if I use the same FaceIntegrator for internal and boundary cases, the states on the gauss points in the boundary faces have to be equal (due to `fe2 = fe1;` string in the `void NonlinearForm::Mult(const Vector &x, Vector &y) const` function). The problem statement places the circular "explosion" in the center of my computational domain; solution near boundaries should stay constant during at least 10 first time steps. For the serial computation, I see a correct result, but in parallel mode, I see strange disturbances near the piece of the boundary, moreover, only for one of the processes. You can find attached pictures for 4 cores and 12 cores respectively.

![sod4c](https://user-images.githubusercontent.com/19410260/91740084-77d3c380-ebbb-11ea-974e-90ac93313d71.png)
![sod12c](https://user-images.githubusercontent.com/19410260/91740083-773b2d00-ebbb-11ea-9798-0c1e27ad2f8f.png)

When I've looked through the code I've found that these disturbances appear after the last stage of ExplicitRKSolver. I'm still in the dark when trying to find the source of disturbances... Could anyone help me, please?

--
Best regards,
Victoria Korchagova

**Comment by jdahm** [comment] 2020-09-01 18:40
A wild guess would be that the mesh orientations are somehow incorrect, so the quadrature points are not quite lining up from either side of the face. You can either verify or rule this out by printing out the global positions of the quadrature points.

**Comment by vkorchagova** [comment] 2020-09-02 14:58
Dear @jdahm ,

Thank you for your answer. Gauss points seem to be consistent (I've compared the result of element transformations for eip1 and eip2 points for one cell with the wrong solution).
Maybe I couldn't write the simple instruction` A.AddBdrFaceIntegrator(new FaceIntegrator(rsolver, dim));` in the main function and I should create the separate boundary integrator?..

**Comment by rw-anderson** [comment] 2020-09-02 18:01
You've confirmed that this is a real in-situ data issue, and not a visualization artifact?

**Comment by vladotomov** [comment] 2020-09-03 02:21
It's difficult to guess from the given info. Check if all RK states are initialized, maybe some of the tasks is initializing a `Vector` to non-zero.

Does it happen right away after the first time step and stay constant, or is the weird value at the boundary changing? The wrong value also seems to be in your solution range, around 0.5; is this a special value for some of the variables? Which field are you plotting, are the other fields behaving the same way?

**Comment by vladotomov** [comment] 2020-09-03 19:02
For me it's clear that `k[i]` gets wrong values at the boundary for one of the MPI tasks. I would make one step, using the minimum number of MPI tasks that produce the error, track down the task and the degree of freedom numbers, and debug how these values appear.

**Comment by vkorchagova** [comment] 2020-09-04 15:38
The problem is solved. I could not use the same integrator for boundary and internal faces because `elfun2_mat` initialization strongly requires the difference of `el1` and `el2`. When these elements are the same the "memory window" for `elfun2_mat` will be incorrect: no errors produced but the information of some other element on boundary appears in `elfun2_mat`. Also, it will be some addition operation with boundary by `elvect2_mat`.
I'm so sorry for my stupid question! When I've created the "honest" boundary integrator the error disappeared!
Thank you very much for your patience and answers!

**Comment by jdahm** [comment] 2020-09-04 18:06
Glad you found the issue! I'll close this now then. Let us know if there is anything else that comes up that may be an issue with MFEM.

**Closed by jdahm** 2020-09-04 18:06 UTC
Labels: examples & miniapps, fem, usage
