### ISSUE TITLE
Building mfem with Intel and Pgi

### ISSUE THREAD

**Issue by tsariysk** [mfem/mfem#608] opened 2018-09-13 22:25 UTC
Hi,

I am able to build mfem-3.4 with Gnu, but Pgi and Intel both fail (see attachments). Do I miss compiler flags or environment settings? Any help is highly appreciated.

Thanks,
Ted

OS  : Darwin Kernel Version 17.7.0 xnu-4570.71.2~1/RELEASE_X86_64 x86_64
Intel: icpc (ICC) 17.0.4 20170411
Pgi. : pgc++ 18.4-0 64-bit target on macOS -tp p7-64 

[intel.log](https://github.com/mfem/mfem/files/2381164/intel.log)
[pgi.log](https://github.com/mfem/mfem/files/2381165/pgi.log)

**Comment by tzanio** [comment] 2018-09-17 21:30
These error are strange and I'm not sure what's causing them.

PGI seems to be complaining about this destructor in `fem/geom.cpp`:
```c++
Geometry::~Geometry()
{
   for (int i = 0; i < NumGeom; i++)
   {
      delete PerfGeomToGeomJac[i];
      delete GeomToPerfGeomJac[i];
      delete GeomVert[i];
   }
}
```
but I don't see anything wrong with it, and compilers are not supposed to have "internal errors" :)

Can you try the current master branch, or maybe hardcoding `NumGeom` to 6 just to see if that will affect the compiler?

The Intel issue seems to be a missing `-std=c++11`.

It is possible (though not very likely), that there are contributing issues from using CMake instead of the Makefile system... @benson31 may be able to help with that.

Cheers,
Tzanio

**Comment by tsariysk** [comment] 2018-09-18 14:16
[intel.log](https://github.com/mfem/mfem/files/2393020/intel.log)

For Intel, adding -std=c++11 helps up to a point, see attachment. It makes no difference for Pgi. 

I haven't try hardcoding NumGeom to 6, yet.

Thanks,
Ted

**Comment by Rombur** [comment] 2018-09-18 14:32
@tsariysk 
- For Intel, your problem now looks like it is from the STL that you are using. Does the gcc version that you are using with your Intel compiler support C++11?
- PGI 18.04 has an LLVM code generator see [here](https://www.pgroup.com/resources/docs/18.1/x86/pgi-release-notes/index.htm#llvm-backend). In my experience it works better for C++ than the default version of PGI.

**Comment by v-dobrev** [comment] 2018-09-18 19:16
I just built mfem v3.4 using both Intel v17.0.2 and PGI v18.5 (on Linux) and I did not encounter any issues.

You seem to be building mfem from within a larger build system. Can you try building it standalone? For example, what I did was:
* Checkout (or simlpy un-tar) mfem 3.4 in `mfem-3.4`
* `cd mfem-3.4`
* `mkdir build`
* `cd build`
* `cmake .. -DCMAKE_CXX_COMPILER=/path/to/icpc`
* `make`

Similarly, you can replace `/path/to/icpc` with `/path/to/pgc++`.

**Comment by tsariysk** [comment] 2018-09-18 20:50
On Linux I am able to build mfem with Intel-17 and with Gnu v.4.4.7.  
In MacOS I have issues to compile mfem both with Intel and with Pgi. I am still working on it. 

Linux/Pgi-18.4 gives the same error with and without -Mllvm. I tried the v-dobrev steps - the same error (I don't have 18.5, though).

Thanks,
Ted
...
[  2%] Building CXX object CMakeFiles/mfem.dir/fem/fe.cpp.o
/usr/local/pgi/18.4/linux86-64-llvm/18.4/mpi/openmpi/bin/mpicxx  -DMFEM_BUILD_DIR=/ascldap/users/tesari/local/ep_cmt/pgi/mfem/src/ep_mfem-build  -std=c++11 -std=c++11 -Mllvm -fast -O3 -DNDEBUG   -o CMakeFiles/mfem.dir/fem/fe.cpp.o -c /ascldap/users/tesari/local/ep_cmt/pgi/mfem/src/ep_mfem/fem/fe.cpp
[  4%] Building CXX object CMakeFiles/mfem.dir/fem/geom.cpp.o
/usr/local/pgi/18.4/linux86-64-llvm/18.4/mpi/openmpi/bin/mpicxx  -DMFEM_BUILD_DIR=/ascldap/users/tesari/local/ep_cmt/pgi/mfem/src/ep_mfem-build  -std=c++11 -std=c++11 -Mllvm -fast -O3 -DNDEBUG   -o CMakeFiles/mfem.dir/fem/geom.cpp.o -c /ascldap/users/tesari/local/ep_cmt/pgi/mfem/src/ep_mfem/fem/geom.cpp
PGCC-S-0000-Internal compiler error. flowgraph: node is zero     169  (/ascldap/users/tesari/local/ep_cmt/pgi/mfem/src/ep_mfem/fem/geom.cpp: 976)
PGCC-S-0000-Internal compiler error. flowgraph: node is zero     170  (/ascldap/users/tesari/local/ep_cmt/pgi/mfem/src/ep_mfem/fem/geom.cpp: 976)
PGCC-S-0000-Internal compiler error. flowgraph: node is zero     171  (/ascldap/users/tesari/local/ep_cmt/pgi/mfem/src/ep_mfem/fem/geom.cpp: 976)
PGCC-S-0000-Internal compiler error. flowgraph: node is zero     172  (/ascldap/users/tesari/local/ep_cmt/pgi/mfem/src/ep_mfem/fem/geom.cpp: 976)
PGCC-S-0000-Internal compiler error. flowgraph: node is zero     173  (/ascldap/users/tesari/local/ep_cmt/pgi/mfem/src/ep_mfem/fem/geom.cpp: 976)
PGCC-S-0000-Internal compiler error. flowgraph: node is zero     174  (/ascldap/users/tesari/local/ep_cmt/pgi/mfem/src/ep_mfem/fem/geom.cpp: 976)
PGCC-S-0000-Internal compiler error. flowgraph: node is zero     175  (/ascldap/users/tesari/local/ep_cmt/pgi/mfem/src/ep_mfem/fem/geom.cpp: 976)

**Comment by v-dobrev** [comment] 2018-09-18 21:18
If you're getting the same errors when building mfem separately then, judging by the log files, the problem with the Intel compiler seems to be compiler configuration issue. Have you tried building any simple test program that includes `<iomanip>` (the inclusion of this header seemed to be the issue in your original intel.log file)? This is a standard c++98/c++03 header, so you should not need to use a flag to enable c++11.

With the PGI compiler - I think the error message is clear enough - it is an internal compiler error. If I could reproduce the error I'd try to find a workaround - but I cannot reproduce the issue.

**Comment by tsariysk** [comment] 2018-09-18 21:48
I already have a working environment, which is enough to proceed with the pilot program. I'll proceed with the builds  when I have Pgi-18.10, which should be soon. 

I want to thank all of you for the prompt help.
Thanks,
Ted

**Comment by tzanio** [comment] 2018-09-18 23:35
@tsariysk, I'll close this issue for now. Feel free to re-open if you have additional information.

**Closed by tzanio** 2018-09-18 23:35 UTC
Labels: building
