### ISSUE TITLE
Quadrature points fall onto the edge of a simplex

### ISSUE THREAD

**Issue by thorvath12** [mfem/mfem#1548] opened 2020-06-15 16:44 UTC
Hi All,

Recently we have been working with discontinuous source terms in our problems, and we realized some strange behavior for certain integration orders. After a bit of debugging, we found that for the order 7 integration rule on tetrahedrons, some of the integration points are on the faces of the tets. This should not be a problem in general, but when dealing with discontinuous functions, it can cause some troubles.

Then I went a bit further and found that for triangles we have the same issue for orders 11 and 13. Because prisms are tensor products of triangles and segments, I guess the same issue is there for prisms.

We have a workaround (simply avoid these integration orders) but I was wondering if you want to change those integration rules.

I think I found some solutions for triangles for order 13, not for order 11. Also, I cannot find a proper quadrature rule for tets for order 7. According to this page
http://nines.cs.kuleuven.be/research/ecf/mtables.html

there should be another rule with 33 points instead of 31, but I cannot get the thesis or the report the site refers to.

Let me know if you plan to work on this issue any further. As I said, we have a workaround.

Regards
Tamas

**Comment by mlstowell** [comment] 2020-06-16 17:02
Hello, @thorvath12 ,

I don't know much about the history of our integration rule choices so perhaps someone else can speak to that part of this issue.

If integration points on the surface of elements are creating a problem then I assume the discontinuities in your source function are meant to be aligned with element interfaces.  Presumably such integration points occasionally lead to evaluations of your source on the wrong side of these interfaces.  If this is the case then you might consider this an issue caused by round-off errors in the evaluation locations.  Another possible workaround is to rely on element attributes to define regions in which your source is continuous.  Then split your source function into separate pieces which are continuously extended beyond their respective regions.  Finally you use `RestrictedCoefficients` for the sources in each region.  The result will be that each element will only evaluate the coefficient which has been assigned to its region and even if the integration point leads to a physical location slightly outside the element the coefficient will still return a suitable value due to the continuous extension of the source function.

Best wishes,
Mark

**Comment by tzanio** [comment] 2020-06-17 22:21
Tamas, can you clarify a bit more why such integration points are a problem?

We are flexible, but even if we change the simplex rules, we have the same issue with the Lobatto rules for tensor-product elements, and those we certainly want to allow.

Tzanio

**Comment by thorvath12** [comment] 2020-06-18 17:32
Dear Mark and Tzanio,

Yes, our discontinuities are aligned with the element interfaces. The problem is when a quadrature point falls onto the interface we get a wrong evaluation - as the source term is not defined on some of the interfaces. As this problem occurs only with a few quadrature rules, we can do the simples workaround: avoid using those.

I know that changing the quadrature rules would be painful, and maybe it does not even worth it. I just wanted to get your opinion on this. For the Lobatto rules, it is well known that the endpoints are included, however, the simplex rules are not that clear: some rules do include boundary points, some do not.

Tamas

**Comment by tzanio** [comment] 2020-06-20 23:56
Hi Tamas,

My inclination will be not to modify the quadrature rules, but I'd like to understand your use case better first.

I am confused because quadrature points always come with a particular element, and so as long as a function is defined inside the element it should also be defined, by continuity at least, on the boundary. It is very true that the value in a physical location may not be well defined, but the values at any of the quadrature points that correspond to such location will be well defined by the values for the elements these quadrature points belong to.

Can you elaborate what you mean by "the source term is not defined on some of the interfaces"? Is this something that you can potentially handle in your application?

Cheers,
Tzanio

**Comment by aasivas** [comment] 2020-06-28 20:18
Hi @tzanio,

Just to chip in, I believe this maybe actually a big issue. Take a source function f(x,y) = 1 if x<0.5 and 0 if x>=0.5, for example. Assume the mesh is aligned with the discontinuity. If you try to integrate this function with a quadrature point on 0.5, at least on one side the integral will be wrong. In general, this is okay because that is what you accept. There will be some error coming from numerical integration.

However, if you use L2 elements with Gauss-Legendre basis, there is no reason to use closed integration rules. Moreover, one would expect, in such case, for open quadrature rules to be default and with an open Gaussian quadrature rule, the problem above would be avoided completely. On both sides, the value of the integral would be exact. 

I understand your reluctance with changing the quadrature rules, as it may potentially break some codes but I believe for this case there is a semantic discrepancy which, at least, calls for a warning in the documentation.

**Comment by thorvath12** [comment] 2020-06-28 20:43
Sorry, I was busy with some other projects.

The particular problem I am trying to solve with a DG method has a discontinuous source term (something similar to what @aasivas commented, only that the function doesn't have a particular value at x = 0.5). This discontinuity comes from the fact that I have different properties (for example, viscosity) defined on different parts of the domain. Since my mesh is aligned with the discontinuity and the integral corresponding to the source term is an element integral, it shouldn't be necessary to evaluate at the interface.

I have solved this issue by identifying and avoiding the problematic the quadrature rules, so I am okay with not changing the quadrature rules since it would be tedious, but maybe we should have a comment on this in the documentation.

**Comment by tzanio** [comment] 2020-06-28 21:37
Just to clarify, is the following summary correct: 

> You have a `FunctionCoefficient`, `f` that is not defined in certain points on element boundaries and you want to evaluate a `LinearForm` with it, say `DomainLFIntegrator`?

**Comment by thorvath12** [comment] 2020-06-28 23:16
Yes, exactly.

**Comment by tzanio** [comment] 2020-06-29 04:34
Other folks may chime in with better suggestions, but here's what I think.

First, the class `Coefficient` implicitly assumes that the function it represents can be evaluated at every point of every element -- the arguments of `Eval(ElementTransformation &T, const IntegrationPoint &ip)`. Since the `Eval` method can be used for other things, e.g. to interpolate a coefficient in a finite element space, I think it will be better not to break this assumption.

You can handle discontinuous coefficients, with discontinuities aligned with the mesh, simply by using a derived coefficient class that takes the element into account.

For example you can create a class `PWFunctionCoefficient` that distinguishes which branch of `f` to use based on the element attribute. Or you could define a `MyDiscontinuousFunctionCoefficient` which chooses which value to use by checking the location of the element center in the `Eval` function.

What do you think?
Tzanio

**Comment by tzanio** [comment] 2020-07-04 00:35
@v-dobrev also suggested that we could add properties to the quadrature rules, the two most important ones being:

- `PositiveWeights`
- `InteriorPoints`

We can then support different rules for the same order and the user can request rules with specific properties, e.g.

```
IntegrationRule &Get(int GeomType, int Order, int PositiveWeights, int InteriorPoints);
```

Let us know if you'd like to add something like this.

**Comment by aasivas** [comment] 2020-07-04 02:09
Adding properties to the quadrature rules is a good idea. If it is also documented well, that would be great for the user. I am not an expert on quadrature rules, my knowledge is pretty general. Do PositiveWeights and InteriorPoints ever imply or contradict each other? For example, Gauss-Legendre quadrature rules are both open and guaranteed to have positive weights. But I do not know if there are any open rules with mixed weights.

**Comment by tzanio** [comment] 2020-07-04 02:16
> Do PositiveWeights and InteriorPoints ever imply or contradict each other? 

I don't think so in general

> I do not know if there are any open rules with mixed weights.

Some of the simplex rules we use have negative weights -- search for "negative weight" in `fem/intrules.cpp`. This is undesirable since it could lead to e.g. negative norm approximations.

**Comment by thorvath12** [comment] 2020-07-04 02:41
@tzanio Adding something like that would be awesome. Shall we open a pull request or discuss it in more detail here first?

@aasivas there are a few quadrature rules on simplices with mixed weight. (Remember we ran into these when we were calculating convergence rates and we got negative norms.)

**Comment by tzanio** [comment] 2020-07-04 02:49
You can open the PR and we will move the discussion there.

**Comment by benzwick** [comment] 2020-08-02 02:28
The [quadpy](https://github.com/nschloe/quadpy) Python package is quite useful for discovering and comparing different quadrature rules. It also contains references to where the different schemes are derived. For example, see [here](https://github.com/nschloe/quadpy#tetrahedron-t3) for tetrahedrons.

**Comment by tzanio** [comment] 2020-08-02 02:44
> The quadpy Python package is quite useful for discovering and comparing different quadrature rules.

That looks really nice!!

Do you know if properties like positive weights or strictly interior quadrature points are tracked in the package?

**Comment by benzwick** [comment] 2020-08-02 02:56
> Do you know if properties like positive weights or strictly interior quadrature points are tracked in the package?

Not that I know of but I guess it wouldn't be too difficult to add as a new feature. Maybe additional properties in the [QuadratureScheme](https://github.com/nschloe/quadpy/blob/master/quadpy/tn/_helpers.py#L9) base class or as a function/method that checks if all the weights are positive and the points are inside the interval. The latter might be easier to implement because it would only require two functions compared to defining properties for over 1500 quadrature rules!

**Comment by tzanio** [comment] 2020-10-06 23:04
I'll close this issue since there has been no activity in a while. We are still open to a PR for exposing integration rule properties as discussed above!

**Closed by tzanio** 2020-10-06 23:04 UTC
Labels: fem, usage
