### ISSUE TITLE
Is nonlinear newton iteratation initial value always 0 ?

### ISSUE THREAD

**Issue by fanronghong** [mfem/mfem#1421] opened 2020-04-15 01:48 UTC
Hi all,

If I want to give an initial value for a newton iteration, is this the right way by changing `x` in `pnewton_solver->Mult(b, x)`, where `pnewton_solver` is a `PetscNonliearSolver *` ?

**Comment by tzanio** [comment] 2020-04-17 19:57
For mfem's `NewtonSolver` the answer is that `x` always provides the initial guess (this is because the `iterative_mode` in the base `Solver` class is set to `true` by `IterativeSolver` from which `NewtonSolver` inherits).

@stefanozampini can confirm, but this doesn't seem to be the case for `PetscNonliearSolver`.

**Comment by stefanozampini** [comment] 2020-04-17 20:44
`PetscNonlinearSolver` also support nonzero initial guess, see here https://github.com/mfem/mfem/blob/master/linalg/petsc.cpp#L3445.

The `b` vector is the affine part of the nonlinear equation, i.e. you solve F(x) = b, instead of F(x) = 0

**Comment by fanronghong** [comment] 2020-04-18 06:30
Thanks for your reply @tzanio , @stefanozampini ,

Yes, for `NewtonSolver` it is. Actually, I think it is the same for `PetscNonlinearSolver` before. But the below MWE gives a different answer.

The below MWE outputs 
```
norm of initial: 129
in Solve(), l2 norm of x: 129             // OK
in Mult(), l2 norm of x: 0                   // Should be 129 ?
  0 SNES Function norm 3.083152155824e-01 
in GetGradient(), l2 norm of x: 0      // Should be 129 ?
```

The MWE source code: 
```
#include <iostream>
#include "mfem.hpp"
using namespace std;
using namespace mfem;

double u_exact_func_NonlinearPoisson(const Vector& x)
{
    return sin(2*M_PI*x[0]) * sin(2*M_PI*x[1]);
}
// -Laplace u + u^2 = f
double f_exact_func_NonlinearPoisson(const Vector& x)
{
    return 8*M_PI*M_PI*u_exact_func_NonlinearPoisson(x) + u_exact_func_NonlinearPoisson(x) * u_exact_func_NonlinearPoisson(x);
}


// Nonlinear problem F(u)=0, F(u)=-Laplace u + u^2 - f
// Residual: (F(u), v) = (grad(u), grad(v)) + (u^2 - f, v)
// Jacobian: J(du, v; u) = (-Laplace du + 2*u*du, v) = (grad(du), grad(v)) + 2*u*(du, v)
class NLFIntegrator: public NonlinearFormIntegrator
{
private:
    Vector shape;
    Coefficient* f; // 非线性算子F(u)=-Laplace u + u^2 - f
    DenseMatrix dshape, dshapedxt, invdfdx;
    Vector vec, pointflux;

public:
    NLFIntegrator(Coefficient* f_): f(f_) {}

    // 计算当前解的残量
    virtual void AssembleElementVector(const FiniteElement& el,
                                       ElementTransformation& Tr,
                                       const Vector& elfun,
                                       Vector& elvect)
    {
        int dof = el.GetDof();
        int dim = el.GetDim();
        shape.SetSize(dof);
        dshape.SetSize(dof, dim);
        invdfdx.SetSize(dim);
        vec.SetSize(dim);
        pointflux.SetSize(dim);

        elvect.SetSize(dof);
        elvect = 0.0;
        vec = 0.0;

        const IntegrationRule* ir = &IntRules.Get(el.GetGeomType(), 2*el.GetOrder()+Tr.OrderW());

        for (int i=0; i<ir->GetNPoints(); i++) {
            const IntegrationPoint& ip = ir->IntPoint(i);
            el.CalcShape(ip, shape);
            el.CalcDShape(ip, dshape);
            Tr.SetIntPoint(&ip);

            // given u, compute (u^2-f, v)
            double fun_val = (elfun*shape)*(elfun*shape) - (*f).Eval(Tr, ip);
            double w = ip.weight * Tr.Weight() * fun_val;
            add(elvect, w, shape, elvect);

            // given u, compute (grad(u), grad(v))
            CalcAdjugate(Tr.Jacobian(), invdfdx);
            dshape.MultTranspose(elfun, vec);
            invdfdx.MultTranspose(vec, pointflux);
            double ww = ip.weight / Tr.Weight();
            pointflux *= ww;
            invdfdx.Mult(pointflux, vec);
            dshape.AddMult(vec, elvect);
        }
    }

    virtual void AssembleElementGrad(const FiniteElement& el,
                                     ElementTransformation& Tr,
                                     const Vector& elfun,
                                     DenseMatrix& elmat)
    {
        int dof = el.GetDof();
        int dim = el.GetDim();
        dshapedxt.SetSize(dof, dim);
        dshape.SetSize(dof, dim);
        shape.SetSize(dof);
        elmat.SetSize(dof);
        elmat = 0.0;

        const IntegrationRule* ir = &IntRules.Get(el.GetGeomType(), 2*el.GetOrder()+Tr.OrderW());

        for (int i=0; i<ir->GetNPoints(); i++) {
            const IntegrationPoint& ip = ir->IntPoint(i);
            el.CalcShape(ip, shape);
            el.CalcDShape(ip, dshape);
            Tr.SetIntPoint(&ip);

            // compute (grad(du), grad(v))
            double w = ip.weight / Tr.Weight();
            Mult(dshape, Tr.AdjugateJacobian(), dshapedxt);
            AddMult_a_AAt(w, dshapedxt, elmat);

            // compute 2*u*(du,v)
            double fun_val = 2 * (elfun*shape) * ip.weight * Tr.Weight();
            AddMult_a_VVt(fun_val, shape, elmat); // 2*u*(du, v)
        }
    }
};

class PoissonSolver: public Operator
{
protected:
    ParNonlinearForm* N;
    mutable HypreParMatrix* Jacobian;
    Coefficient* f;
    PetscNonlinearSolver* pnewton_solver;

public:
    PoissonSolver(ParNonlinearForm* N_, Coefficient* f_, int size)
            : Operator(size), N(N_), f(f_), Jacobian(NULL)
    {
        pnewton_solver = new PetscNonlinearSolver(MPI_COMM_WORLD, *this);
        pnewton_solver->SetPrintLevel(1);
        pnewton_solver->SetRelTol(1e-8);
        pnewton_solver->SetAbsTol(1e-20);
        pnewton_solver->SetMaxIter(1);
    }

    virtual void Mult(const Vector& x, Vector& y) const
    {
        cout << "in Mult(), l2 norm of x: " << x.Norml2() << endl;
        N->Mult(x, y);
    }

    virtual Operator &GetGradient(const Vector& x) const
    {
        cout << "in GetGradient(), l2 norm of x: " << x.Norml2() << '\n' << endl;
        Jacobian = dynamic_cast<HypreParMatrix*>(&N->GetGradient(x));
        return *Jacobian;
    }

    void Solve(Vector& b, Vector& x)
    {
        cout << "in Solve(), l2 norm of x: " << x.Norml2() << endl;
        pnewton_solver->Mult(b, x);
        cout << endl;
    }
};

int main(int argc, char** argv)
{
    int num_procs, myid;
    MPI_Init(&argc, &argv);
    MPI_Comm_size(MPI_COMM_WORLD, &num_procs);
    MPI_Comm_rank(MPI_COMM_WORLD, &myid);

    MFEMInitializePetsc(NULL,NULL,NULL,NULL);

    Mesh* mesh = new Mesh(8, 8, Element::TRIANGLE, true, 1.0, 1.0);
    ParMesh* pmesh = new ParMesh(MPI_COMM_WORLD, *mesh);
    delete mesh;
    for (int i=0; i<4; i++) pmesh->UniformRefinement();
    int dim = pmesh->Dimension();

    H1_FECollection h1_fec(1, dim);
    ParFiniteElementSpace h1_space(pmesh, &h1_fec);
    int size = h1_space.GetVSize();

    Array<int> ess_tdof_list;
    if (pmesh->bdr_attributes.Size()) {
        Array<int> ess_bdr(pmesh->bdr_attributes.Max());
        ess_bdr = 1; // 所有边界都是Dirichlet
        h1_space.GetEssentialTrueDofs(ess_bdr, ess_tdof_list);
    }

    FunctionCoefficient f_exact_coeff(f_exact_func_NonlinearPoisson);
    FunctionCoefficient u_exact_coeff(u_exact_func_NonlinearPoisson);

    ParNonlinearForm* N = new ParNonlinearForm(&h1_space);
    N->AddDomainIntegrator(new NLFIntegrator(&f_exact_coeff));
    N->SetEssentialTrueDofs(ess_tdof_list);

    PetscParVector* zero = new PetscParVector(MPI_COMM_WORLD, size);
    *zero = 0.0;

    PoissonSolver* poisson_solver = new PoissonSolver(N, &f_exact_coeff, size);
    ParGridFunction uh(&h1_space);
    uh = 1.0;
    cout << "norm of initial: " << uh.Norml2() << endl;
    poisson_solver->Solve(*zero, uh);

    delete poisson_solver;
    MFEMFinalizePetsc();
    MPI_Finalize();
    return 0;
}
```

**Comment by stefanozampini** [comment] 2020-04-19 13:16
Have you read your code? 

```
virtual void Mult(const Vector& x, Vector& y) const
    {
        cout << "in Mult(), l2 norm of x: " << x.Norml2() << endl;
        N->Mult(x, y);
    }

    void Solve(Vector& b, Vector& x)
    {
        cout << "in Solve(), l2 norm of x: " << x.Norml2() << endl;
        pnewton_solver->Mult(b, x);
        cout << endl;
    }
```
`x` is the affine part of the equation for `Mult`. `Solve` uses `y` as starting point.

**Comment by fanronghong** [comment] 2020-04-22 10:52
Thanks for your reply @stefanozampini ,

I make some changes but I don't get the expected answer.
It seems that whatever I give `b` and `x`, the Newton initial value is always 0.0.
The below are the prints for the first Newton iteration
```
initial value l2 norm: 129
in Solve(), l2 norm of b: 258
in Solve(), l2 norm of x: 129
in Mult(), l2 norm of x: 0
in Mult(), l2 norm of y: 0
  0 SNES Function norm 2.580021221804e+02 
in GetGradient(), l2 norm of x: 0
```

Sorry for so many questions.

**Comment by stefanozampini** [comment] 2020-04-22 14:53
If you do not post what you modified, how can I tell you where the issue is?

**Comment by fanronghong** [comment] 2020-04-22 15:09
Sorry about not clear descriptions,

I change the `r.h.s` of nonlinear problem to `2.0` instead of `0.0`.
```
    PetscParVector* two = new PetscParVector(MPI_COMM_WORLD, size);
    *two = 2.0; // set to2.0, instead of 0.0

    PoissonSolver* poisson_solver = new PoissonSolver(N, &f_exact_coeff, size);
    ParGridFunction uh(&h1_space);
    uh = 1.0;
    cout << "initial value l2 norm: " << uh.Norml2() << endl;

    poisson_solver->Solve(*two, uh);
```

And I add more prints in `Solve()`, `Mult()`and `GetGradient()`.
```
    virtual void Mult(const Vector& x, Vector& y) const
    {
        cout << "in Mult(), l2 norm of x: " << x.Norml2() << endl;
        cout << "in Mult(), l2 norm of y: " << y.Norml2() << endl;
        N->Mult(x, y);
    }

    virtual Operator &GetGradient(const Vector& x) const
    {
        cout << "in GetGradient(), l2 norm of x: " << x.Norml2() << '\n' << endl;
        Jacobian = dynamic_cast<HypreParMatrix*>(&N->GetGradient(x));
        return *Jacobian;
    }

    void Solve(Vector& b, Vector& x)
    {
        cout << "in Solve(), l2 norm of b: " << b.Norml2() << endl;
        cout << "in Solve(), l2 norm of x: " << x.Norml2() << endl;
        pnewton_solver->Mult(b, x);
        cout << endl;
    }
```

**Comment by stefanozampini** [comment] 2020-04-22 15:24
If you do not post the entire code, I cannot compile and run it.
Now I can just guess. Also, can you start fresh, and post a simpler MWE without all these functions? E.g. by solving x^3 - 1 = 0? or any other simple nonlinear equation you like?

**Comment by fanronghong** [comment] 2020-04-22 15:27
In my second post, the MWE is the entire code. You can compile it and run it.
And its comments explain the nonlinear problem. Thanks again.

**Comment by stefanozampini** [comment] 2020-04-22 15:29
I have already told you what was wrong in the first MWE. Now you are saying you still have the problem after you have modified it. I cannot answer without seeing the modifications.

**Comment by stefanozampini** [comment] 2020-04-22 15:32
Also, did you set iterative_mode to true?

**Comment by fanronghong** [comment] 2020-04-22 15:36
Oh, yes, I just forget setting iterative_mode to true. I get my expected result.
I am so sorry for this mistake and thank you for your time @stefanozampini

**Comment by stefanozampini** [comment] 2020-04-22 15:47
glad it works, I'm closing the issue

**Closed** 2020-04-22 15:47 UTC
Labels: linalg, usage
