### ISSUE TITLE
Results are not the same for parallel code and Serial code

### ISSUE THREAD

**Issue by diliu1994** [mfem/mfem#1565] opened 2020-06-22 01:52 UTC
Hi All,

I have modified the ex10 and ex10p code for solving the problem of the bilayer beam bending with 2 different Neo-Hookean materials. And one of the material is with the time dependent expansion coefficient. However, I have met the problem that the results of the parallel code and the serial code are not the same. Could anyone help me solve this problem? The attached files are the modified cpp codes and the input file.
[ex10_expansion_subdomain.cpp.txt](https://github.com/mfem/mfem/files/4810757/ex10_expansion_subdomain.cpp.txt)
[ex10p_expansion_subdomain.cpp.txt](https://github.com/mfem/mfem/files/4810760/ex10p_expansion_subdomain.cpp.txt)
[multi-layer-beam.msh.txt](https://github.com/mfem/mfem/files/4810763/multi-layer-beam.msh.txt)

**Comment by camierjs** [comment] 2020-06-22 16:19
Hi @diliu1994, could you provide as well the command lines you are working with for us to reproduce the issue?
Thank you.

**Comment by diliu1994** [comment] 2020-06-22 18:07
Hi @camierjs 

Thanks for reminding me. The command line for the serial code is: 
./ex10_expansion_subdomain -m ../data/multi-layer-beam.msh -s 2 -r 1 -o 2 -tf 200 -dt 0.5
The command line for the parallel code is:
mpirun -np 16 ./ex10p_expansion_subdomain -m ../data/multi-layer-beam.msh -s 2 -rs 1 -tf 200 -dt 0.5


Best regards,
Di

**Comment by tengzhang48** [comment] 2020-06-25 02:23
Hi @psocratis ,

I am working with @diliu1994 on this example. I tried simulation on SDSC Comet cluster and found the results are different from my Mac. Basically, the errors from the first iteration are very small (1e-9), which gives almost 0 displacements at the end. This is not correct. However, I can get the right answer on my Mac computer. This may be due to the compiler, and I think gcc is used on Comet but can check this more carefully. I feel the code on Comet does not read the material properties correctly.

Another thing is that I just check the ex2p code on Comet and the result is the same as the benchmark shown on the website. So the definition of the two material properties should be ok. I also did a modification to the ex10p a few weeks before to include expansion for a single material and the code works well on Comet. Therefore, I feel the error may be due to the way of passing PWConstCoefficient vector to the HyperelasticOperator

"Vector g(mesh->attributes.Max()); // Initial expansion vector
   g = 1.0;
   PWConstCoefficient g_func(g);
   HyperelasticOperator oper(fespace, ess_bdr, visc, mu_func, K_func, g_func);"

Will different settings are required for gcc and clang?

Thanks,
Teng

**Comment by tengzhang48** [comment] 2020-06-25 02:46
Hello,

For this example, we would like to assign a time dependent expansion (a linear function of time). So we update the g function value and redefine HyperelasticOperator in the loop of each time increment. 
"for (int ti = 1; !last_step; ti++)
   {
      double dt_real = min(dt, t_final - t);
	  // update the expansion with time
      g(0) = 1.0 + 0.002*t;
      HyperelasticOperator oper(fespace, ess_bdr, visc, mu_func, K_func, g_func);
"
Is this a possible reason for not seeing material parameters updated?

Our goal is to dynamically update the expansion. Is this the right way to do?

Also, I just checked the code on my Mac and found it only works when I wrote
 g(2) = 1.0 + 0.002*t;

If I put 0 or 1 there, I will not see the update of the parameters. But we only have two attributes.

Thanks,
Teng

**Comment by tengzhang48** [comment] 2020-06-25 15:19
Hello,

I commented the command in the for loop of the time integration and assign a different g value for the two materials at the beginning. Please see the modified code.
And I can see the beam bending deformation (attached image). Therefore, the question should be how can be assign a time-dependent material properties to an ode operator? 

Best,
Teng
<img width="1191" alt="Screen Shot 2020-06-25 at 11 07 13 AM" src="https://user-images.githubusercontent.com/58086633/85747813-9c9c4e00-b6d5-11ea-8f31-e6ab39b92893.png">

[ex10p_expansion_subdomain_1.cpp.txt](https://github.com/mfem/mfem/files/4832228/ex10p_expansion_subdomain_1.cpp.txt)

**Comment by psocratis** [comment] 2020-06-25 18:04
Hi @tengzhang48 and @diliu1994 , 

The way it is done now will not do the work... you are creating a new operator inside the loop but the operator of the ODE solver is not updated. Since the only thing you need is updating the g_func with respect to time you can add       
g_func.UpdateConstants(g); right after setting them inside the loop. This should look like this: 

````c++
for (int ti = 1; !last_step; ti++)
   {
      double dt_real = min(dt, t_final - t);
      // update the expansion with time
      g(0) = 1.0 + 0.002*t;
      g_func.UpdateConstants(g);

      ode_solver->Step(vx, t, dt_real);

      last_step = (t >= t_final - 1e-8*dt);

      if (last_step || (ti % vis_steps) == 0)
      {
         v_gf.SetFromTrueVector(); x_gf.SetFromTrueVector();

         double ee = oper.ElasticEnergy(x_gf);
         double ke = oper.KineticEnergy(v_gf);
 
         .......

````

Can you try this and let us know if it worked? I tried it on my mac and I see the updates. 

I presume this issue is no longer parallel vs serial run inconsistency right? 

Thanks, 

Socratis

**Comment by diliu1994** [comment] 2020-06-25 18:58
Hi @psocratis 

I think now it works and I have got the result for at t = 200
![result](https://user-images.githubusercontent.com/61118273/85781892-2c50f500-b6f4-11ea-97e0-3c6036c0f3c0.png)

And this issue is no longer about parallel vs serial run. It is just how to make a time dependent expansion coefficient.

Thanks,
Di

**Comment by psocratis** [comment] 2020-06-25 19:07
Hi @diliu1994 , 

That's great! I'm glad it works. I closing this issue now. Feel free to reopen it if anything else comes up. 

Socratis

**Closed by psocratis** 2020-06-25 19:07 UTC
Labels: examples & miniapps, fem, usage
