### ISSUE TITLE
Potential bug when manipulating Vectors?

### ISSUE THREAD

**Issue by varchasgopalaswamy** [mfem/mfem#3029] opened 2022-05-20 14:57 UTC
Hi,

I noticed this behavior when trying to write a new Riemann solver. I'm using GCC 9.1.0 with MFEM 4.4 installed through spack. Basically, if you add two vectors and assign to a third, you get a compiler error (fair enough). But if you subtract two vectors, you get no compiler error but end up getting a wrong result. 

```
Vector A(5), B(5), C(5); 
// Set some values in A and B 
for (int i = 0; i < 5; i++){
        A(i) = i;
        B(i) = i*i;
    }

// error: no match for ‘operator+’ (operand types are ‘mfem::Vector’ and ‘mfem::Vector’)
C = A + B; 

// No compiler error, but incorrect result 
C = A - B;
C.Print(); 
// Prints out -6 -6 -6 -6 -6

// No compiler error and correct result with expected behavior (i.e. no change in A)
C = A; 
C -= B; 
A.Print();
// 0 1 2 3 4
C.Print(); 
// 0 0 -2 -6 -12
```

**Comment by pazner** [comment] 2022-05-20 18:01
Hi @varchasgopalaswamy,

In general, I wouldn't recommend using expressions like `C = A - B;` with `Vector`s in MFEM. That this even compiles is actually because `A` and `B` are implicitly cast to `double *`, and so `A - B` becomes a difference of pointers (integer type), which is then promoted to `double`, and `C` is given that constant value.

It's probably better to work with explicit `for` loops.

**Comment by termi-official** [comment] 2022-05-20 18:02
As this is a very technical problem, let me quickly explain what the issue is. The vector class overloaded the indirection operator (i.e. operator*double()). Since the subtraction operator is not overloaded, the expression "Vector - Vector" is resolved by the compiler to the pointer arithmetic expression "double* - double*". Note that expressions of type "double* + double*" are not valid pointer arithmetic expressions (as explained in §8.5.6 of the C++ standard). This pointer difference the triggers the overloaded assignment operator on Vector.

An MWE exhibiting this issue is given by:

```
#include <iostream>

struct A {
    double data;
    std::string me;

    inline double operator=(double val)
    {
        data = val;
        std::cout << "Assigning to " << me << "(" << this << ")" << std::endl;
        return data;
    }

    inline operator double *()
    {
        std::cout << "Dereferencing to " << me << "(" << this << ")" << std::endl;
        return &data;
    }
};

int main()
{
    A a1, a2, a3;
    a1.me = "1";
    a2.me = "2";
    a3.me = "3";

    a1.data = 1.0;
    a2.data = 2.0;

    a3 = a2 - a1;

    return a3.data;
}
```

**Comment by tzanio** [comment] 2022-05-20 18:17
There are also helper functions like

```
 /// Set v = v1 + alpha * v2.
void add(const Vector &v1, double alpha, const Vector &v2, Vector &v);
```

**Comment by jandrej** [comment] 2022-05-20 18:25
This indicates that we should overload `operator-` with a static_assert so this fails at compile time, right?

**Comment by varchasgopalaswamy** [comment] 2022-05-20 18:34
Got it! Thanks!

**Comment by pazner** [comment] 2022-05-20 18:36
> This indicates that we should overload `operator-` with a static_assert so this fails at compile time, right?

We could, an implementation would look like:
```c++
template <typename...>
struct always_false { static constexpr bool value = false; };

template <typename... Ts>
Vector &operator-(const Vector &v)
{ static_assert(always_false<Ts...>::value, "operator- not supported for Vector."); }
```

I don't know if there are other such "dangerous" operators.

**Comment by tzanio** [comment] 2022-06-08 15:15
Discussion about disabling `operator-` for `Vector` continued in https://github.com/mfem/mfem/pull/3064

**Comment by samuelpmishLLNL** [comment] 2022-08-30 18:05
Serac is upgrading to a new mfem version and hitting a problem related to this change. We wrote some tools to enable `mfem::Vector` to support arithmetic operators through expression templates, but now the implementation has been broken by mfem's deletion of `operator-`.

I feel like the discussion in this thread has missed the point: the problem is not that a vector class admits `operator-`, it's that `mfem::Vector` is implicitly convertible to a `double *`. Implicit conversions are notoriously dangerous operations in C++, Google's style guide [on the subject](https://google.github.io/styleguide/cppguide.html#Implicit_Conversions) doesn't mince words:

> Do not define implicit conversions.

Is it possible to reconsider this change? Removing the implicit conversion to `double *` seems like the more accurate decision.

**Comment by white238** [comment] 2022-08-30 22:20
If you do end up removing the implicit conversion, it should be safe to add back the `operator-` and `operator+` that is now explicitily deleted.

**Comment by samuelpmishLLNL** [comment] 2022-08-30 22:48
> If you do end up removing the implicit conversion, it should be safe to add back the operator- and operator+ that is now explicitily deleted.

Part of the reason for this issue is that `mfem::Vector` surprisingly doesn't implement `operator+` or `operator-` at all. That, combined with the fact that `mfem::Vector` implicitly converts convertible to `double *`  leads to the especially troubling errors like the one in this issue where perfectly reasonable mathematical expressions compile successfully, yet produce nonsense:

```
// No compiler error, but incorrect result 
C = A - B;
```

If there had been an implementation of vector addition and subtraction, this issue would have been avoided as well, but it is still advisable to get rid of the dangerous implicit conversion to a raw pointer. `mfem::Array` also [defines implicit conversions](https://github.com/mfem/mfem/blob/master/general/array.hpp#L105-L109) that should be removed or made `explicit`.

**Comment by samuelpmishLLNL** [comment] 2022-08-30 23:27
It's also worth noting that PR #3064 doesn't actually stop this from happening (spotted by @white238):

https://godbolt.org/z/7PEz6aqYc

**Comment by pazner** [comment] 2022-08-31 03:43
Regarding the implicit conversions, I think there is generally agreement that it would be better not to have them, but removing them could also break existing user code, so perhaps they should be deprecated first, and then removed.

The issue of `operator+` and `operator-` is both related to the implicit conversions and also somewhat separate. The motivation for deleting `operator-` is exactly the case of the valid mathematical expressions that compile but produce nonsense (because of the implicit conversion to pointers, and then interpreting `A - B` as pointer arithmetic). Deleting it turns this into a compile-time error.

However, the motivation for not implementing them in the first place is because the straightforward implementation will lead to temporaries and other inefficiencies, and we want to direct users towards more efficient in-place functions. Expression templates are one way of making this less inefficient, and this is a topic that has been brought up in the past, but I don't believe there is a plan to supports expression templates in MFEM. Generally, the MFEM linear algebra objects aren't intended for writing high-level mathematical expressions the way that e.g. the Eigen or Armadillo libraries are, the design is intended to be lower-level and more explicit.



> It's also worth noting that PR #3064 doesn't actually stop this from happening (spotted by @white238):
> 
> https://godbolt.org/z/7PEz6aqYc

This is a good catch, I believe if that `const` version of `operator-` is also deleted then this becomes a compile-time error too.

**Comment by samuelpmishLLNL** [comment] 2022-08-31 17:39
> However, the motivation for not implementing them in the first place is because the [naive] implementation will lead to temporaries and other inefficiencies, and we want to direct users towards more efficient in-place functions.

The existence of one poor implementation of `operator-` shouldn't justify banning all possible implementations of `operator-`, but that's effectively what #3064 is doing (inadvertently, I imagine).

Serac implements the arithmetic operators that are missing from `mfem::Vector`,  but #3064 explicitly `= delete`ing them just breaks our implementation completely.

**Comment by tzanio** [comment] 2022-08-31 21:01
Thanks for this report @samuelpmishLLNL, the effect of this change was indeed inadvertent and in hindsight we should have considered the possible implications of deleting the operators more carefully.

Here is a possible solution

1. We list the `double *` conversion as deprecated and remove it in future MFEM versions. This is what @pazner meant above. The reason for not removing it right away is that this too can have implications for some of our users.

2. We either (A) undo https://github.com/mfem/mfem/pull/3064 or (B) add a simple implementation with a warning about the performance.

What do you guys think?

I am personally leaning towards 1 + 2A.

**Comment by samuelpmishLLNL** [comment] 2022-08-31 21:38
Those options sound great.

I'd vote for 1 + 2B, following the principle of least surprise: users (like the one that posted this issue) will expect those operators to be defined. Having implementations of
```cpp
Vector Vector::operator*(double)
Vector Vector::operator/(double)
Vector Vector::operator+(Vector)
Vector Vector::operator-(Vector)
```
makes it much more natural to transcribe mathematical expressions into code and back, and performance-critical regions are still free to use separate optimized routines where needed.

**Comment by tzanio** [comment] 2022-08-31 21:43
Will 2B work for you? i.e. if we include a simple implementation, you will replace it with the expression templated one in your code?

Or are you proposing 2C, where the implementation we add is not a simple one, but the one from Serac?

**Comment by samuelpmishLLNL** [comment] 2022-08-31 21:51
2B would be great for serac. If mfem provides those operator overloads, we would adopt them immediately and probably remove the expression template implementation.

**Comment by tzanio** [comment] 2022-09-07 00:25
Discussion continued in https://github.com/mfem/mfem/pull/3194, which implements 1+2A

**Closed by tzanio** 2022-09-07 00:25 UTC
Labels: usage, linalg
