### ISSUE TITLE
How to realize the Robin Boundary condition on pde

### ISSUE THREAD

**Issue by jsfeng-fudan** [mfem/mfem#3121] opened 2022-07-29 02:04 UTC
I have one 1d ode :
-y' '[x] = 3 in domain  [0,1], with Robin boundary
y'[0]-y[0] = -1 and y'[1]+y[1] = 1;
I tried to solve this problem using mfem library. but I can not arrive at correct solution.
The correct solution is:
![图片](https://user-images.githubusercontent.com/101965017/181667363-0127ad29-4ac6-4ba7-a026-28644366c583.png)
my solution is:

![图片](https://user-images.githubusercontent.com/101965017/181667438-58538b23-947e-40ca-b4ec-46ad2a4c8572.png)
I post my code for enforce the Robin boundary ..

    rbc_bdr = 1;
    fespace.GetEssentialTrueDofs(rbc_bdr, ess_tdof_list);
   
    double rbc_a_val1 = -1.0; // for left endpoint
    double rbc_b_val1 = -1.0; 
    double rbc_a_val2 = 1.0;  // for right endpoint
    double rbc_b_val2 = 1.0; 
    ConstantCoefficient rbc_a_coeff1(rbc_a_val1);// entering a matrix
    ConstantCoefficient rbc_a_coeff2(rbc_a_val2);// entering a matrix
    ConstantCoefficient rbc_b_coeff1(rbc_b_val1); // entering b linear form
    ConstantCoefficient rbc_b_coeff2(rbc_b_val2); // entering b linear form           
    b.AddDomainIntegrator(new DomainLFIntegrator(f_src));
    // key steps: add B.C. into linear system
    // Add Robin BCs n.(matCoef Grad u) + rbcACoef u = rbcBCoef on the boundary
    // // marked in the rbc_marker array.
    // left
    rbc_bdr = 0;
    rbc_bdr[0] =1 ;
    b.AddBoundaryIntegrator(new BoundaryLFIntegrator(rbc_b_coeff1), rbc_bdr);
    rbc_bdr = 0;
    rbc_bdr[1] =1 ;
    b.AddBoundaryIntegrator(new BoundaryLFIntegrator(rbc_b_coeff2), rbc_bdr);                                   
    b.Assemble();
    //getchar();
    a.AddDomainIntegrator( new DiffusionIntegrator(one));
    // // Add Robin BCs n.(matCoef grad u) + rbcACoef u = rbcBCoef on the boundary
    // // marked in the rbc_marker array.
    rbc_bdr = 0;
    rbc_bdr[0] = 1;
    a.AddBoundaryIntegrator(new MassIntegrator(rbc_a_coeff1), rbc_bdr);
    rbc_bdr = 0;
    rbc_bdr[1] = 1;
    a.AddBoundaryIntegrator(new MassIntegrator(rbc_a_coeff2), rbc_bdr);       
    cout << a.Size() << endl;
    a.Assemble();

can anyone help to solve this problem

**Comment by psocratis** [comment] 2022-07-29 10:04
Hi @jsfeng-fudan, 

It seems you are imposing essential BC on the two ends. This is caused by the lines 
````cpp
rbc_bdr = 1;
fespace.GetEssentialTrueDofs(rbc_bdr, ess_tdof_list);
````
Since both ends of the domain have Neumann BC, the `ess_tdof_list` should remain empty, 

For convenience here is a simple implementation of your example

````cpp

#include "mfem.hpp"
using namespace std;
using namespace mfem;

double y_exact(const Vector & x)
{
   return -3.0*x(0)*x(0)/2.0 + 3.0*x(0)/2.0 + 5.0/2.0;
}

int main(int argc, char *argv[])
{

   int order = 1;
   double sx = 1.0;
   Mesh mesh = Mesh::MakeCartesian1D(10, sx);

   H1_FECollection fec(order, mesh.Dimension());
   FiniteElementSpace fespace(&mesh, &fec);

   cout << "Number of finite element unknowns: " << fespace.GetTrueVSize() << endl;

   Array<int> ess_tdof_list; // should remain empty
   Array<int> newmann_bdr0;
   Array<int> newmann_bdr1;
   if( mesh.bdr_attributes.Size())
   {
      newmann_bdr1.SetSize(mesh.bdr_attributes.Max());
      newmann_bdr0.SetSize(mesh.bdr_attributes.Max());
      newmann_bdr0[0] = 1;
      newmann_bdr0[1] = 0;
      newmann_bdr1[0] = 0;
      newmann_bdr1[1] = 1;
   }
   LinearForm b(&fespace);
   ConstantCoefficient three(3.0);
   ConstantCoefficient one(1.0);
   ConstantCoefficient negone(-1.0);

   b.AddDomainIntegrator(new DomainLFIntegrator(three));
   b.AddBoundaryIntegrator(new BoundaryLFIntegrator(one),newmann_bdr0);
   b.AddBoundaryIntegrator(new BoundaryLFIntegrator(one),newmann_bdr1);
   b.Assemble();

   GridFunction x(&fespace); 
   x = 0.0;

   BilinearForm a(&fespace);
   a.AddDomainIntegrator(new DiffusionIntegrator(one));
   a.AddBoundaryIntegrator(new MassIntegrator(one),newmann_bdr0);
   a.AddBoundaryIntegrator(new MassIntegrator(one),newmann_bdr1);
   a.Assemble();

   OperatorPtr A;
   Vector B, X;
   a.FormLinearSystem(ess_tdof_list, x, b, A, X, B);

   cout << "Size of linear system : " << A->Height() << endl;

   GSSmoother M( (SparseMatrix&) (*A));

   PCG(*A,M,B,X,1, 200, 1e-12,0.0);
   a.RecoverFEMSolution(X,b,x);

   char vishost[] = "localhost";
   int  visport   = 19916;
   socketstream sol_sock(vishost, visport);
   sol_sock.precision(8);
   sol_sock << "solution\n" << mesh << x << flush;

   // exact solution
   GridFunction y_ex(&fespace);
   FunctionCoefficient Ex(y_exact);
   y_ex.ProjectCoefficient(Ex);

   socketstream exact_sock(vishost, visport);
   exact_sock.precision(8);
   exact_sock << "solution\n" << mesh << y_ex << flush;

   return 0;
}

````

Best,

Socratis

**Comment by jsfeng-fudan** [comment] 2022-07-29 11:08
@psocratis  Thank you very much.  With your help,  now I can obtain the correct solution. But why we perform the same  boundary integrator for b at boundary x = 0 and x = 1, as well as boundary Mass integrator for a at boundary x = 0 and x = 1. My B.C. is different at the two endpoints x =0 and x = 1.

**Comment by psocratis** [comment] 2022-07-29 11:15
> @psocratis Thank you very much. With your help, now I can obtain the correct solution. But why we perform the same boundary integrator for b at boundary x = 0 and x = 1, as well as boundary Mass integrator for a at boundary x = 0 and x = 1. My B.C. is different at the two endpoints x =0 and x = 1.

Given your BCs, if you work out the integration by parts on paper, the boundary terms that come out are as the ones in the code above. 

Best, 

Socratis

**Comment by jsfeng-fudan** [comment] 2022-07-29 11:39
Okay. I try to derive the weak form by hands.

**Comment by jsfeng-fudan** [comment] 2022-07-29 12:13
@psocratis  Thank you again . you are right for x = 0, which is low bound integration.
![图片](https://user-images.githubusercontent.com/101965017/181755821-832377b8-be25-43da-836e-d70790f8ce80.png)

**Comment by psocratis** [comment] 2022-07-29 13:01
Cool! I am closing this now. Feel free to reach out if anything else comes up.

**Comment by jsfeng-fudan** [comment] 2022-08-01 09:45
@psocratis  Hi, I have another problem.  
For time-dependent PDE,  where can I find the basic principle for weak form of PDE.  Since there are different methods for time
discretization.   As the example.9 shows the realization of DG Advection problem.   In the code, the explanation is

/** A time-dependent operator for the right-hand side of the ODE. The DG weak
    form of du/dt = -v.grad(u) is M du/dt = K u + b, where M and K are the mass
    and advection matrices, and b describes the flow on the boundary. This can
    be written as a general ODE, du/dt = M^{-1} (K u + b), and this class is
    used to evaluate the right-hand side. */

I can not grasp the bilinear form ( M and K)  from weak form with Galarkin method.
Can you give me some clues?

Thank you!

**Comment by jsfeng-fudan** [comment] 2022-08-06 03:46
@psocratis  Hi, I struggle to derive the weak form of advection (shown in Example 9). 
I derive the formalism above advection equation.  I post it .

![图片](https://user-images.githubusercontent.com/101965017/183232253-254667a9-dae5-4955-a356-6da297e44efa.png)
![图片](https://user-images.githubusercontent.com/101965017/183232273-e7efb553-8cd4-43f0-ba43-01bec951fa74.png)

in the code .
============================================================
   m.AddDomainIntegrator(new MassIntegrator); // mass integrator of domain : M
   constexpr double alpha = -1.0;
   k.AddDomainIntegrator(new ConvectionIntegrator(velocity, alpha)); //  stiffness integrator fo domain : K
   k.AddInteriorFaceIntegrator(
      new NonconservativeDGTraceIntegrator(velocity, alpha));
   k.AddBdrFaceIntegrator(
      new NonconservativeDGTraceIntegrator(velocity, alpha));

   LinearForm b(&fes);
   b.AddBdrFaceIntegrator(
      new BoundaryFlowIntegrator(inflow, velocity, alpha));
==============================================
why we need  AddInteriorFaceIntegrator and AddBdrFaceIntegrator?

**Comment by jsfeng-fudan** [comment] 2022-08-09 16:24
@psocratis Hi,  I have another problem about 1d PDE.
the PDE is given by:
-y''[x] + x y'[x] + y[x] = 2x;
Dirichlet B.C. reads 
y[0] = 1;
y[1] = 3;
The FE solution is different from exact solution as shown below:
![图片](https://user-images.githubusercontent.com/101965017/183705354-50f05318-77ff-4c9d-a870-fc516b383dc1.png)


I  post the key code :
=======================================

        double b_coff = 1.0;
        cout << "we solve pde -y''[x] + a_coff y'[x] + b_coff y[x] = f[x], with y[0] = 1, y[1] =3" << endl;
       cout << "a_coff = x" << endl;
        cout << "b_coff = " << setw(6) << b_coff << endl; 
        cout << "f[x] = 2 x " << endl;
        cout << "the boundary condition is Dirichlet, we must set essential B.C." << endl;
        dbc_bdr = 1;
        fespace.GetEssentialTrueDofs(dbc_bdr, ess_tdof_list);
       
        double dbc_val1 = 1.0;
        double dbc_val2 = 3.0;
        ConstantCoefficient dbc_coeff1(dbc_val1);
        ConstantCoefficient dbc_coeff2(dbc_val2);

        // set left side Dirichlet B.C.
        dbc_bdr = 0;
        dbc_bdr[0] = 1;
        x.ProjectBdrCoefficient(dbc_coeff1, dbc_bdr);
        // set right side Dirichlet B.C.        
        dbc_bdr = 0;
        dbc_bdr[1] = 1;
        x.ProjectBdrCoefficient(dbc_coeff2, dbc_bdr);
        FunctionCoefficient  rhs(f_fun);
        b.AddDomainIntegrator(new DomainLFIntegrator(rhs));
        b.Assemble();
        // bilinear a, containing three terms
        // first term :-y'', which include biliear term a1 =(u,v) and boundary   
        // 
        a.AddDomainIntegrator( new DiffusionIntegrator(one));
        // second term : x y'
        //Coefficient *a1 = new ConstantCoefficient(a_coff);
        FunctionCoefficient *a1 = new FunctionCoefficient(lam_fun);
        a.AddDomainIntegrator( new MixedScalarWeakDerivativeIntegrator(*a1));
        // therd term : y
        Coefficient *b1 = new ConstantCoefficient(b_coff);
        a.AddDomainIntegrator( new MixedScalarMassIntegrator(*b1));
        cout << a.Size() << endl;
        a.Assemble();

**Comment by jsfeng-fudan** [comment] 2022-08-09 16:25
where the lam_fun is

double lam_fun(const Vector &x)
{
        return x(0);
}

**Comment by psocratis** [comment] 2022-08-10 11:37
> @psocratis Hi, I have another problem. For time-dependent PDE, where can I find the basic principle for weak form of PDE. Since there are different methods for time discretization. As the example.9 shows the realization of DG Advection problem. In the code, the explanation is
> 
> /** A time-dependent operator for the right-hand side of the ODE. The DG weak form of du/dt = -v.grad(u) is M du/dt = K u + b, where M and K are the mass and advection matrices, and b describes the flow on the boundary. This can be written as a general ODE, du/dt = M^{-1} (K u + b), and this class is used to evaluate the right-hand side. */
> 
> I can not grasp the bilinear form ( M and K) from weak form with Galarkin method. Can you give me some clues?
> 
> Thank you!

hi @jsfeng-fudan, Please see https://github.com/mfem/mfem/issues/3011 for a related issue. I think you can find what you are asking for there. I also encourage you to open a new issue (and not continue posting in this issue) for unrelated topics to the original issue.

**Comment by psocratis** [comment] 2022-08-10 11:48
@jsfeng-fudan, 

Since you know the exact solution, you can read the boundary data from a single coefficient. You don't need to separate the two endpoints (you could but you don't have to).  

You would need a function for the exact, one for the rhs data and one for the coefficient of the second term. 

````cpp
double y_exact(const Vector & x)
{
   double a = x(0)*x(0)/2.0;
   double b = erf(x(0)/sqrt(2));
   double c = (sqrt(exp(1)) - 2.0)*exp((x(0)*x(0)-1.0)/2.0) * b;
   return -c/erf(1.0/sqrt(2)) + exp(a) + x(0);
}

double rhs_func(const Vector & x)
{
   return 2.0 * x(0);
}

double coeff_func(const Vector & x)
{
   return x(0);
}
````
If you don't want to use the exact, you can always define a function that returns `1.0` on the left end point and `3.0` on the right one. For the bilinear and linear forms you would need something like this 

````cpp
   Array<int> ess_tdof_list; 
   Array<int> ess_bdr; 
   if( mesh.bdr_attributes.Size())
   {
      ess_bdr.SetSize(mesh.bdr_attributes.Max());
      ess_bdr = 1;
      fespace.GetEssentialTrueDofs(ess_bdr, ess_tdof_list);
   }

   LinearForm b(&fespace);
   FunctionCoefficient f(rhs_func); 
   b.AddDomainIntegrator(new DomainLFIntegrator(f));
   b.Assemble();

   FunctionCoefficient y_ex_coeff(y_exact);

   GridFunction x(&fespace); 
   x = 0.0;
   x.ProjectBdrCoefficient(y_ex_coeff,ess_bdr);

   FunctionCoefficient c1(coeff_func); // coefficient of the second term
   ConstantCoefficient one(1.0); 

   BilinearForm a(&fespace);
   a.AddDomainIntegrator(new DiffusionIntegrator(one));
   a.AddDomainIntegrator(new DerivativeIntegrator(c1,0));
   a.AddDomainIntegrator(new MassIntegrator(one));
   a.Assemble();
````
`Mixed` integrators are not appropriate here. These are meant for bilinear forms which involve different types of trial and test `FiniteElementSpace`. In your example trial and test spaces are H1. 

I've tested the above and I do get the exact solution. 

Best,

Socratis

**Comment by jsfeng-fudan** [comment] 2022-08-11 05:13
@psocratis  Hi, thank you.

Here,  the  class DerivativeIntegrator :

======================
/// Class for integrating (Q D_i(u), v); u and v are scalars
class DerivativeIntegrator : public BilinearFormIntegrator
{
protected:
   Coefficient* Q;

private:
   int xi;
   DenseMatrix dshape, dshapedxt, invdfdx;
   Vector shape, dshapedxi;

public:
   DerivativeIntegrator(Coefficient &q, int i) : Q(&q), xi(i) { }
   virtual void AssembleElementMatrix(const FiniteElement &el,
                                      ElementTransformation &Trans,
                                      DenseMatrix &elmat)
   { AssembleElementMatrix2(el,el,Trans,elmat); }
   virtual void AssembleElementMatrix2(const FiniteElement &trial_fe,
                                       const FiniteElement &test_fe,
                                       ElementTransformation &Trans,
                                       DenseMatrix &elmat);
};
======================
the index i (here, you set i = 0)  means ?

now, I can arrive at right solution.



Best,

J.S. Feng

**Comment by psocratis** [comment] 2022-08-16 23:54
@jsfeng-fudan, 

The index `i` refers to which component you are taking the derivative. In the 1D case there is only 1 component, so `i=0`. 

Best, 

Socratis

**Closed by psocratis** 2022-08-16 23:54 UTC
Labels: usage, fem
