### ISSUE TITLE
read vtu mesh

### ISSUE THREAD

**Issue by ChaoW95** [mfem/mfem#2563] opened 2021-09-23 03:58 UTC
[origin_mesh_tri.zip](https://github.com/mfem/mfem/files/7214935/origin_mesh_tri.zip)
I have a .vtu mesh file that contains triangular shell elements.
I can view this file in ParaView.
However, when I try to load this file into MFEM with the following code:
`Mesh *mesh = new Mesh(mesh_file1, 1, 1);`
I got the following error:
`Verification failed: (faces_info[i].Elem2No < 0 || faces_info[i].Elem2Inf%2 != 0) is false: 
 --> Invalid mesh topology. Interior face with incompatible orientations.
 ... in function: virtual void mfem::Mesh::Finalize(bool, bool)
 ... in file: \FEM\mfem-master\mesh\mesh.cpp:2669
`

I was wondering how can I fix this error?
Any help would be appreciated!

**Comment by pazner** [comment] 2021-09-23 20:18
This may be caused by the same issue as #2547 and will be fixed by #2566. Can you try with that branch and see if it works for you? It appears to fix the issue for me.

![GLVis_s01](https://user-images.githubusercontent.com/11493037/134577887-a8b4c777-ab61-4b90-b422-e808e74915da.png)

**Comment by tzanio** [comment] 2021-09-26 20:38
Discussion continued in https://github.com/mfem/mfem/pull/2566

**Closed by tzanio** 2021-09-26 20:38 UTC
Labels: bug, mesh
