### ISSUE TITLE
Compiling with cuda-unsupported compiler

### ISSUE THREAD

**Issue by VictorEijkhout** [mfem/mfem#4527] opened 2024-09-30 22:36 UTC
Intel 24 is too new. Oh dear.

```
cmake
    -D CMAKE_INSTALL_PREFIX=/work/00434/eijkhout/mfem/installation-mfem-4.7-milan-intel24-impi21.12
    -D CMAKE_COLOR_DIAGNOSTICS=OFF
    -D CMAKE_VERBOSE_MAKEFILE=ON
    -D BUILD_SHARED_LIBS=ON
    -Wno-dev
    -D CMAKE_BUILD_TYPE=Release
    -D MFEM_USE_MPI=YES
    -D MFEM_USE_CUDA=YES
    -D CMAKE_NVCC_FLAGS=-allow-unsupported-compiler
[...]
```

but I still get:

```
  #$ "/scratch/projects/compilers/intel24.1/oneapi/mpi/2021.12/bin"/mpicxx
  -D__CUDA_ARCH__=520 -E -x c++ -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__
  -D__NVCC__ "-I/opt/apps/cuda/11.4/bin/../targets/x86_64-linux/include"
  -D__CUDACC_VER_MAJOR__=11 -D__CUDACC_VER_MINOR__=4
  -D__CUDACC_VER_BUILD__=120 -D__CUDA_API_VER_MAJOR__=11
  -D__CUDA_API_VER_MINOR__=4 -include "cuda_runtime.h" -m64
  "CMakeCUDACompilerId.cu" -o "tmp/CMakeCUDACompilerId.cpp1.ii"

  In file included from <built-in>:1:

  In file included from
  /opt/apps/cuda/11.4/bin/../targets/x86_64-linux/include/cuda_runtime.h:83:


  /opt/apps/cuda/11.4/bin/../targets/x86_64-linux/include/crt/host_config.h:147:2:
  error: -- unsupported clang version! clang version must be less than 13 and
  greater than 3.2 .  The nvcc flag '-allow-unsupported-compiler' can be used
  to override this version check; however, using an unsupported host compiler
  may cause compilation failure or incorrect run time execution.  Use at your
  own risk.

    147 | #error -- unsupported clang version! clang version must be less than 13 and greater than 3.2 . The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
        |  ^

  1 error generated.

  # --error 0x1 --





Call Stack (most recent call first):
  /opt/apps/cmake/3.24.2/share/cmake-3.24/Modules/CMakeDetermineCompilerId.cmake:6 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /opt/apps/cmake/3.24.2/share/cmake-3.24/Modules/CMakeDetermineCompilerId.cmake:48 (__determine_compiler_id_test)
  /opt/apps/cmake/3.24.2/share/cmake-3.24/Modules/CMakeDetermineCUDACompiler.cmake:307 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:120 (enable_language)
```

**Comment by v-dobrev** [comment] 2024-09-30 22:49
Try using `CMAKE_CUDA_FLAGS` instead of `CMAKE_NVCC_FLAGS` -- I'm not finding the latter in the CMake docs.

**Comment by VictorEijkhout** [comment] 2024-09-30 23:48
Cmake:
```
cmake
    -D CMAKE_INSTALL_PREFIX=/work/00434/eijkhout/mfem/installation-mfem-4.7-milan-gcc13-impi19.0.9
    -D CMAKE_COLOR_DIAGNOSTICS=OFF
    -D CMAKE_VERBOSE_MAKEFILE=ON
    -D BUILD_SHARED_LIBS=ON
    -Wno-dev
    -D CMAKE_BUILD_TYPE=Release
    -D MFEM_USE_MPI=YES
    -D MFEM_USE_CUDA=YES
    -D CMAKE_CUDA_FLAGS=-allow-unsupported-compiler
    -D MFEM_USE_PETSC=NO
    -D MFEM_USE_LAPACK=YES
[...]
```

output:
```
  #$ INCLUDES="-I/opt/apps/cuda/11.4/bin/../targets/x86_64-linux/include"

  #$ LIBRARIES= "-L/opt/apps/cuda/11.4/bin/../targets/x86_64-linux/lib/stubs"
  "-L/opt/apps/cuda/11.4/bin/../targets/x86_64-linux/lib"

  #$ CUDAFE_FLAGS=

  #$ PTXAS_FLAGS=

  #$ rm tmp/a_dlink.reg.c

  #$
  "/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin"/mpicxx
  -D__CUDA_ARCH__=520 -E -x c++ -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__
  -D__NVCC__ "-I/opt/apps/cuda/11.4/bin/../targets/x86_64-linux/include"
  -D__CUDACC_VER_MAJOR__=11 -D__CUDACC_VER_MINOR__=4
  -D__CUDACC_VER_BUILD__=120 -D__CUDA_API_VER_MAJOR__=11
  -D__CUDA_API_VER_MINOR__=4 -include "cuda_runtime.h" -m64
  "CMakeCUDACompilerId.cu" -o "tmp/CMakeCUDACompilerId.cpp1.ii"

  In file included from
  /opt/apps/cuda/11.4/bin/../targets/x86_64-linux/include/cuda_runtime.h:83,

                   from <command-line>:


  /opt/apps/cuda/11.4/bin/../targets/x86_64-linux/include/crt/host_config.h:139:2:
  error: #error -- unsupported GNU version! gcc versions later than 11 are
  not supported! The nvcc flag '-allow-unsupported-compiler' can be used to
  override this version check; however, using an unsupported host compiler
  may cause compilation failure or incorrect run time execution.  Use at your
  own risk.

    139 | #error -- unsupported GNU version! gcc versions later than 11 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
```

**Comment by v-dobrev** [comment] 2024-10-01 05:48
It looks like the CUDA compiler detection does not use `CMAKE_CUDA_FLAGS` for some reason. Can you check if that is indeed the case in the log output? What do the full `nvcc` command lines look like?

Another thing: there's small chance that this issue may be resolved in newer CMake versions. Do you have a newer CMake version you can try?

**Comment by v-dobrev** [comment] 2024-10-01 06:14
Another option to try is setting `CUDAFLAGS` to `-allow-unsupported-compiler` instead of setting `CMAKE_CUDA_FLAGS` to the same value -- I'm sure it will make any difference but it's worth a try.

**Comment by VictorEijkhout** [comment] 2024-10-01 10:30
Using cmake 3.29 and `export CUDAFLAGS=....` and still no dice.

Say, cmake outputs stuff that I've never seen before:
```
  #$ INCLUDES="-I/opt/apps/cuda/11.4/bin/../targets/x86_64-linux/include"

  #$ LIBRARIES= "-L/opt/apps/cuda/11.4/bin/../targets/x86_64-linux/lib/stubs"
  "-L/opt/apps/cuda/11.4/bin/../targets/x86_64-linux/lib"

  #$ CUDAFE_FLAGS=

  #$ PTXAS_FLAGS=

  #$ rm tmp/a_dlink.reg.c

  #$
  "/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin"/mpicxx
  -D__NV_NO_HOST_COMPILER_CHECK=1 -D__CUDA_ARCH__=520 -E -x c++
  -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__ -D__NVCC__
  "-I/opt/apps/cuda/11.4/bin/../targets/x86_64-linux/include"
  -D__CUDACC_VER_MAJOR__=11 -D__CUDACC_VER_MINOR__=4
  -D__CUDACC_VER_BUILD__=120 -D__CUDA_API_VER_MAJOR__=11
  -D__CUDA_API_VER_MINOR__=4 -include "cuda_runtime.h" -m64
  "CMakeCUDACompilerId.cu" -o "tmp/CMakeCUDACompilerId.cpp1.ii"

  #$ cicc --c++17 --gnu_version=130200 --orig_src_file_name
  "CMakeCUDACompilerId.cu" --allow_managed -arch compute_52 -m64
  --no-version-ident -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1
  --include_file_name "CMakeCUDACompilerId.fatbin.c" -tused
  --gen_module_id_file --module_id_file_name
  "tmp/CMakeCUDACompilerId.module_id" --gen_c_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.c" --stub_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.stub.c" --gen_device_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.gpu" "tmp/CMakeCUDACompilerId.cpp1.ii" -o
  "tmp/CMakeCUDACompilerId.ptx"
```

Does that give any hint as to what cmake is doing? 
1. there is something about flags in there
2. is it possible to let cmake output more diagnostics?

**Comment by jandrej** [comment] 2024-10-01 16:26
I have never seen output like this either, unless I specifically told cmake to provide it. Do you mind sharing the complete environment configuration so we can judge what's going on?

FWIW I'm using cmake on lmod based systems and don't run into issues like this. It might be worth working with/involving your sysadmins because it is impossible for us to reproduce the environment and know what they might have configured for your particular deployment.

**Comment by VictorEijkhout** [comment] 2024-10-01 18:35
This enough?
[mfemconfig.zip](https://github.com/user-attachments/files/17214397/mfemconfig.zip)

**Comment by jandrej** [comment] 2024-10-01 18:51
I would try invoking nvcc by passing the options `-Xcompiler -std=gnu++14`, which will set the host compiler c++'s dialect version to match nvcc's toolchain.

Or just set the std to c++17 with cmake.

**Comment by VictorEijkhout** [comment] 2024-10-01 20:05
> I would try invoking nvcc by passing the options `-Xcompiler -std=gnu++14`, which will set the host compiler c++'s dialect version to match nvcc's toolchain.
> 
> Or just set the std to c++17 with cmake.

And that is the winning suggestion. The cmake config when t through and the build is running.

**Comment by v-dobrev** [comment] 2024-10-01 20:08
As I was writing this post, I see that you got things working. 🎉 For completeness, here's what I was writing:

From the above-posted log file, it looks like the flag `-allow-unsupported-compiler` is now being used (I'm not sure if that's due to `export CUDAFLAGS=...`, or `-D CMAKE_CUDA_FLAGS=...`, or both), so that's not the issue anymore.

Also from the log file, it looks like the Intel LLVM compiler is using c++ headers from gcc 13 and the nvidia intermediate compiler (`cicc` which is run with `--c++14`) does not like some of those headers from gcc 13. One option is to try to tell `nvcc` (and `cicc`) to use C++17 standard using `CMAKE_CXX_STANDARD=17` (MFEM's cmake will copy this value to `CMAKE_CUDA_STANDARD` as well). It may also be possible to get this to work by explicitly setting the standard to `CMAKE_CXX_STANDARD=11` or `14`.

**Comment by VictorEijkhout** [comment] 2024-10-03 00:55
Hm. It went through once, but I can not reproduce that.

gcc13:

```
  #$ "/scratch/tacc/apps/gcc/13.2.0/bin"/c++ -D__NV_NO_HOST_COMPILER_CHECK=1
  -D__CUDA_ARCH__=520 -E -x c++ -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__
  -D__NVCC__ -std=gnu++17 -std=gnu++17
  "-I/opt/apps/cuda/11.4/bin/../targets/x86_64-linux/include"
  -D__CUDACC_VER_MAJOR__=11 -D__CUDACC_VER_MINOR__=4
  -D__CUDACC_VER_BUILD__=120 -D__CUDA_API_VER_MAJOR__=11
  -D__CUDA_API_VER_MINOR__=4 -include "cuda_runtime.h" -m64
  "CMakeCUDACompilerId.cu" -o "tmp/CMakeCUDACompilerId.cpp1.ii"

  #$ cicc --c++17 --gnu_version=130200 --orig_src_file_name
  "CMakeCUDACompilerId.cu" --allow_managed -arch compute_52 -m64
  --no-version-ident -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1
  --include_file_name "CMakeCUDACompilerId.fatbin.c" -tused
  --gen_module_id_file --module_id_file_name
  "tmp/CMakeCUDACompilerId.module_id" --gen_c_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.c" --stub_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.stub.c" --gen_device_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.gpu" "tmp/CMakeCUDACompilerId.cpp1.ii" -o
  "tmp/CMakeCUDACompilerId.ptx"

  /usr/include/stdlib.h(140): error: identifier "_Float32" is undefined
```

intel 2024:

```
  #$ "/scratch/projects/compilers/intel24.1/oneapi/compiler/2024.1/bin"/icpx
  -D__NV_NO_HOST_COMPILER_CHECK=1 -D__CUDA_ARCH__=520 -E -x c++
  -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__ -D__NVCC__ -std=gnu++17
  -std=gnu++17 "-I/opt/apps/cuda/11.4/bin/../targets/x86_64-linux/include"
  -D__CUDACC_VER_MAJOR__=11 -D__CUDACC_VER_MINOR__=4
  -D__CUDACC_VER_BUILD__=120 -D__CUDA_API_VER_MAJOR__=11
  -D__CUDA_API_VER_MINOR__=4 -include "cuda_runtime.h" -m64
  "CMakeCUDACompilerId.cu" -o "tmp/CMakeCUDACompilerId.cpp1.ii"

  #$ cicc --c++14 --clang --clang_version=180000 --orig_src_file_name
  "CMakeCUDACompilerId.cu" --unicode_source_kind=UTF-8 --allow_managed -arch
  compute_52 -m64 --no-version-ident -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1
  --include_file_name "CMakeCUDACompilerId.fatbin.c" -tused
  --gen_module_id_file --module_id_file_name
  "tmp/CMakeCUDACompilerId.module_id" --gen_c_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.c" --stub_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.stub.c" --gen_device_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.gpu" "tmp/CMakeCUDACompilerId.cpp1.ii" -o
  "tmp/CMakeCUDACompilerId.ptx"


  /scratch/tacc/apps/gcc/13.2.0/lib/gcc/x86_64-pc-linux-gnu/13.2.0/../../../../include/c++/13.2.0/ext/type_traits.h(226):
  error: parameter pack "_Tp" was referenced but not expanded
```

**Comment by v-dobrev** [comment] 2024-10-03 13:12
Are you using `-DCMAKE_CXX_STANDARD=17` or are you doing something else?

**Comment by v-dobrev** [comment] 2024-10-03 13:19
I notice one difference: before the host compiler was the MPI wrapper (e.g. `"/opt/intel/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin"/mpicxx`) and now it is not an MPI wrapper -- I'm not sure if that matters.

**Comment by VictorEijkhout** [comment] 2024-10-07 14:20
Gcc 13, using c++14:

```
  /usr/include/bits/mathcalls.h(57): error: identifier "_Float32" is
  undefined
```

This code seems uncompilable with cuda.

**Comment by VictorEijkhout** [comment] 2024-10-07 14:27
Nvidia system with nvidia 24.7:
```
  #$ "/opt/apps/gcc14/cuda12/openmpi/5.0.5/bin"/mpicxx




  /opt/apps/gcc/14.2.0/include/c++/14.2.0/type_traits(695): error: identifier
  "__is_reference" is undefined

        : public __bool_constant<__is_reference(_Tp)>
                                 ^



  /opt/apps/gcc/14.2.0/include/c++/14.2.0/type_traits(731): error: type name
  is not allowed

        : public __bool_constant<__is_object(_Tp)>
```

**Comment by v-dobrev** [comment] 2024-10-07 18:17
At this point I'll just suggest you try using a host compiler that is supported by the CUDA version you are using, or try a newer CUDA version that supports the host compilers that you want to use.

If you really need to use a CUDA version with unsupported compilers, I can still try to help, however these issues seem more like system configuration issues than mfem related issues.

**Closed** 2024-11-24 21:35 UTC
Labels: building
