### ISSUE TITLE
GetVectorValue  for ParGridFunction

### ISSUE THREAD

**Issue by stefanozampini** [mfem/mfem#1585] opened 2020-06-28 20:48 UTC
The signature of these methods have been recently changed 5ab8dfc15ca331432b42a2fb8df59880cf88ee59, and we can no longer use `void GetVectorValue(int i, const IntegrationPoint &ip, Vector &val) const` with a `ParGridFunction`. `GetValue` can still be used. Is this an oversight? 

 /home/szampini/Devel/petscopt/src/mfemopt/objective.cpp: In member function ‘virtual void mfemopt::TDLeastSquares::Eval(const mfem::Vector&, const mfem::Vector&, double, double*)’:
/home/szampini/Devel/petscopt/src/mfemopt/objective.cpp:482:25: error: cannot convert ‘int’ to ‘mfem::ElementTransformation&’
  482 |       u->GetVectorValue(eid,ip,E);
      |                         ^~~
      |                         |
      |                         int

**Comment by mlstowell** [comment] 2020-06-29 18:42
Hi, @stefanozampini ,

We certainly didn't intend to disable these pre-existing `GetValue` and `GetVectorValue` methods.  I suspect the problem is that we recently made `void GridFunction::GetVectorValue(ElementTransformation &T,  const IntegrationPoint &ip, Vector &val, Vector *tr = NULL) const` a `virtual` method but `void GridFunction::GetVectorValue(int i, const IntegrationPoint &ip, Vector &val) const` is not `virtual`.

As a temporary workaround you can probably change the displayed line to `u->GridFunction::GetVectorValue(eid, ip, E);`.

This is something I can add to our new unit tests.    We currently have a couple of related PRs being tested in `next`.  I'll try to put together a bug fix which will be compatible with the other PRs.

Sorry for the trouble.

Best wishes,
Mark

**Comment by termi-official** [comment] 2020-06-29 21:31
I want to note that `void GetVectorValue(int i, const IntegrationPoint &ip, Vector &val) const` does not work as expected in parallel, because it is not virtual/derived in the `ParGridFunction`. The problem here is, that `void GetVectorValue(int i, const IntegrationPoint &ip, Vector &val) const` is unable to access shared dofs, while `void GetValue(int i, const IntegrationPoint &ip, Vector &val) const` can. 
I thought this is part of #1529, but it seems like I really misread the PRs description.

**Comment by stefanozampini** [comment] 2020-06-29 21:44
I think the old behavior is semantically correct since `GetVectorValue` and `GetValue` should not need shared dofs, being FEM  a local discretization technique. The value of the function is completely specified by the element index and the integration point. Then, if you want to extend these methods to support something different for DG like methods is fine, but the old behaviour was working properly.

**Comment by termi-official** [comment] 2020-06-29 22:55
Sorry I was imprecise, so let me try to explain where I see an issue, since my point was not about semantic correctness, but about semantic inconsistency.

Some error estimators need information about the jump information in the gradient along element interfaces. Now in parallel, these interface may be also a process boundary, such that some faces have half-faces owned by a different processes. To estimate the jump we can choose matching integration points (on each half-face) and evaluate locally on each element. Now, if one of the faces is on a process-boundary, then I need information about a half-face residing on an adjacent process. Now `GetValue` is overridden and accessing the shared dof works as expected in a `ParGridFunction` (after calling `ExchangeFaceNbrData`). However, the semantics of `GetVectorValue` differs here, because it is not virtual and therefore unable to access the non-local half-face information. This semantic difference was also present before the mentioned PR has been merged.

**Comment by v-dobrev** [comment] 2020-06-30 03:35
The issue is that the new method in `ParGridGunction`: https://github.com/mfem/mfem/blob/551f5077091db02fae54773728d13eb8f4b67c76/fem/pgridfunc.hpp#L216-L219

is hiding the version inherited from `GridFunction`, so we need to add `using GetVectorValue;` in `ParGridFunction`.

This should fix @stefanozampini's issue.

However, it is better to re-implement it to support face-neighbor elements (these have indices >= the local number of elements). This may be useful, if one wants to evaluate values in face-neighbor elements, which happens typically in DG context.

**Comment by mlstowell** [comment] 2020-06-30 03:48
Thanks, @v-dobrev , that's exactly what I'm working on.  I've also expanded the unit tests to catch this type of error.  I'm also implementing the `GetValue` and `GetVectorValue` methods for map type `INTEGRAL` so that the tests will be more uniform.

I'm just putting on the finishing touches and it should be ready any minute.

**Comment by mlstowell** [comment] 2020-06-30 04:23
@termi-official , PR #1529 was only concerned with the newer `GetValue` and `GetVectorValue` methods which take an `ElementTransformation` object as their first argument.  The intention was to leave the original `GetValue` and `GetVectorValue` methods unchanged but we accidentally hid the `GridFunction::GetVectorValue` method from `ParGridFunction` objects by providing an override for only the newer version of this method.

PR #1589 should address this issue and it also updates the older implementations so that they should both work across processor boundaries, as you described, and they should now support scalar fields using the `INTEGRAL` map type.

Please let us know if you notice any problems.

**Comment by tzanio** [comment] 2020-07-04 00:37
This will be resolved by #1589. See that PR for further discussion.

**Closed by tzanio** 2020-07-04 00:37 UTC
Labels: bug, fem, high-priority
